import type { CounterStrikeEditorial } from './counter-strike-editorials.data';

export const COUNTER_STRIKE_STATISTICAL_EDITORIALS: readonly CounterStrikeEditorial[] = [
  {
    slug: 'ropz-playoff-effect-and-the-friday-dip',
    number: '035',
    title: 'The ropz Playoff Effect—and the Friday Dip',
    shortTitle: 'ropz: playoffs and Fridays',
    dek: 'His Saturday and Sunday rating is enormous because those are the days elite Counter-Strike stages semi-finals and finals. Once the calendar is read correctly, the interesting day-of-week question moves to the bottom: Tuesday is lowest, but Friday is the result worth watching.',
    verdict: 'The uplift belongs to the bracket, not the weekend.',
    verdictDetail: 'ropz averaged 1.269 on Saturdays and Sundays because that sample is dominated by the matches Vitality survived to play: semi-finals and finals. It should be described as a playoff-stage signal, not a calendar effect. Tuesday produced his lowest observed mean at 0.995 over only eight maps; Friday’s 1.014 over 23 maps is the more credible candidate for a genuine weak-day pattern.',
    readingMinutes: 13,
    publishedAt: '2026-09-02',
    dataCutoff: '1 September 2026, before that day’s matches',
    sample: 'A screening universe of 577 matches, 1,285 maps and 12,850 player-map rows across 22 top-level 2026 event stages. The selected ropz analysis uses all 121 of his 2026 Vitality maps in the dataset: 50 series at 12 events from 14 January through 31 August. Maps are equally weighted. The source does not expose a standardised stage field, so weekend is treated as a playoff-heavy schedule proxy rather than an independently testable cause.',
    heroStats: [
      { value: '20–1', label: 'Weekend series record', detail: 'The selection mechanism behind the headline split' },
      { value: '+0.185', label: 'Playoff-heavy weekend lift', detail: 'Descriptive stage proxy, not a day-of-week effect' },
      { value: '0.995', label: 'Tuesday rating', detail: 'Lowest mean, but only eight maps' },
      { value: '1.014', label: 'Friday rating', detail: 'Second-lowest mean across a stronger 23-map sample' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'The correction',
        title: 'Saturday and Sunday are not neutral treatments. They are where the bracket ends.',
        paragraphs: [
          'The first pass found a striking split: ropz averaged 1.269 over 53 Saturday and Sunday maps and 1.084 over 68 weekday maps. Calling that a weekend anomaly was wrong. In elite Counter-Strike, the calendar is part of the tournament format. Semi-finals and finals are normally scheduled on Saturday and Sunday, so day of week is carrying information about stage, survival and team form.',
          'Vitality’s record makes the confound impossible to miss. They played 21 weekend series in the sample and won 20. During weekdays they went 20–9. A team does not arrive at Sunday through random assignment; it arrives by winning the earlier matches. Weekend maps therefore select tournaments in which Vitality are functioning well and matches important enough to sit at the end of the schedule.',
          'The correct label is a playoff-heavy weekend split. It can motivate a hypothesis that ropz improves in late-bracket Counter-Strike, but it cannot show that Saturday or Sunday causes the improvement. Event and map adjustment do not repair a missing stage variable. The article is built around that correction rather than hiding it in a limitations paragraph.',
        ],
        stats: [
          { value: '95.2%', label: 'Weekend series wins', detail: '20 wins from 21 Vitality series' },
          { value: '69.0%', label: 'Weekday series wins', detail: '20 wins from 29 Vitality series' },
          { value: '+26.2 pp', label: 'Selection gap', detail: 'Why the raw rating split cannot be causal' },
        ],
        callout: 'The original calendar interpretation fails. The defensible observation is that ropz rates higher in the playoff-heavy portion of Vitality’s schedule.',
      },
      {
        number: '02',
        eyebrow: 'What remains interesting',
        title: 'ropz still moves more than the rest of Vitality when the tournament reaches its final days.',
        paragraphs: [
          'Schedule selection explains why the whole team should look better on weekends. It does not automatically explain why ropz moves the most. His weekend-minus-weekday change was +0.185 rating points. The corresponding changes were +0.091 for flameZ, +0.064 for ZywOo, +0.047 for mezii and +0.035 for apEX.',
          'Restricting the comparison to series Vitality won leaves ropz at 1.289 on weekend maps and 1.107 on weekday maps, a +0.183 difference. The win-only differences for the regular teammates were +0.029 for flameZ, −0.009 for mezii, −0.067 for apEX and −0.099 for ZywOo. Merely removing losses does not reproduce ropz’s shape.',
          'But that is still not a clean playoff estimate. Weekend wins include stronger Vitality tournaments, different opponents, arena matches and later veto information. Relative to the mean of his four teammates on the same maps, ropz improved by +0.119 between weekdays and weekends; the series-block bootstrap interval was −0.044 to +0.272. The point estimate is interesting, while the uncertainty still admits no player-specific change.',
        ],
        table: {
          caption: 'Rating change in the playoff-heavy weekend sample',
          headers: ['Player', 'Weekend mean', 'Weekday mean', 'Difference', 'Maps'],
          rows: [
            ['ropz', '1.269', '1.084', '+0.185', '53 / 68'],
            ['flameZ', '1.283', '1.192', '+0.091', '53 / 68'],
            ['ZywOo', '1.476', '1.412', '+0.064', '53 / 68'],
            ['mezii', '1.103', '1.055', '+0.047', '48 / 64'],
            ['apEX', '1.038', '1.004', '+0.035', '53 / 68'],
          ],
          note: 'These are descriptive schedule splits, not estimates of a causal weekend effect. mezii has fewer maps because Vitality used a substitute at Porto.',
        },
        callout: 'The useful follow-up is “does ropz gain more than his teammates in semi-finals and finals?”, not “does ropz like weekends?”',
      },
      {
        number: '03',
        eyebrow: 'Stage hypothesis',
        title: 'A playoff effect is plausible, but this dataset cannot yet identify it cleanly.',
        paragraphs: [
          'The broad consistency is why the result remains worth investigating. Nine of ten events containing both weekday and weekend maps produced a positive ropz split. Removing any entire event left the aggregate difference positive, between +0.161 and +0.208. Six maps with reasonable observations on both sides also pointed in the same direction.',
          'Those checks reject a narrow explanation such as one exceptional final or one favourite map. They do not reject tournament-stage confounding, because the same scheduling rule operates across events and maps. A repeated confound produces a repeated result. Consistency is valuable only after the variable has been interpreted correctly.',
          'A proper stage analysis needs each series labelled group, quarter-final, semi-final or final. It should compare ropz with other players in the same stage, condition on opponent strength and map, and cluster uncertainty by event. The current machine-readable source contains dates, events, maps, teams and player ratings but no normalised round-of-tournament field. Until that field is added manually, “playoff effect” is the hypothesis rather than the measurement.',
        ],
        table: {
          caption: 'What the existing robustness checks do—and do not—establish',
          headers: ['Check', 'Result', 'What it rules out', 'What remains'],
          rows: [
            ['Events with both samples', '9 / 10 positive', 'One-event outlier', 'Shared playoff scheduling'],
            ['Leave one event out', '+0.161 to +0.208', 'Single-event dependence', 'Stage and survival selection'],
            ['Adequately sampled maps', '6 / 6 positive', 'One-map veto artefact', 'Later-stage map preparation'],
            ['Event + map adjustment', '+0.152', 'Average event/map composition', 'Explicit tournament stage'],
            ['Event + map + opponent', '+0.030', 'Much of observed composition', 'Sparse, near-saturated model'],
          ],
          note: 'The strict three-way estimate is unstable because 121 maps are divided among 12 events, eight maps and many opponents. It is evidence for caution, not a precise null effect.',
        },
      },
      {
        number: '04',
        eyebrow: 'The actual day-of-week question',
        title: 'Tuesday is the observed low. Friday is the stronger warning.',
        paragraphs: [
          'Once Saturday and Sunday are removed from the search for a weak day, Tuesday has the lowest observed rating: 0.995 across eight maps. Friday follows at 1.014 across 23. Monday, Wednesday and Thursday sit between 1.130 and 1.171. Numerically, the answer to “which day is worst?” is Tuesday.',
          'The denominator changes the interpretation. Eight Tuesday maps can be moved dramatically by one series. Friday contains almost three times as many maps and remains roughly 0.105 rating points below ropz’s other weekdays combined. Tuesday is approximately 0.100 below the other weekdays, but with far less information. Friday is therefore the better candidate for a repeatable dip even though Tuesday owns the lower displayed mean.',
          'There is an obvious schedule explanation here too. Friday often acts as the transition between group play and the weekend bracket: qualification matches, quarter-finals or the last opportunity to survive. The same principle applies—day names are labels for tournament structure. Unlike the weekend result, however, Friday is not automatically selecting only teams that have already reached the final rounds, which makes the negative result less mechanically predetermined.',
        ],
        bars: [
          { label: 'Sunday', value: 100, display: '1.278', detail: '28 maps · final-heavy' },
          { label: 'Monday', value: 88, display: '1.130', detail: '12 maps' },
          { label: 'Tuesday', value: 78, display: '0.995', detail: '8 maps · lowest mean' },
          { label: 'Wednesday', value: 92, display: '1.171', detail: '13 maps' },
          { label: 'Thursday', value: 89, display: '1.134', detail: '12 maps' },
          { label: 'Friday', value: 79, display: '1.014', detail: '23 maps · stronger downside sample' },
          { label: 'Saturday', value: 98, display: '1.258', detail: '25 maps · semi-final-heavy' },
        ],
        callout: 'Literal answer: Tuesday, 0.995 over eight maps. Analytical answer: Friday, 1.014 over 23 maps, is the weak-day pattern with enough volume to monitor.',
      },
      {
        number: '05',
        eyebrow: 'How much should Friday matter?',
        title: 'A 23-map dip is a lead, not a conclusion.',
        paragraphs: [
          'Friday’s 1.014 is 0.105 below the 1.119 equal-map mean from ropz’s other 45 weekdays. That comparison deliberately excludes Saturday and Sunday so playoff scheduling cannot inflate the reference group. Tuesday’s 0.995 is 0.100 below the other 60 weekday maps. The two apparent weak days therefore have similar effect sizes and very different sample sizes.',
          'Neither split was pre-registered. Tuesday and Friday were identified after looking across all seven days, alongside several other player-context families. Ordinary significance tests would understate the probability of finding an extreme-looking day somewhere in that search. There is also no adjustment here for opponent, match start time, online versus LAN, travel or tournament round.',
          'Friday becomes useful as a forecast only prospectively. If the remaining 2026 calendar adds another 15–20 Friday maps and the rating remains around 1.01 while Monday through Thursday stay materially higher, the pattern becomes difficult to dismiss. If it immediately regresses toward his normal level, the current result was a schedule-specific fluctuation.',
        ],
        stats: [
          { value: '−0.105', label: 'Friday weekday gap', detail: 'Versus Monday–Thursday combined' },
          { value: '−0.100', label: 'Tuesday weekday gap', detail: 'Versus the other four weekdays' },
          { value: '23 vs 8', label: 'Sample advantage', detail: 'Why Friday is more informative despite rating higher' },
        ],
      },
      {
        number: '06',
        eyebrow: 'Interpretation discipline',
        title: 'The calendar describes the competition before it describes the player.',
        paragraphs: [
          'Tournament schedules are not background noise. They encode stage, survival, arena access, format and frequently opponent quality. Any esports day-of-week analysis should begin by asking what kind of match is normally played on that day. Saturday and Sunday answered that question immediately: semi-finals and finals.',
          'That does not make calendar splits useless. It makes them diagnostic. The weekend result suggests a stage interaction worth measuring explicitly. The Friday result suggests a possible transition-day weakness worth testing against quarter-final and elimination status. Tuesday’s tiny low suggests only that eight maps happened to average below one.',
          'The hierarchy of claims is now clear. Proven in this sample: ropz rated highest on the playoff-heavy weekend and lowest on Tuesday. Better-supported downside candidate: Friday, because it has 23 maps. Plausible explanation: tournament stage. Not established: a physiological day-of-week effect, an inherent big-game trait or a causal Friday penalty.',
        ],
        callout: 'A day label is not an explanation. It is often compressed metadata about where a team is in the bracket.',
      },
      {
        number: '07',
        eyebrow: 'The corrected test',
        title: 'Track stage first, then ask whether any day remains.',
        paragraphs: [
          'For the remaining 2026 events, every Vitality series should be labelled by tournament round before its result is added: group, qualification or elimination match, quarter-final, semi-final and final. The analysis should then estimate ropz’s player-by-stage interaction relative to his teammates, with map, opponent and event controls and uncertainty clustered by series and event.',
          'The Friday question should be frozen separately. Record every new Friday map without exclusions and compare it only with Monday through Thursday. The current benchmark is 1.014 over 23 maps and a −0.105 gap. Tuesday remains reported, but its eight-map discovery sample is too small to deserve a special causal story.',
          'If ropz retains a positive semi-final/final interaction after stage is explicitly coded, the playoff-gear storyline survives. If stage absorbs the entire weekend split, the scheduling explanation wins. If Friday remains weak after stage and opponent adjustment, then the genuinely strange day-of-week result was hiding at the opposite end of the graph.',
        ],
        table: {
          caption: 'Pre-registered follow-up ledger',
          headers: ['Question', 'Current benchmark', 'Required comparison', 'Failure condition'],
          rows: [
            ['Playoff gear?', '+0.185 weekend proxy', 'Explicit semi/final interaction vs teammates', 'Stage-adjusted effect approaches zero'],
            ['Friday dip?', '1.014; −0.105 vs other weekdays', 'New Friday maps vs Mon–Thu only', 'Gap regresses materially toward zero'],
            ['Tuesday weakness?', '0.995 over 8 maps', 'Accumulate a usable new sample', 'Expected small-sample regression'],
          ],
          note: 'The 1 September dataset remains frozen as discovery data. Matches after the cut-off belong only to the prospective test.',
        },
        callout: 'Final answer: call the high side a playoff-stage signal. Call Tuesday the numerical low. Watch Friday for the first day-specific pattern that might survive a larger sample.',
      },
    ],
    sources: [
      { label: 'HLTV — ropz 2026 match history', url: 'https://www.hltv.org/stats/players/matches/11816/ropz?startDate=2026-01-01&endDate=2026-09-01', use: 'Public map-by-map date, opponent, score and Rating 3.0 ledger used to audit the player split.' },
      { label: 'HLTV — ropz career history', url: 'https://www.hltv.org/stats/players/career/11816/ropz', use: 'Independent 2026 map-count cross-check for the 121-map player sample.' },
      { label: 'HLTV — ropz player profile', url: 'https://www.hltv.org/player/11816/ropz', use: 'Current team, recent match path and roster context.' },
      { label: 'CS API — interactive endpoint documentation', url: 'https://api.csapi.de/docs', use: 'Machine-readable match, map and per-map player-stat endpoints used for the full-calendar screen.' },
      { label: 'OldFella / hltv_api — source and data notes', url: 'https://github.com/OldFella/hltv_api', use: 'Open-source endpoint implementation, HLTV provenance, response schema and daily-refresh statement.' },
      { label: 'HLTV — Introducing Rating 3.0', url: 'https://www.hltv.org/news/42485/introducing-rating-30', use: 'Meaning of the rating, economy adjustment and Round Swing.' },
      { label: 'HLTV — Rating 3.0 adjustments', url: 'https://www.hltv.org/news/43047/rating-30-adjustments-go-live', use: 'Current formula context and the volatility of high-leverage single-map ratings.' },
      { label: 'Liquipedia — 2026 S-tier tournament calendar', url: 'https://liquipedia.net/counterstrike/S-Tier_Tournaments', use: 'Cross-check of the top-level event universe, dates and tournament structure.' },
    ],
  },
];
