import type { CounterStrikeEditorial } from './counter-strike-editorials.data';

export const COUNTER_STRIKE_SYSTEMS_EDITORIALS: readonly CounterStrikeEditorial[] = [
  {
    slug: 'how-replaceable-is-a-counter-strike-system-vitality-jl-experiment',
    number: '032',
    title: 'How Replaceable Is a Counter-Strike System? Vitality’s jL Experiment',
    shortTitle: 'Vitality’s jL experiment',
    dek: 'One emergency substitute, two missing players, and a live test of what actually belongs to Vitality’s system. Porto suggests the machine travels—but its T side does not travel intact.',
    verdict: 'Vitality’s system is transferable, but not plug-and-play.',
    verdictDetail: 'A 0–2 opening loss followed by six map wins in seven shows that structure survived the personnel shock. The uneven T sides show what did not: role timing, connective communication and the small decisions that make Vitality’s defaults cohere. Bucharest, where jL replaces apEX instead of mezii, is the harder test because it removes command rather than a role player.',
    readingMinutes: 16,
    publishedAt: '2026-09-01',
    dataCutoff: '1 September 2026',
    sample: 'Vitality’s four BLAST Open Porto 2026 group-stage series with jL standing in for mezii: nine maps, 198 regulation and overtime rounds, against Inner Circle, 9z, Legacy and FUT.',
    heroStats: [
      { value: '3–1', label: 'Series record', detail: 'After losing the opening series 0–2' },
      { value: '6–3', label: 'Map record', detail: 'Six wins in seven maps after the opener' },
      { value: '+24', label: 'Round differential', detail: '111 won, 87 lost across nine maps' },
      { value: '1.96', label: 'jL peak rating', detail: '38 kills in the 2–0 elimination win over 9z' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'A natural experiment',
        title: 'A stand-in reveals the joints in a team.',
        paragraphs: [
          'Roster changes are normally terrible experiments. The new player arrives with practice time, the map pool changes, the coach rewrites roles, and the opposition changes at the same time. Porto is unusually revealing because the intervention was abrupt and narrow: jL replaced mezii for family reasons while Vitality otherwise retained apEX, ropz, flameZ and ZywOo. The question is not whether jL is better or worse than mezii. It is which parts of elite team performance survive when one node in the system is replaced without a full rebuild.',
          'The nine-map sample is too small for a stable estimate of true strength, and the opposition was not uniformly elite. It is still useful as a stress test. A modular system should preserve its basic map control, recover as repetitions accumulate and allow the substitute to contribute without requiring the entire offense to orbit him. A brittle system should lose its timing, strand its stars and remain incoherent even against weaker teams.',
          'Vitality produced evidence for both propositions. They opened with the worst possible signal—an 0–2 loss in which ZywOo recorded a 0.78 series rating—then won six of the next seven maps. That recovery is too large to dismiss as pure continuity, but the route through Legacy exposed recurring T-side problems. The system remained recognisable; its connective tissue did not remain invisible.',
        ],
        callout: 'The stand-in is not the experiment’s subject. The team’s ability to absorb him is.',
      },
      {
        number: '02',
        eyebrow: 'The response curve',
        title: 'Porto was a shock, then an adaptation—not a smooth decline.',
        paragraphs: [
          'Inner Circle won Anubis 13–8 and Cache 16–13. Vitality therefore began at 21 rounds won, 29 lost and zero maps. The immediate temptation was to treat the substitute as proof that the machine had broken. The next series made that conclusion untenable: Vitality eliminated 9z 13–2 on Dust2 and 13–6 on Nuke, a 26–8 aggregate in which jL led the server with 38 kills and a 1.96 rating.',
          'Legacy then supplied the useful middle case. Vitality recovered from 2–10 to win Nuke 16–14, lost Mirage 9–13 and closed Dust2 13–8. The 38–35 aggregate was competitive rather than dominant. HLTV’s match report identified weak T sides and visible growing pains; that is consistent with a roster that can still defend within familiar protocols while rebuilding who creates, trades and communicates through an attacking round.',
          'The group-stage decider against FUT was cleaner: 13–7 on Anubis and 13–8 on Dust2. Across the last seven maps, Vitality went 6–1 and outscored opponents 90–58. Relative to the opening 21–29, the swing in round differential was 40 rounds. That is evidence of rapid adaptation, although opponent strength and map selection prevent attributing the whole swing to learning.',
        ],
        table: {
          caption: 'Vitality’s Porto group stage with jL',
          headers: ['Opponent', 'Series', 'Map record', 'Rounds', 'Round diff.'],
          rows: [
            ['Inner Circle', '0–2 loss', '0–2', '21–29', '−8'],
            ['9z', '2–0 win', '2–0', '26–8', '+18'],
            ['Legacy', '2–1 win', '2–1', '38–35', '+3'],
            ['FUT', '2–0 win', '2–0', '26–15', '+11'],
            ['Total', '3–1', '6–3', '111–87', '+24'],
          ],
          note: 'The post-opener subset is 6–1 on maps and 90–58 on rounds, a 60.8% round win rate. The full sample is 56.1%.',
        },
      },
      {
        number: '03',
        eyebrow: 'Role geometry',
        title: 'Replacing mezii removes more than his scoreboard line.',
        paragraphs: [
          'A team role is a bundle of timings, information obligations and spatial relationships. mezii’s value to Vitality is partly connective: he occupies low-resource positions, preserves optionality for the stars, communicates what his slice of the map permits, and arrives at the trade on a schedule the caller already understands. Those actions are difficult to count because a successful connection often looks like somebody else’s multikill.',
          'jL is not an inert placeholder. He is a Major MVP-level rifler whose instincts can win rounds immediately, as the 9z series demonstrated. But substituting mechanical quality does not reproduce role geometry. If he takes a duel half a second earlier, holds a different line, or reports uncertainty using a different threshold, every dependent decision shifts. On CT sides, local protocols can contain that variance. On T sides, where five players must sequence utility, territory and rotations, it compounds.',
          'This explains why “the substitute had a good rating” and “the team’s offense lost coherence” can both be true. Individual output measures whether jL converted his opportunities. Team shape measures whether the same opportunities were being created for everybody. Porto’s recovery says jL could learn the interfaces quickly; the Legacy series says the interfaces were real.',
        ],
        stats: [
          { value: '38', label: 'jL kills vs 9z', detail: 'The highest-output demonstration of immediate fit' },
          { value: '46–47', label: 'jL K–D vs Legacy', detail: 'Near-even during the most tactically uneven series' },
          { value: '0.78', label: 'ZywOo rating in opener', detail: 'The system shock reached its most protected star' },
        ],
      },
      {
        number: '04',
        eyebrow: 'What persisted',
        title: 'The recovery identifies Vitality’s portable infrastructure.',
        paragraphs: [
          'Three properties survived. First, the veto still produced playable maps. Vitality used Dust2 three times after the opening loss and won all three by a combined 39–16. A familiar map can reduce the substitute’s decision tree, and the results suggest the team found a stable base from which to add complexity.',
          'Second, high-end individual correction survived. jL could dominate 9z; apEX produced 101.7 ADR in the FUT qualification series; ZywOo recovered from the 0.78 opener to a 1.82 rating against 9z and led the difficult Legacy win at 1.19. The system did not permanently suppress its stars when the first configuration failed.',
          'Third, the team could update between series. Winning 90 of 148 rounds after the opener is not merely scraping through brackets. Even allowing for weaker opposition, a 60.8% round rate indicates that coaches, caller and players reduced the most damaging misunderstandings. This is the strongest evidence that Vitality owns shared protocols rather than a set of memorised plays dependent on exactly five people.',
        ],
        bars: [
          { label: 'Opening series', value: 72, display: '42.0%', detail: '21 of 50 rounds won' },
          { label: 'Next seven maps', value: 100, display: '60.8%', detail: '90 of 148 rounds won' },
          { label: 'Full group stage', value: 92, display: '56.1%', detail: '111 of 198 rounds won' },
        ],
        callout: 'Portable structure does not mean identical performance. It means the team can locate errors and rebuild shared expectations before the event is over.',
      },
      {
        number: '05',
        eyebrow: 'What degraded',
        title: 'The T side is where a missing relationship becomes a missing round.',
        paragraphs: [
          'Defense allows more modularity. A player can be given a site, a rotation rule and a compact set of responses. Attack is relational: an entry depends on the flash, the flash depends on the caller’s read, the lurk depends on the rotation timing, and the late-round player depends on all four communicating what is no longer possible. One unfamiliar timing can invalidate the rest of the sequence.',
          'That distinction fits Porto better than a generic chemistry explanation. Vitality’s worst stretch against Legacy occurred while their attacks stalled, yet their defensive base and individual quality kept Nuke recoverable. The comeback from 2–10 to 16–14 is simultaneously impressive and diagnostic: the roster could solve the map after the side switch, but had first allowed a huge structural deficit to form.',
          'The implication is not that mezii is uniquely irreplaceable. It is that his task graph contains more edges than a rating table shows. A substitute can learn positions in hours; he cannot instantly reproduce thousands of conditioned expectations. Vitality’s performance improved when the team reduced that graph—leaning on comfortable maps, clearer assignments and direct firepower.',
        ],
        callout: 'A role player’s hidden statistic is the number of teammate decisions that become easier because he behaves as expected.',
      },
      {
        number: '06',
        eyebrow: 'The second intervention',
        title: 'Bucharest changes the experiment from execution to command.',
        paragraphs: [
          'Porto is only the first half of the study. jL stood in for mezii there; at PGL Bucharest he is scheduled to replace apEX. Those are not equivalent substitutions. Removing mezii perturbs role allocation and communication while leaving the in-game leader in place. Removing apEX changes who compresses information into a call, who sets the team’s risk tolerance and who carries authority when the first plan fails.',
          'If Vitality remain tactically coherent in Bucharest, the result would imply that more of apEX’s decision system has been distributed through preparation, coaching and shared player models than observers assume. If the CT sides remain strong but late T rounds fragment, that would locate command as the less transferable layer. If the entire map pool contracts, it would suggest the caller also acts as the indexing system that makes the playbook accessible under pressure.',
          'This is why the two events should never be pooled into a single “Vitality with jL” win rate without qualification. The treatment changes. Porto asks whether a mature system can absorb a different executor. Bucharest asks whether that system can execute without its primary runtime controller.',
        ],
        table: {
          caption: 'Two stand-ins, two different causal questions',
          headers: ['Event', 'Player absent', 'Layer disturbed', 'Most revealing outcome'],
          rows: [
            ['BLAST Open Porto', 'mezii', 'Roles, spacing, connective communication', 'T-side timing and site-level fit'],
            ['PGL Bucharest', 'apEX', 'Calling, authority, information synthesis', 'Late-round coherence and adaptation'],
          ],
          note: 'jL is the constant substitute, but the intervention is not constant; results should be analysed separately.',
        },
      },
      {
        number: '07',
        eyebrow: 'The falsification test',
        title: 'The playoffs can distinguish recovery from opponent effects.',
        paragraphs: [
          'The current evidence supports a bounded claim: Vitality recovered functional team structure against 9z, Legacy and FUT. It does not prove that the temporary roster preserves championship-level strength. The Porto arena playoffs increase opponent quality and preparation time; both should punish interface errors more reliably than the lower bracket did.',
          'Three measures matter more than jL’s raw rating. First, attacking-round win rate on non-eco rounds: does the offense create competitive plants and trades before individual heroics are required? Second, trade spacing around jL: is he integrated into the next action or merely surviving his own duel? Third, recovery after a failed opening plan: can the roster reach a coordinated late round with enough utility and time?',
          'The claim should weaken if Vitality’s T sides repeatedly collapse against playoff opposition while CT and individual numbers remain adequate. It should strengthen if their attacks become stable across more than Dust2 and jL’s output settles near average without reducing team efficiency. A truly modular system does not require the substitute to play like a superstar. It makes ordinary output sufficient.',
        ],
        callout: 'Provisional answer: Vitality replaced a player and kept the machine. They did not replace the relationships that make the machine efficient—at least not yet.',
      },
    ],
    sources: [
      { label: 'HLTV — jL to stand in for Vitality', url: 'https://www.hltv.org/news/45238/media-jl-to-stand-in-for-vitality', use: 'Stand-in configuration for Porto and Bucharest and the family-leave context.' },
      { label: 'HLTV — Inner Circle send Vitality to the lower bracket', url: 'https://www.hltv.org/news/45400/inner-circle-send-meziiless-vitality-to-blast-open-porto-lower-bracket', use: 'Opening scores, ZywOo rating and initial role disruption.' },
      { label: 'HLTV — Vitality eliminate 9z', url: 'https://www.hltv.org/news/45411/vitality-eliminate-9z-from-blast-open-porto', use: 'Map scores and jL and ZywOo performance in the first recovery series.' },
      { label: 'HLTV — Vitality fend off Legacy', url: 'https://www.hltv.org/news/45421/vitality-fend-off-legacy-to-stay-alive-at-blast', use: 'Three-map scores, player statistics and reported T-side difficulties.' },
      { label: 'HLTV — Vitality beat FUT to reach the playoffs', url: 'https://www.hltv.org/news/45430/vitality-crush-fut-to-secure-final-blast-porto-playoff-berth', use: 'Qualification scores, apEX output and complete recovery arc.' },
      { label: 'BLAST — Open Porto opening matches', url: 'https://blast.tv/cs/news/blast-open-porto-opening-matches', use: 'Official event framing, bracket and opening schedule.' },
    ],
  },
  {
    slug: 'valve-regional-standings-vrs-technical-explainer',
    number: '033',
    title: 'VRS Is Not a Leaderboard. It Is Counter-Strike’s Operating System.',
    shortTitle: 'How VRS really works',
    dek: 'A source-code-level guide to Valve Regional Standings: roster identity, the 180-day evidence window, prize and opponent seeding, fixed-RD Glicko updates, regional lists, invitations, and the incentives hidden inside the model.',
    verdict: 'VRS is a two-stage predictive model with governance consequences—not a tournament-points table.',
    verdictDetail: 'Valve first builds a 400–2000 prior from four normalized performance signals, then replays eligible match wins chronologically through a fixed-RD Glicko calculation. The output ranks five-player rosters and determines access to ranked events and Majors. Its transparency is a strength; its dependence on prize economics, event completion, connected opponent graphs and monthly snapshots is the cost.',
    readingMinutes: 24,
    publishedAt: '2026-09-01',
    dataCutoff: '1 September 2026',
    sample: 'Valve’s public VRS implementation and data documentation, August 2026 published standings, current Tournament Operation Requirements and current Major Supplemental Rulebook.',
    heroStats: [
      { value: '180d', label: 'Evidence window', detail: 'Six nominal 30-day months' },
      { value: '4', label: 'Active seed factors', detail: 'Prize, bounty, opponent network and LAN' },
      { value: '10', label: 'Best results retained', detail: 'Per bucketed seed signal' },
      { value: '3 / 5', label: 'Roster continuity', detail: 'Shared core required for identity and invite acceptance' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'What the number means',
        title: 'VRS estimates strength; it does not award points from a schedule.',
        paragraphs: [
          'A conventional circuit table is additive: finish third, receive a published number of points, then retain or lose them according to a calendar. VRS is different. Valve describes the target as predictive accuracy while resisting manipulation and remaining transparent. The public implementation takes match and event data, constructs an initial rating from performance signals, and then updates that rating from head-to-head results.',
          'That distinction changes how every movement should be interpreted. A team does not “earn 150 VRS points” by winning a named trophy. Prize money can improve its seed prior; beating valuable, connected opponents can improve other seed components; and each match then changes the running rating according to the two teams’ ratings at that historical moment. The final number is the output of recomputing the window, not a bank balance.',
          'The number matters far beyond bragging rights. Valve’s tournament rules use VRS lists to define who can be directly invited to ranked events. Major invitations are also drawn from regional VRS lists. A model error, timing edge or roster-identity dispute therefore changes competitive access, revenue and possibly the survival of an organization. VRS is ranking infrastructure and market infrastructure at once.',
        ],
        callout: 'The right mental model is “recalculate the competitive graph,” not “add points to a team.”',
      },
      {
        number: '02',
        eyebrow: 'The entity being ranked',
        title: 'Valve ranks a roster of players, not the logo on the jersey.',
        paragraphs: [
          'The tournament rules define a VRS ranking as a ranking of a roster consisting of five specific players. The implementation links past and present lineups when they share at least three players. That three-player core is the continuity primitive: it prevents an organization from replacing a majority of the lineup while automatically inheriting the old team’s history.',
          'The code resolves an active roster from recent participation. It examines up to the ten most recent matches and includes recent players who appeared at least five times, filling at most five slots. Historical team IDs are linked inside event context because an organization name can survive while the underlying ranked entity changes.',
          'The same principle appears at invitation time. An invited roster may accept only if at least three of the participating players belonged to the invited five, and those qualifying players must play every match. The system therefore tolerates limited substitution but makes majority continuity the price of carrying access forward.',
        ],
        table: {
          caption: 'Roster identity across the VRS stack',
          headers: ['Layer', 'Rule', 'Practical effect'],
          rows: [
            ['Model history', 'At least three shared players', 'Past matches can attach to the same roster entity'],
            ['Published entry', 'Five specific players', 'The rank belongs to a lineup, not an organization'],
            ['Active roster', 'Five-match participation in recent matches', 'Recent competitors populate the displayed lineup'],
            ['Invite acceptance', 'At least three invited players compete throughout', 'A majority core can accept; a replaced majority cannot'],
          ],
        },
      },
      {
        number: '03',
        eyebrow: 'Evidence and decay',
        title: 'The model sees six months, but the newest month is equally fresh.',
        paragraphs: [
          'The default data window is six times 30 days: 180 days. Incomplete matches, unranked matches, showmatches and matches from events still in progress are filtered out. A roster must have played at least five included matches to receive a numbered global or regional rank, and rosters with no defeated opponent are removed before standings are assigned.',
          'Age is a linear weight. Let s be the start of the 180-day window and let e be the ranking cut-off. The code sets the decay endpoint to e minus 30 days. For a match at time t, a(t) = clamp((t − s) / ((e − 30d) − s), 0, 1). The newest 30 days therefore all receive weight 1; older results decline linearly toward zero at the beginning of the window.',
          'The same age weight touches several layers: prize winnings are aged by the event’s last match, distinct defeated opponents use the most recent win, LAN wins are aged, quality-win buckets are aged, and Glicko match information is aged. When the monthly cut-off advances, every result can change value even if no team plays. That is why VRS is best understood as a snapshot of a moving evidence window.',
        ],
        stats: [
          { value: '30d', label: 'Full-weight grace period', detail: 'All results in the newest month use age weight 1' },
          { value: '5', label: 'Minimum matches', detail: 'Required for a numbered ranking' },
          { value: '1+', label: 'Opponent defeated', detail: 'No-win rosters are filtered from standings' },
        ],
        callout: 'A team can move during an idle month because its evidence—and everybody else’s—is being re-aged and re-normalized.',
      },
      {
        number: '04',
        eyebrow: 'Stage one: the seed',
        title: 'Four signals build the prior before head-to-head updates begin.',
        paragraphs: [
          'Each roster receives five calculated modifiers, but the current seed assigns zero weight to its own-network modifier. The four active inputs have equal coefficient: bounty offered, bounty collected, opponent network and LAN factor. Their arithmetic mean is the raw seed score. Across the population, that score is min–max remapped to a starting rating between 400 and 2000.',
          '“Bounty offered” is the roster’s own aged prize winnings from its ten strongest event results, normalized to the fifth-highest roster in the population and capped at 1. “Bounty collected” rewards wins over opponents with valuable bounty. “Opponent network” rewards wins over opponents that have defeated a broad set of other teams. “LAN factor” uses the ten strongest aged LAN wins. Fifth-best normalization caps the leading outliers together instead of allowing one extraordinary money winner to stretch the whole scale.',
          'Quality-win signals are bucketed. For each win, the opponent value is multiplied by match age and an event-stakes weight; only the best ten outcomes survive. Missing slots effectively count as zero because the sum is divided by ten. This rewards repeated evidence but caps volume: an eleventh weak win cannot displace a stronger top-ten result.',
        ],
        table: {
          caption: 'Current seed factors in Valve’s public implementation',
          headers: ['Factor', 'Coefficient', 'Underlying evidence', 'Main normalization'],
          rows: [
            ['Bounty offered', '1', 'Top 10 aged event winnings', 'Relative to fifth-highest roster'],
            ['Bounty collected', '1', 'Top 10 wins over high-bounty opponents', 'Curved after age and stakes weighting'],
            ['Opponent network', '1', 'Top 10 wins over well-connected opponents', 'Opponent’s distinct-win network'],
            ['LAN factor', '1', 'Top 10 aged LAN wins', 'Relative to fifth-highest roster'],
            ['Own network', '0', 'Aged distinct opponents defeated', 'Calculated but excluded from seed mean'],
          ],
          note: 'Seed = (offered + collected + opponent network + LAN) / 4, then remapped across all roster seeds to the interval [400, 2000].',
        },
      },
      {
        number: '05',
        eyebrow: 'Prize pools and stakes',
        title: 'Money is a proxy, transformed rather than copied.',
        paragraphs: [
          'Prize money enters twice in different forms. Actual winnings create the roster’s bounty offered. The event prize pool also scales the value of beating an opponent when bounty collected and opponent network are populated. Prize pools are clamped between one dollar and $1 million, then transformed as q(p) = 1 / (1 + |log10(p / 1,000,000)|).',
          'The curve is deliberately compressive. A $1 million event receives weight 1. A $100,000 event receives 0.5; $10,000 receives about 0.333; and $1,000 receives 0.25. A tenfold reduction in money does not cause a tenfold reduction in match context. Qualifiers can inherit part of a completed downstream event’s prize pool: the linked value is discounted by one half for each qualification step and the resulting effective pool remains capped at $1 million.',
          'This is why “VRS ranks teams by prize money” is both directionally understandable and technically wrong. Money initializes prestige and stakes, but opponent quality, network, LAN status, aging and head-to-head results all intervene. The defensible criticism is narrower: when money is used as a proxy for event importance, organizer economics and prize distribution become inputs to competitive access.',
        ],
        table: {
          caption: 'Event-stakes curve, q(p)',
          headers: ['Effective prize pool', 'Stakes weight', 'Relative to $1m'],
          rows: [
            ['$1,000,000', '1.000', '100.0%'],
            ['$100,000', '0.500', '50.0%'],
            ['$10,000', '0.333', '33.3%'],
            ['$1,000', '0.250', '25.0%'],
          ],
          note: 'Computed directly from Valve’s curve. This weight scales quality-win seed buckets; it is not a direct award of ranking points.',
        },
      },
      {
        number: '06',
        eyebrow: 'Stage two: results replay',
        title: 'A fixed-RD Glicko pass turns the seed into the final rating.',
        paragraphs: [
          'After seeding, Valve creates a Glicko object for every roster with rating deviation fixed at 75. Fixing RD removes the uncertainty dynamics that distinguish full Glicko and makes the update behave like an Elo-style system. The implementation documents a calibration in which a 400-point rating difference corresponds to a 90% expected win probability.',
          'Eligible matches are sorted from oldest to newest and replayed. For each match, the winner receives a positive adjustment and the loser a negative one based on the expected result at that moment. The update is multiplied by the match’s age-derived information content. Recent upsets move more rating than old expected wins; results are path-dependent because an opponent’s rating at the historical replay point determines the expectation.',
          'A useful consequence follows: the top-ten bucket comment that there is “never any harm” in playing a low-stakes match applies to seed buckets, where a weak result cannot displace a strong one. It does not mean losses are harmless to the complete VRS. Once a match is eligible, the head-to-head stage can reduce rating after a defeat. Seeding and rating adjustment must be kept conceptually separate.',
        ],
        table: {
          caption: 'The complete calculation pipeline',
          headers: ['Order', 'Operation', 'Output'],
          rows: [
            ['1', 'Filter to eligible completed matches in the 180-day window', 'Evidence set'],
            ['2', 'Resolve roster entities through three-player overlap', 'Ranked teams'],
            ['3', 'Compute aged prize, quality-opponent, network and LAN factors', 'Raw seed'],
            ['4', 'Min–max remap population seeds', 'Starting rating, 400–2000'],
            ['5', 'Replay matches chronologically with fixed RD 75', 'Final rank value'],
            ['6', 'Filter eligibility and sort globally and regionally', 'Published standings'],
          ],
        },
        callout: 'VRS is ensemble-like: a prestige prior followed by a chronological result model. Reading only one stage misdescribes the system.',
      },
      {
        number: '07',
        eyebrow: 'From rating to invitation',
        title: 'The monthly list becomes a queue with strict acceptance rules.',
        paragraphs: [
          'For a ranked tournament, the organizer declares which VRS list it will use, how many teams it intends to invite and the starting rank. It must invite sequentially from the most recent available standings at the invitation date. When a roster declines or cannot satisfy the acceptance conditions, the organizer proceeds down the list. The current rules require at least two VRS invitees from any chosen list.',
          'This mechanism turns publication timing into a real strategic boundary. The relevant list is not necessarily the newest list by tournament start; it is the most recent list when invitations are issued. A completed event excluded because it was still in progress at the cut-off can therefore miss an invitation cycle even if its result appears days later.',
          'Unranked competitions are constrained separately by compensation caps in Valve’s tournament requirements. Ranked access, sponsorship visibility and chances to create higher-value evidence consequently form a feedback loop. VRS is designed to make that loop merit-responsive, but no ranking with invitation power can be competitively neutral.',
        ],
        callout: 'A VRS snapshot is executable policy: once an organizer starts the invitation queue, ordinal position becomes access.',
      },
      {
        number: '08',
        eyebrow: 'Majors and regions',
        title: 'Regional performance creates slots; regional VRS fills them.',
        paragraphs: [
          'The current Major structure invites 32 teams across three stages: 16 into Stage 1, eight into Stage 2 and eight into Stage 3. Regional allocations are earned by the previous Major. Each region receives a Stage 2 place for each of its teams that reached the previous Stage 3, and a Stage 3 place for each team that reached the playoffs. The remaining places are filled at Stage 1.',
          'Those slots are then offered in regional VRS order, beginning with Stage 3, then Stage 2, then Stage 1. Global VRS is used for pre-event seeding, not for replacing the regional invitation mechanism. A roster’s region is determined from the majority of its players; the rules specify tie priorities when no single region has an outright majority.',
          'This separates two competitive questions. Regional allocation asks how a region performed at the last Major. VRS asks which currently eligible roster from that region should receive the resulting place. It also creates a lag: one generation can earn structural opportunity that a later monthly ranking distributes to a different roster from the same region.',
        ],
        stats: [
          { value: '32', label: 'Major teams', detail: '16 Stage 1, eight Stage 2, eight Stage 3' },
          { value: 'Regional', label: 'Invitation lists', detail: 'Major access is filled by region' },
          { value: 'Global', label: 'Event seeding list', detail: 'Used to seed the assembled field' },
        ],
      },
      {
        number: '09',
        eyebrow: 'Failure modes',
        title: 'Transparency makes the trade-offs inspectable, not disappear.',
        paragraphs: [
          'First, VRS depends on a connected competitive graph. Opponent bounty and network are only informative when regions and tiers play enough meaningful cross-comparison matches. Sparse regions can have noisier relative calibration even when their internal ordering is reasonable. Second, prize pools are observable but imperfect proxies: a strategically important qualifier may have little direct money, while a well-funded event can purchase additional model context.',
          'Third, monthly recomputation creates cliffs. Event-completion filters are sensible—partial brackets should not distribute premature evidence—but a final played on the wrong side of a cut-off can affect an entire invitation wave. Fourth, majority-core continuity is necessary and gameable at the margin: it treats three retained players as sufficient even when the caller, star and tactical identity all change.',
          'Fifth, min–max and fifth-best normalization make the rating population-relative. A roster’s seed can change because the reference field changes, not only because its own results change. That is not a bug in a comparative model, but it means the displayed point difference cannot be interpreted as a self-contained asset.',
          'The strongest defense of VRS is not perfection. It is auditability. The code, inputs, standings detail pages and rules are public enough for teams to reproduce much of the pipeline and contest concrete behavior. The strongest improvement would be equally concrete: publish versioned parameter documentation, snapshot cut-off rules and calibration reports alongside each monthly release so that governance changes are as legible as model changes.',
        ],
        table: {
          caption: 'How to read common VRS claims',
          headers: ['Claim', 'Better interpretation'],
          rows: [
            ['“They gained points for the trophy”', 'The recomputation incorporated prizes, opponents and match updates'],
            ['“Low-tier matches cannot hurt”', 'Weak wins may not enter top-ten seed buckets; eligible losses can still hurt H2H rating'],
            ['“The organization owns the rank”', 'The five-player roster owns it, with three-player continuity'],
            ['“Global rank decides every invite”', 'Organizers and Majors use specified global, regional or subdivision lists'],
            ['“The points only change when teams play”', 'Aging, window exits and population normalization also change them'],
          ],
          note: 'These interpretations follow the public code and tournament rules as of the stated data cut-off; Valve can revise both.',
        },
        callout: 'VRS succeeds when its errors are easier to find, argue about and correct than the opaque invitation market it replaced.',
      },
      {
        number: '10',
        eyebrow: 'Technical verdict',
        title: 'Judge VRS as infrastructure under constraints.',
        paragraphs: [
          'As a ranking model, VRS has a coherent architecture: a broad prior protects against isolated upset noise; chronological head-to-head updates restore direct competitive evidence; aging keeps the target current; roster cores attach results to players; regional views support a global esport. Each component addresses a real operational problem.',
          'As a governance system, the same components create incentives. Prize structures communicate stakes to the model. Tournament timing interacts with monthly snapshots. Core retention carries access. Invitations create the matches that create future rank. Those loops cannot be removed simply by choosing a different equation; they must be monitored as part of tournament policy.',
          'The right response is neither to worship the decimal nor discard it whenever it produces an uncomfortable team order. Reproduce the calculation, identify which layer caused the result, and ask whether that layer matches the competitive value Valve intended to measure. VRS is not merely the table at the end of that process. It is the process by which modern professional Counter-Strike decides who gets into the room.',
        ],
        callout: 'Final answer: VRS is technically more sophisticated than a points table and politically more consequential than a power ranking. It should be analysed as both.',
      },
    ],
    sources: [
      { label: 'Valve — Counter-Strike Regional Standings repository', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings', use: 'Model goals, public implementation, data format and evaluation context.' },
      { label: 'Valve — Ranking pipeline source', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/model/ranking.js', use: 'Seed coefficients, 400–2000 remap, fixed RD, chronological match updates and eligibility.' },
      { label: 'Valve — Team and seed-modifier source', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/model/team.js', use: 'Roster overlap, top-ten buckets, prize, opponent-network and LAN calculations.' },
      { label: 'Valve — Data-loader source', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/model/data_loader.js', use: '180-day filter, 30-day grace period, completed-event filter and linked qualifier prize pools.' },
      { label: 'Valve — Glicko implementation', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/model/glicko.js', use: 'Expected-result equation, information weighting and fixed-RD behavior.' },
      { label: 'Valve — Ranking-context source', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/model/ranking_context.js', use: 'Linear timestamp modifier and outlier-reference configuration.' },
      { label: 'Valve — Tournament Operation Requirements', url: 'https://github.com/ValveSoftware/counter-strike_rules_and_regs/blob/main/tournament-operation-requirements.md', use: 'VRS definitions, sequential invitation process, roster acceptance and ranked-event rules.' },
      { label: 'Valve — Major Supplemental Rulebook', url: 'https://github.com/ValveSoftware/counter-strike_rules_and_regs/blob/main/major-supplemental-rulebook.md', use: '32-team stage allocation, regional invitations, roster integrity and global seeding.' },
      { label: 'Valve — August 2026 global standings', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/live/2026/standings_global_2026_08_03.md', use: 'Latest published monthly snapshot available at the data cut-off.' },
      { label: 'Valve — VRS model details example', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/live/2026/standings_europe_2026_08_03.md', use: 'Published regional roster entries and detailed factor reporting.' },
    ],
  },
  {
    slug: 'predicting-every-remaining-s-tier-counter-strike-event-2026',
    number: '034',
    title: 'Forecasting the Rest of 2026: Who Wins Every S-Tier Event?',
    shortTitle: 'The rest-of-2026 forecast',
    dek: 'Nine tournaments, one transparent forecasting model, and no false certainty. VRS supplies the prior; recent LAN form, head-to-heads, player output, roster news, attendance and format decide how far to move it.',
    verdict: 'Spirit are the season favourite. They are not the field.',
    verdictDetail: 'The model selects Spirit at Porto, EPL, Thunderpick, PGL Bucharest, BLAST Rivals and the Singapore Major; FURIA at FISSURE, Vitality at StarSeries, and Falcons in Beijing. Those are modal outcomes, not certainties. The nine favourites carry only 2.56 expected correct picks in total, which is the honest scale of tournament forecasting before brackets, qualifiers and two future VRS cut-offs are known.',
    readingMinutes: 25,
    publishedAt: '2026-09-01',
    dataCutoff: '1 September 2026, 12:00 UTC',
    sample: 'Valve’s 3 August global VRS; completed S-tier LANs and direct elite matchups from March–August 2026; HLTV three-month team form and current player/team pages; confirmed or projected event fields and roster news available at the cut-off. Porto probabilities are conditional on the six-team playoff bracket.',
    heroStats: [
      { value: '9', label: 'S-tier events left', detail: 'From Porto playoffs through Singapore' },
      { value: '6', label: 'Spirit selections', detail: 'The model leader whenever Spirit attend' },
      { value: '2.56', label: 'Expected exact picks', detail: 'Sum of the nine favourite probabilities' },
      { value: '23%', label: 'Major favourite', detail: 'Spirit lead, but 77% belongs elsewhere' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'Scope before prediction',
        title: '“The rest of the season” means nine live 2026 S-tier titles.',
        paragraphs: [
          'This forecast covers every Liquipedia-classified S-tier Counter-Strike event that had not produced a champion by 1 September 2026. BLAST Open Porto is already in progress, so its estimate begins from the known six-team playoff bracket rather than pretending the group stage has not happened. The other eight run from FISSURE Playground 3 on 8 September to the PGL Major Singapore final on 13 December.',
          'StarLadder StarSeries Fall is included. Its $500,000 prize pool makes it easy to overlook, and the corresponding 2025 event was A-tier, but Liquipedia explicitly classifies the 2026 edition as S-tier. Cancelled PGL Fall, Forge of Legends and YaLLa events are excluded. Postponed FISSURE Playground 5 is excluded because there is no settled date or field from which to forecast.',
          'Event fields are not equally knowable. FISSURE, StarSeries and EPL have substantially confirmed lists. PGL Bucharest and Beijing still contain qualifier slots. Thunderpick currently displays seven VRS-projected teams plus a qualifier. BLAST Rivals depends on the 5 October VRS, while all 32 Singapore invitations depend on regional VRS lists dated 2 November. A prediction that treats those projected teams as confirmed is overstating its evidence before the first match is simulated.',
        ],
        table: {
          caption: 'Forecast universe at the 1 September cut-off',
          headers: ['Event', 'Dates', 'Teams', 'Field status', 'Model pick'],
          rows: [
            ['BLAST Open Porto', '26 Aug–6 Sep', '6 left', 'Playoff bracket known', 'Spirit'],
            ['FISSURE Playground 3', '8–13 Sep', '16', '15 named + Asia qualifier', 'FURIA'],
            ['StarSeries Fall', '17–20 Sep', '8', 'Confirmed', 'Vitality'],
            ['ESL Pro League S24', '3–11 Oct', '16', 'Confirmed', 'Spirit'],
            ['Thunderpick World Championship', '14–18 Oct', '8', '7 VRS projections + qualifier', 'Spirit'],
            ['PGL Masters Bucharest', '24–31 Oct', '16', '12 invites + 4 qualifiers', 'Spirit'],
            ['IEM Beijing', '2–8 Nov', '16', '13 invites + 3 qualifiers', 'Falcons'],
            ['BLAST Rivals S2', '9–15 Nov', '8', 'Projected from 5 Oct VRS', 'Spirit'],
            ['PGL Major Singapore', '24 Nov–13 Dec', '32', 'Projected from 2 Nov regional VRS', 'Spirit'],
          ],
          note: 'Dates refer to the complete event. HLTV displays the Singapore Stage 3 and playoff page as 3–13 December; Stages 1 and 2 begin on 24 November.',
        },
      },
      {
        number: '02',
        eyebrow: 'The forecasting model',
        title: 'VRS is the prior, not the prediction.',
        paragraphs: [
          'The model begins with Valve’s 3 August global standings because VRS already compresses six months of results, opponent quality, LAN evidence, stakes and roster continuity into a common scale. Spirit led on 2011 points, followed by Falcons on 1950, MOUZ on 1873, 9z on 1847, Vitality on 1836, NAVI on 1802, Legacy on 1773 and FURIA on 1771. That ordering is valuable evidence, but blindly converting it into nine champions would ignore what happened in August and who is actually attending each tournament.',
          'Each team receives a 0–100 base score: 35% VRS position, 20% three-month series form, 15% 2026 S-tier LAN conversion, 10% recent head-to-head results against the event’s principal contenders, 10% current player ceiling, and 10% map-pool breadth plus roster continuity. Missing form data is shrunk toward the field mean rather than silently treated as zero. Event adjustments then account for attendance, known bracket position, best-of-five finals, travel, stand-ins and whether a field is projected rather than confirmed.',
          'For event e and team i, the championship share is p(i,e) = exp((Sᵢ + Aᵢₑ)/τ) divided by the corresponding sum for every attendee. S is the weighted base score, A is the event adjustment and τ is a temperature chosen to prevent small score differences from becoming fake certainty. The displayed probabilities are rounded and sum to 100% within each event. This is an interpretable analytical model, not a trained betting model: there is no claim that a reported 26% bin has been calibrated over thousands of historical tournaments.',
        ],
        table: {
          caption: 'Model components and the question each answers',
          headers: ['Input', 'Weight', 'Measurement question', 'Failure mode controlled'],
          rows: [
            ['VRS', '35%', 'What has the connected six-month result graph learned?', 'Recency narrative and selective memory'],
            ['Recent form', '20%', 'How often has the current team won series in three months?', 'Aging form hidden inside the VRS window'],
            ['S-tier conversion', '15%', 'Has strength become deep runs and titles in 2026?', 'Farming lower-stakes volume'],
            ['Elite head-to-head', '10%', 'Are there repeatable matchup advantages?', 'Assuming transitive strength'],
            ['Player ceiling', '10%', 'Can the roster manufacture rounds against equal systems?', 'Treating every roster point as interchangeable'],
            ['Maps, roster and news', '10%', 'Will this five arrive intact with a viable veto?', 'Ignoring stand-ins, rebuilds and event-specific absence'],
          ],
          note: 'The weights were fixed before assigning event winners. They are judgement choices, so sensitivity is discussed rather than disguised.',
        },
        callout: 'A VRS rank answers “who has the strongest body of evidence?” A tournament forecast asks “who wins this field, in this format, with this roster, next?”',
      },
      {
        number: '03',
        eyebrow: 'The evidence entering September',
        title: 'Spirit own the strongest prior and the strongest current response.',
        paragraphs: [
          'Spirit’s position is unusually coherent across inputs. They were first in the August VRS on 2011, first in HLTV’s 31 August world ranking, and 87.0% on series over the preceding three months. Since losing the BLAST Bounty final to MOUZ, they won EWC and reached the Porto semi-final with nine consecutive series wins. At Porto they beat DENDELE, G2 and FURIA 2–0; the last two are forecast contenders rather than filler opposition.',
          'The player-level explanation is not subtle. donk posted a 1.43 rating at EWC and sh1ro supplied the second elite conversion point. Spirit’s recent map ledger also had real veto breadth: 7–0 on Ancient, 7–1 on Anubis, 9–3 on Mirage and 11–4 on Dust2 over the published three-month view. Perfect-looking map percentages have small denominators, but four credible maps make it difficult for a best-of-three opponent to route around the favourite.',
          'Falcons are the clearest alternative. They entered August second in VRS, sat second in HLTV’s latest ranking, and showed a 73.3% three-month series rate. More importantly, they won the Cologne Major by beating G2, NAVI, Vitality, Spirit and FURIA, with m0NESY earning the MVP at 1.25 and a three-star core around him. The downgrade is volatility: Legacy eliminated them 2–0 at EWC, MOUZ beat them 2–1 in Porto, and karrigan’s 0.74 rating across his current Falcons team period places an unusually large mechanical tax on the other four players.',
        ],
        table: {
          caption: 'Contender snapshot — evidence available at publication',
          headers: ['Team', 'Aug VRS', 'Three-month series rate', 'Most important recent evidence', 'Player / roster signal'],
          rows: [
            ['Spirit', '2011 (#1)', '87.0%', 'EWC champion; Porto semi-final, 6–0 maps', 'donk 1.43 at EWC; stable five'],
            ['Falcons', '1950 (#2)', '73.3%', 'Cologne Major champion; EWC QF', 'm0NESY 1.25 Major MVP; karrigan joined in April'],
            ['MOUZ', '1873 (#3)', 'Shrunk to mean', 'Bounty champion; Porto semi-final', 'Spinx 1.54 in Bounty final; rebuilt with PR and xelex'],
            ['Vitality', '1836 (#5)', '60.0%', 'Five early S-tier titles; three recent LAN QFs', 'ZywOo-led stable five outside named stand-ins'],
            ['FURIA', '1771 (#8)', '68.8%', 'Cologne runner-up; EWC fourth', 'KSCERATO 1.19 team-period rating; no transfer in a year'],
            ['FUT', '1663 (#14)', '65.0%', 'EWC runner-up; three 2026 series wins over MOUZ', 'xfl0ud 1.48 in EWC playoff win'],
            ['Legacy', '1773 (#7)', '52.6%', 'CAC champion; EWC third', 'try 1.26 at EWC; new five has high ceiling'],
            ['G2', '1688 (#11)', '65.0%', 'Major playoff team; Porto playoff', 'Recent rebuild; excellent Inferno/Mirage split'],
          ],
          note: 'Ratings use the named sample and are not directly interchangeable. MOUZ’s unavailable comparable team-page series percentage is mean-shrunk; its recent LAN results remain separate evidence.',
        },
      },
      {
        number: '04',
        eyebrow: 'Head-to-heads and non-transitivity',
        title: 'The best team can still draw the wrong opponent.',
        paragraphs: [
          'Counter-Strike strength is not transitive. Falcons reached Cologne’s final by beating Spirit and extended a four-series winning run over Vitality in the quarter-final. Yet Legacy beat Falcons in the CS Asia Championships final and again 2–0 at EWC. Spirit arrived at the same EWC quarter-final having lost six consecutive series to Vitality, then broke that sequence and won the event. These are not footnotes: in single-elimination playoffs, one stylistic edge can consume the entire probability mass of a favourite.',
          'MOUZ supply the other warning. Spirit had beaten them seven consecutive times before MOUZ won the Bounty final 3–1. MOUZ then lost twice to FUT at EWC and had already lost a third 2026 series to FUT at Cologne. A model driven only by MOUZ’s title and VRS would miss their recurring difficulty against FUT; a model driven only by that matchup would miss MOUZ beating Falcons in Porto. Head-to-head receives 10%, enough to move an event probability but not enough to erase the broader graph.',
          'The practical effect changes by field. FUT’s matchup value matters at PGL Bucharest and projected BLAST Rivals, but not at FISSURE after magic replaced them. Legacy’s two straight wins over Falcons reduce the latter’s chance at EPL, Thunderpick and Beijing. Vitality’s historical control over Spirit has been discounted after EWC rather than declared dead from one reversal. Matchups decay: the closer a series is to the event and the more similar the roster and map pool, the more it should matter.',
        ],
        table: {
          caption: 'Recent matchup signals that move the event priors',
          headers: ['Matchup', 'Observed run', 'Forecast implication'],
          rows: [
            ['Falcons over Vitality', 'Four consecutive series through Cologne', 'Falcons gain in shared fields; Vitality’s ceiling is not treated as matchup-neutral'],
            ['Legacy over Falcons', 'Two consecutive LAN series, CAC final and EWC QF', 'Legacy is a live bracket spoiler; Falcons lose clean dominance'],
            ['Vitality over Spirit', 'Six straight before Spirit won at EWC', 'Old edge retained at low weight, but reversal and current form dominate'],
            ['Spirit over MOUZ', 'Seven straight before MOUZ won Bounty 3–1', 'MOUZ has demonstrated a solution, not established permanent control'],
            ['FUT over MOUZ', 'Three 2026 series wins, including twice at EWC', 'FUT receives a material PGL/Rivals path adjustment'],
            ['Falcons over FURIA', '3–0 in Cologne Major final', 'Beijing’s two leading alternatives are not matchup-symmetric'],
          ],
        },
        callout: 'Head-to-head is evidence of interaction, not a magical veto over the rest of the sample.',
      },
      {
        number: '05',
        eyebrow: 'Prediction ledger',
        title: 'Nine picks, nine probability distributions.',
        paragraphs: [
          'The table is the forecast in its most falsifiable form. “Pick” means the single most likely champion, not a claim that the team is more likely to win than the whole field. Only Porto’s 41% estimate approaches even odds, because Spirit and MOUZ have already earned semi-final byes and twelve teams have been eliminated. Every pre-event favourite remains below one third.',
          'The runner-up column is intentionally visible. In six of nine events, the gap between first and second is ten percentage points or less. A forecast that publishes only names would make a 27–20 choice look as decisive as 70–20. It is not. The field share includes every remaining team not individually shown, including unknown qualifiers where applicable.',
          'Summing the nine winning probabilities gives 2.56 expected correct selections. That expectation does not require the event outcomes to be independent. Multiplying all nine modal probabilities would produce about 0.0011% under an independence assumption, but the assumption is false because form, rosters and map changes persist across events. The multiplication is useful only as a demonstration of how absurd a nine-for-nine expectation would be.',
        ],
        table: {
          caption: 'Rest-of-2026 championship forecast',
          headers: ['Event', 'Pick', 'Win probability', 'Second', 'Other named contenders / field'],
          rows: [
            ['BLAST Open Porto', 'Spirit', '41%', 'MOUZ 23%', 'Falcons 14%; Vitality 9%; FURIA 7%; G2 6%'],
            ['FISSURE Playground 3', 'FURIA', '27%', 'G2 20%', 'Legacy 14%; 9z 10%; FaZe 8%; BETBOOM 6%; MongolZ 5%; field 10%'],
            ['StarSeries Fall', 'Vitality', '26%', 'MOUZ 23%', 'FURIA 19%; NAVI 11%; Aurora 8%; magic 5%; MIBR 5%; NRG 3%'],
            ['ESL Pro League S24', 'Spirit', '26%', 'Falcons 20%', 'MOUZ 13%; Vitality 11%; FURIA 10%; G2 7%; field 13%'],
            ['Thunderpick Worlds', 'Spirit', '31%', 'Falcons 23%', 'MOUZ 15%; Vitality 12%; NAVI 7%; Legacy 5%; 9z 4%; qualifier 3%'],
            ['PGL Masters Bucharest', 'Spirit', '29%', 'MOUZ 16%', 'FURIA 13%; FUT 11%; G2 9%; Vitality 8%; Legacy 6%; field 8%'],
            ['IEM Beijing', 'Falcons', '27%', 'MOUZ 20%', 'FURIA 18%; G2 10%; NAVI 8%; Legacy 6%; 9z 4%; field 7%'],
            ['BLAST Rivals S2', 'Spirit', '26%', 'Falcons 20%', 'MOUZ 15%; Vitality 12%; FURIA 10%; FUT 7%; G2 6%; Legacy 4%'],
            ['PGL Major Singapore', 'Spirit', '23%', 'Falcons 19%', 'MOUZ 13%; Vitality 12%; FURIA 10%; FUT 7%; G2 6%; field 10%'],
          ],
          note: 'Probabilities are analytical estimates as of the cut-off, not market odds. Each row sums to 100%. Rivals and Major fields are projections and must be rerun after their VRS cut-offs.',
        },
      },
      {
        number: '06',
        eyebrow: 'September',
        title: 'Porto rewards the bracket; Suzhou and Barcelona reward attendance.',
        paragraphs: [
          'Porto is the highest-confidence selection because half the work is complete. Spirit’s 6–0 group-stage map record earned a semi-final against the Falcons–G2 winner. MOUZ own the other bye and wait for FURIA or Vitality. Spirit’s 41% reflects current form plus one fewer elimination match, while MOUZ’s 23% respects both the same structural advantage and their recent wins over Spirit and Falcons. Falcons remain dangerous but must beat G2, Spirit and then the other side of the bracket.',
          'FISSURE is the opposite problem: the top three teams in the August VRS—Spirit, Falcons and MOUZ—do not attend, and Vitality are absent as well. FURIA are the strongest confirmed combination of current world rank, stable roster and 2026 LAN depth. Their 68.8% three-month series record and Cologne final outweigh recent losses to Legacy, FUT and Spirit, but do not justify more than 27% in a 16-team double-elimination group followed by single elimination. G2’s 20% is the mechanical and map-pool alternative; Legacy’s 14% captures a CAC title and EWC bronze without mistaking a 52.6% broader rate for sustained dominance.',
          'StarSeries restores Vitality, MOUZ and FURIA but excludes Spirit and Falcons. Vitality’s normal five are listed, which removes the Porto stand-in penalty, and double elimination gives their deeper system time to recover from an early loss. Their five S-tier titles from January through May remain the strongest conversion history in this field. Recent form keeps the estimate at only 26%, narrowly ahead of MOUZ on 23% and FURIA on 19%. This is a pick for regression toward an elite stable roster, not a claim that Vitality’s summer quarter-final exits did not happen.',
        ],
        callout: 'September’s three favourites are driven by three different facts: Spirit’s bracket, FURIA’s depleted field, and Vitality’s return to their intended five.',
      },
      {
        number: '07',
        eyebrow: 'October I',
        title: 'EPL and Thunderpick put the two best priors in the same room.',
        paragraphs: [
          'EPL Season 24 is the cleanest broad-field test. All top twelve VRS invitees accepted, joined by four Challenger League qualifiers, and a Swiss phase sends eight teams into the Spodek playoffs. Spirit lead at 26% and Falcons at 20%; the six-point gap is mostly recent form and EWC rather than VRS, where only 61 points separated them. MOUZ, Vitality and FURIA collectively hold another 34%, so the model still assigns the top two less than an even chance combined.',
          'The long Swiss path reduces upset variance for elite teams because a single bad series does not eliminate them. The single-elimination arena phase restores it. Spirit’s map breadth and 87% recent rate fit both stages. Falcons’ star density fits a playoff bracket, but the 73.3% rate, EWC exit and Porto loss make them second. G2, Legacy and 9z remain high-impact draw variables even when they are not title favourites.',
          'Thunderpick has only eight teams and a best-of-five final, which raises the concentration at the top. Its displayed field is still a VRS prediction—Spirit, Falcons, MOUZ, 9z, Vitality, NAVI, Legacy and one qualifier—so 31% for Spirit includes field uncertainty. The BO5 rewards four-map strength and sustained star output, both Spirit advantages. Falcons rise to 23% because fewer rounds of qualification separate m0NESY, NiKo and kyousuke from the final; Legacy’s matchup history is the reason that advantage is not larger.',
        ],
      },
      {
        number: '08',
        eyebrow: 'October II',
        title: 'Bucharest is a Spirit pick and a Vitality warning.',
        paragraphs: [
          'Falcons declined PGL Masters Bucharest, removing Spirit’s closest global prior. Twelve teams are invited and four arrive through regional qualifiers; every group-stage series is best-of-three, followed by a single-elimination playoff and best-of-five final. That format produces Spirit’s second-largest pre-event share, 29%, and a 13-point gap over MOUZ.',
          'FUT rise to 11% because the field contains MOUZ and FURIA, teams they beat during the EWC run, and because a best-of-five final gives their young map pool more room than a compressed BO3. Their 65.0% recent series rate and Paris final are meaningful, but Porto losses to Legacy and Vitality show why one tournament cannot replace the VRS prior. FURIA’s stable five and G2’s upset ceiling keep both in the same contender tier.',
          'Vitality fall to 8% for an event-specific reason: jL is scheduled to replace apEX for Bucharest. Porto tested whether Vitality could replace mezii while preserving the caller; Bucharest removes the in-game leader. The model assigns a larger penalty because late-round authority, veto implementation and adaptation travel through apEX’s role even when ZywOo, ropz and flameZ preserve the mechanical ceiling. If the planned lineup changes, the probability should be rerun rather than defended after its premise disappears.',
        ],
        callout: 'The same team can be a 26% favourite at StarSeries and an 8% outsider in Bucharest. Event forecasting is supposed to move when the roster does.',
      },
      {
        number: '09',
        eyebrow: 'November before the Major',
        title: 'Beijing belongs to Falcons; Hong Kong is still a hypothetical field.',
        paragraphs: [
          'Spirit and Vitality both declined IEM Beijing. That leaves Falcons as the highest-VRS invite, with MOUZ, FURIA, NAVI, Legacy, G2 and a deep second tier behind them. Falcons take 27%; MOUZ and FURIA combine for 38%. The pick rests on the Cologne path and unmatched three-star ceiling, while the reduced probability reflects the EWC loss to Legacy, Porto loss to MOUZ and a final that can expose karrigan’s individual tax over five maps.',
          'FURIA’s 18% is higher than at most full-field events because Spirit and Vitality are absent and because their roster has had no transfer in the last year. MOUZ’s 20% reflects the Bounty title, Porto semi-final and direct win over Falcons. NAVI remain at 8% despite two 2026 titles because their three-month series rate had fallen to 50% and their recent elite results are less consistent than the three teams above them.',
          'BLAST Rivals begins one day after Beijing ends and uses the 5 October VRS for eight invitations. The currently displayed eight-team list is a prediction, not an announcement: Spirit, Falcons, MOUZ, FUT, Legacy, FURIA, G2 and Vitality. The model therefore reports a conditional distribution and marks confidence low. Spirit lead at 26%; if one of the projected elite teams declines after the European-to-Asian travel sequence, every share must be renormalized. Beijing results will also be new evidence even though they occur after the invite date.',
        ],
      },
      {
        number: '10',
        eyebrow: 'The Major',
        title: 'Spirit are the Singapore favourite at only 23%.',
        paragraphs: [
          'The Major is the most important prediction and the least complete one. Invitations will be drawn from regional VRS lists dated 2 November: 18 European, nine Americas and five Asian teams, distributed across three stages. The current projected Stage 3 includes Spirit, MOUZ, FUT, Falcons, G2, FaZe, Legacy and FURIA, while Vitality are projected into Stage 2. Those starting positions matter because every additional Swiss stage creates more elimination exposure.',
          'Spirit lead on 23%, Falcons follow on 19%, and no other team exceeds 13%. Spirit’s case is current: top VRS, top world rank, EWC title, map breadth and the game’s highest-output player. Falcons’ case is event-specific: they are the reigning Major champions and already proved they can beat Vitality, Spirit and FURIA in consecutive playoff series. Vitality’s 12% assumes the normal five and gives substantial weight to two Majors in 2025 plus five early-2026 S-tier titles, but discounts three consecutive summer LAN quarter-finals and the risk of beginning one stage earlier.',
          'The 10% field share is not decorative. Thirty-two teams, early Swiss best-of-ones, a month of results still to enter VRS, and possible roster changes create genuine paths for an unlisted champion. FUT’s 7% recognizes Paris and favourable MOUZ history. FURIA’s 10% respects a Cologne final and stable roster. MOUZ’s 13% sits above both because its title, VRS and Porto result are broader than one matchup. The correct headline is therefore not “Spirit will win Singapore.” It is “Spirit are the least unlikely winner in a field that owns 77%.”',
        ],
        stats: [
          { value: '23%', label: 'Spirit', detail: 'Highest single-team Major share' },
          { value: '19%', label: 'Falcons', detail: 'Reigning Major champions' },
          { value: '35%', label: 'MOUZ + Vitality + FURIA', detail: 'Three independent second-line routes' },
        ],
        callout: 'A favourite below one quarter is a statement about uncertainty, not weakness.',
      },
      {
        number: '11',
        eyebrow: 'Sensitivity and falsification',
        title: 'The forecast is designed to expire in public.',
        paragraphs: [
          'The main sensitivity is the weight on recency. If VRS rises from 35% to 50% and recent form falls correspondingly, 9z, MOUZ and Vitality gain while FURIA and FUT lose; Spirit remain first in every event they attend. If recent form rises to 35%, Spirit’s lead grows, Vitality lose StarSeries to the FURIA–MOUZ cluster, and Legacy remain a spoiler rather than a favourite. The headline concentration on Spirit is therefore robust; the September non-Spirit selections are not.',
          'The second sensitivity is roster state. A normal Vitality five at Bucharest would move them from 8% into roughly the 12–14% band. A further MOUZ academy integration problem would transfer probability to FURIA and FUT. Any change to Spirit’s five or coaching access would matter more than a normal one-place ranking movement because their prediction relies on both donk’s ceiling and a stable, rehearsed structure.',
          'This paper should be updated at five checkpoints: after Porto, after the two September events, after EPL, after the 5 October Rivals list, and immediately after the 2 November Major lists. Each update should preserve the old table, record the changed inputs and score the forecast with a Brier measure rather than merely counting winners. A wrong 27% pick is not the same error as a wrong 70% pick; probabilistic claims should be judged probabilistically.',
        ],
        table: {
          caption: 'What would make each modal call wrong for a structural reason?',
          headers: ['Pick group', 'Primary failure signal', 'Where it would appear first'],
          rows: [
            ['Spirit: six events', 'donk/sh1ro suppression plus a veto narrowed below four maps', 'Porto semi-final, then EPL Swiss'],
            ['FURIA: FISSURE', 'Travel fatigue and recurring losses to the field’s aggressive mid-round teams', 'Suzhou group stage'],
            ['Vitality: StarSeries', 'Summer decline persists with the normal five', 'Opening two BO3s in Barcelona'],
            ['Falcons: Beijing', 'Star trio cannot cover repeated low-output calling slot over long series', 'Group lower bracket or BO5 final'],
            ['Rivals / Major fields', 'VRS invitations differ materially from current projections', '5 October and 2 November lists'],
          ],
        },
        callout: 'Final answer: pick Spirit most often, trust no pick absolutely, and rerun the paper whenever the field changes.',
      },
    ],
    sources: [
      { label: 'Liquipedia — 2026 S-tier tournament calendar', url: 'https://liquipedia.net/counterstrike/S-Tier_Tournaments', use: 'Event scope, dates, field sizes, prize pools and cancelled/postponed status.' },
      { label: 'Liquipedia — StarSeries Fall 2026', url: 'https://liquipedia.net/counterstrike/StarLadder/StarSeries/2026/Fall', use: 'Explicit 2026 S-tier classification, participants and double-elimination BO3 format.' },
      { label: 'Valve — August 2026 global standings', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings/blob/main/live/2026/standings_global_2026_08_03.md', use: 'Official VRS points and roster identities used as the model prior.' },
      { label: 'Valve — VRS public implementation', url: 'https://github.com/ValveSoftware/counter-strike_regional_standings', use: 'Interpretation of VRS as a recency-weighted connected result model rather than a points circuit.' },
      { label: 'HLTV — BLAST Open Porto 2026', url: 'https://www.hltv.org/events/8249/blast-open-porto-2026', use: 'Known playoff bracket, group results, attendance and BO5 final.' },
      { label: 'HLTV — FISSURE Playground 3', url: 'https://www.hltv.org/events/8266/fissure-playground-3', use: 'Current field, replacement team, format and VRS date.' },
      { label: 'HLTV — StarSeries Fall 2026', url: 'https://www.hltv.org/events/8057/starladder-starseries-fall-2026', use: 'Confirmed eight-team field and all-BO3 double-elimination format.' },
      { label: 'HLTV — EPL S24 invitations', url: 'https://www.hltv.org/news/45270/esl-pro-league-s24-invites-announced', use: 'Complete 16-team field and Swiss-to-playoff structure.' },
      { label: 'HLTV — Thunderpick World Championship 2026', url: 'https://www.hltv.org/events/8932/thunderpick-world-championship-2026', use: 'VRS-projected field, qualifier slot and BO5 final.' },
      { label: 'HLTV — PGL Masters Bucharest 2026', url: 'https://www.hltv.org/events/8050/pgl-masters-bucharest-2026', use: 'Twelve invited teams, four qualifier slots and all-BO3 Swiss stage.' },
      { label: 'HLTV — IEM Beijing invitations', url: 'https://www.hltv.org/news/45289/iem-beijing-invites-announced', use: 'Confirmed invitees, three qualifier slots, and Spirit and Vitality declining.' },
      { label: 'HLTV — BLAST Rivals 2026 Season 2', url: 'https://www.hltv.org/events/8251/blast-rivals-2026-season-2', use: 'Projected eight-team field, 5 October VRS date and format.' },
      { label: 'HLTV — PGL Major Singapore 2026', url: 'https://www.hltv.org/events/8302/pgl-major-singapore-2026', use: 'Projected Stage 3 field, complete event structure and 2 November VRS date.' },
      { label: 'HLTV — Singapore regional distribution', url: 'https://www.hltv.org/news/44921/regional-distribution-set-for-pgl-singapore-major', use: '18 Europe, nine Americas and five Asia invitations across three stages.' },
      { label: 'HLTV — Spirit team overview', url: 'https://www.hltv.org/team/7020/spirit', use: '87.0% three-month series rate, recent match ledger and map records.' },
      { label: 'HLTV — Falcons team overview', url: 'https://www.hltv.org/team/11283/falcons', use: '73.3% recent series rate, current roster, player team-period ratings and event ledger.' },
      { label: 'HLTV — Vitality team overview', url: 'https://www.hltv.org/team/9565/vitality', use: '60.0% recent series rate, intended five-player roster and 2026 event history.' },
      { label: 'HLTV — FURIA team overview', url: 'https://www.hltv.org/team/8297/furia', use: '68.8% recent series rate, stable roster, player ratings and LAN results.' },
      { label: 'HLTV — Legacy team overview', url: 'https://www.hltv.org/team/12468/legacy', use: '52.6% recent series rate, player ratings, roster recency and event ledger.' },
      { label: 'HLTV — FUT team overview', url: 'https://www.hltv.org/team/13286/fut', use: '65.0% recent series rate and the complete recent MOUZ matchup ledger.' },
      { label: 'HLTV — G2 team overview', url: 'https://www.hltv.org/team/5995/g2', use: '65.0% recent series rate, rebuilt roster, recent results and map profile.' },
      { label: 'HLTV — donk wins the EWC MVP', url: 'https://www.hltv.org/news/45376/donk-earns-esports-world-cup-mvp', use: '1.43 tournament rating and Spirit’s title-path player ceiling.' },
      { label: 'HLTV — m0NESY wins Cologne Major MVP', url: 'https://www.hltv.org/news/44973/m0nesy-clinches-iem-cologne-major-2026-mvp', use: '1.25 event rating and Falcons’ elite-opposition Major path.' },
      { label: 'HLTV — MOUZ beat Spirit for the Bounty title', url: 'https://www.hltv.org/news/45226/mouz-subdue-spirit-to-win-blast-bounty-s2', use: '3–1 final, prior seven-series Spirit streak and Spinx’s 1.54 final.' },
      { label: 'HLTV — Spirit break the Vitality streak', url: 'https://www.hltv.org/news/45360/spirit-snap-six-match-losing-streak-vs-vitality-to-reach-ewc-semis', use: 'Six-series prior head-to-head and its EWC reversal.' },
      { label: 'HLTV — Falcons beat Vitality at Cologne', url: 'https://www.hltv.org/news/44962/falcons-see-off-vitality-in-cologne-to-set-up-spirit-clash', use: 'Four-series Falcons streak and quarter-final player output.' },
      { label: 'HLTV — Legacy eliminate Falcons at EWC', url: 'https://www.hltv.org/news/45357/legacy-eliminate-falcons-from-ewc', use: 'Second consecutive Legacy win over Falcons and individual ratings.' },
      { label: 'HLTV — FUT sweep MOUZ at EWC', url: 'https://www.hltv.org/news/45355/fut-sweep-mouz-to-make-ewc-semis', use: 'Repeated matchup advantage and xfl0ud’s 1.48 playoff rating.' },
      { label: 'HLTV — jL to stand in for Vitality', url: 'https://www.hltv.org/news/45238/media-jl-to-stand-in-for-vitality', use: 'Different planned stand-in configurations at Porto and PGL Bucharest.' },
    ],
  },
];
