import type { CounterStrikeEditorial } from './counter-strike-editorials.data';

export const COUNTER_STRIKE_STATISTICAL_EDITORIALS: readonly CounterStrikeEditorial[] = [
  {
    slug: 'the-weekend-ropz-anomaly',
    number: '035',
    title: 'The Weekend ropz Anomaly',
    shortTitle: 'The weekend ropz anomaly',
    dek: 'Across every 2026 map in the sample, ropz gains 0.185 rating points on Saturdays and Sundays. The strange part is not the split. It is how many attempts to make it disappear fail.',
    verdict: 'The weirdest reproducible player storyline of 2026 is that ropz becomes a weekend outlier.',
    verdictDetail: 'His equal-map average rises from 1.084 on weekdays to 1.269 on weekends across 121 maps. The association survives event, map, season-half and leave-one-event-out checks. It is not proof that the day causes the performance: Vitality play and win different matches on weekends, and the strictest opponent-adjusted model materially shrinks the effect.',
    readingMinutes: 15,
    publishedAt: '2026-09-01',
    dataCutoff: '1 September 2026, before that day’s matches',
    sample: 'A screening universe of 577 matches, 1,285 maps and 12,850 player-map rows across 22 top-level 2026 event stages. Context splits were evaluated for 96 players with at least 50 maps. The selected ropz analysis uses all 121 of his 2026 Vitality maps in the dataset: 50 series at 12 events from 14 January through 31 August.',
    heroStats: [
      { value: '+0.185', label: 'Weekend rating lift', detail: '1.269 across 53 maps vs 1.084 across 68' },
      { value: '9 / 10', label: 'Positive event splits', detail: 'Among events containing both weekday and weekend maps' },
      { value: '+0.152', label: 'Event + map adjusted', detail: 'Lift after iterative fixed-effect demeaning' },
      { value: '121', label: 'Maps analysed', detail: 'Every ropz map in the 2026 premier-event dataset' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'The search, before the story',
        title: 'A weird result is easy to find. A weird result that survives inspection is not.',
        paragraphs: [
          'The search began with the full 2026 top-level event ledger available at the cut-off: 577 series from BLAST Bounty Season 1 through BLAST Open Porto, producing 1,285 played maps and 12,850 player-map rating rows. Qualifiers and the lower-tier calendar were excluded so that a contextual split would not merely separate elite LANs from online opposition. Players needed at least 50 maps, leaving 96 candidates.',
          'Five families of context were screened: each weekday against the other six, weekend against weekday, map one against later maps, true best-of-three or best-of-five deciders against other later maps, and the opening date of an event against its remaining dates. Air quality was excluded in advance. Each map received equal weight; this is an average of published map ratings, not a round-weighted reconstruction of HLTV’s aggregate player rating.',
          'That process creates a multiple-comparisons problem. If hundreds of splits are inspected, one of them will look remarkable by chance. The winning storyline therefore needed more than a small nominal p-value: at least 50 total maps, reasonable observations on each side, a large effect, and the same direction across events, maps and time. ropz’s weekend split was the strongest standardised weekend effect in the eligible field and the most stable high-profile result after those checks.',
        ],
        stats: [
          { value: '577', label: 'Series screened', detail: 'Top-level 2026 event stages only' },
          { value: '1,285', label: 'Maps', detail: '12,850 player-map observations' },
          { value: '96', label: 'Eligible players', detail: 'Minimum 50 maps before a split was tested' },
        ],
        callout: 'This is exploratory analysis with a declared search universe—not a pre-registered discovery. The robustness tests decide whether it is worth following, not whether causation has been proved.',
      },
      {
        number: '02',
        eyebrow: 'The anomaly',
        title: 'The calendar turns over and ropz adds 0.185 rating points.',
        paragraphs: [
          'Across 68 weekday maps, ropz averaged 1.084. Across 53 Saturday and Sunday maps, he averaged 1.269. The raw difference is +0.185 rating points. A conventional unequal-variance interval for the map-level difference is +0.067 to +0.303. Resampling complete series rather than individual maps 20,000 times produced a 95% percentile interval of +0.118 to +0.322.',
          'The day-by-day shape is stranger than a generic playoff bump. Saturday averaged 1.258 over 25 maps and Sunday 1.278 over 28. The two weekend days agree with each other. Friday, despite often being adjacent to playoff Counter-Strike, averaged only 1.014 over 23 maps; Tuesday was 0.995 over eight. There is no smooth trend toward the end of the week. The observed line looks like a step.',
          'The bootstrap’s two-sided tail frequency is 0.002, but it must not be read as a confirmatory p-value. ropz was selected after screening many players and contexts, so the search itself consumed significance. The more useful evidence is replication inside the existing sample: two weekend days, two season halves, multiple maps and multiple tournaments all point in the same direction.',
        ],
        bars: [
          { label: 'Sunday', value: 100, display: '1.278', detail: '28 maps' },
          { label: 'Monday', value: 88, display: '1.130', detail: '12 maps' },
          { label: 'Tuesday', value: 78, display: '0.995', detail: '8 maps' },
          { label: 'Wednesday', value: 92, display: '1.171', detail: '13 maps' },
          { label: 'Thursday', value: 89, display: '1.134', detail: '12 maps' },
          { label: 'Friday', value: 79, display: '1.014', detail: '23 maps' },
          { label: 'Saturday', value: 98, display: '1.258', detail: '25 maps' },
        ],
        callout: 'Saturday: 1.258. Sunday: 1.278. Weekdays combined: 1.084. The anomaly is not one exceptional final masquerading as a weekend.',
      },
      {
        number: '03',
        eyebrow: 'Replication inside the sample',
        title: 'Change the map, remove an event, split the season: the sign remains positive.',
        paragraphs: [
          'Six maps had at least five ropz observations on both sides of the weekend boundary. Every one produced a positive weekend difference. Mirage was the smallest at +0.060. Overpass was the largest at +0.240. Anubis, Dust2, Inferno and Nuke all sat between +0.205 and +0.229. Ancient was also positive, but had only one map on each side and is shown as insufficient rather than supporting evidence.',
          'Ten events contained at least one weekday and one weekend map. Nine produced a positive weekend split. The exception was the five-map BLAST Bounty Season 1 Finals sample, where the weekend side contained three maps. More importantly, deleting any entire event from the full analysis never erased the result: the leave-one-event-out estimate ranged from +0.161 to +0.208.',
          'A temporal split also fails to explain it. Before May, the lift was +0.135 across 68 maps; from May onward it was +0.252 across 53. That does not imply the anomaly is growing—the later estimate is noisier—but it rules out the simple story that one hot January or one August tournament manufactured the aggregate.',
        ],
        table: {
          caption: 'Weekend minus weekday rating by map',
          headers: ['Map', 'Weekend maps', 'Weekday maps', 'Rating difference', 'Reading'],
          rows: [
            ['Anubis', '5', '8', '+0.207', 'Positive'],
            ['Dust2', '12', '18', '+0.229', 'Positive'],
            ['Inferno', '8', '10', '+0.222', 'Positive'],
            ['Mirage', '10', '11', '+0.060', 'Positive, weakest'],
            ['Nuke', '9', '10', '+0.205', 'Positive'],
            ['Overpass', '8', '8', '+0.240', 'Positive, strongest'],
            ['Ancient', '1', '1', '+0.160', 'Insufficient sample'],
            ['Cache', '—', '6', '—', 'No weekend comparison'],
          ],
          note: 'Map ratings are equally weighted. A positive sign on six adequately sampled maps is a consistency check, not six independent experiments: the same player, team and events generate them.',
        },
      },
      {
        number: '04',
        eyebrow: 'The obvious confound',
        title: 'Weekends are when Vitality win trophies. ropz still moves more than the team.',
        paragraphs: [
          'Vitality played 21 weekend series and won 20 of them, a 95.2% rate. On weekdays they went 20–9, or 69.0%. That is an enormous selection difference. Weekends disproportionately contain playoff matches reached by a team already playing well, and a player rating is mechanically related to whether the team wins. Any claim that ropz simply likes Saturdays would be unserious without confronting this first.',
          'The within-win split is the most revealing check. Restricting the sample to series Vitality won leaves ropz at 1.289 on weekend maps and 1.107 on weekday maps, still a +0.183 difference. The corresponding weekend lifts for the regular teammates were +0.029 for flameZ, −0.009 for mezii and −0.067 for apEX in wins; ZywOo’s winning-map weekend comparison was −0.099. Winning more often is therefore not sufficient to reproduce ropz’s shape.',
          'Across every map, ropz moved +0.119 relative to the mean rating of his four teammates between weekdays and weekends. That is suggestive, not decisive: a series-block bootstrap interval ran from −0.044 to +0.272. The team-relative result can still be zero. The defensible statement is that ropz has the largest weekend lift on Vitality, not that statistics have proved a personal weekend mechanism.',
        ],
        table: {
          caption: 'Weekend rating lift inside Vitality’s regular five',
          headers: ['Player', 'Weekend mean', 'Weekday mean', 'Difference', 'Maps'],
          rows: [
            ['ropz', '1.269', '1.084', '+0.185', '53 / 68'],
            ['flameZ', '1.283', '1.192', '+0.091', '53 / 68'],
            ['ZywOo', '1.476', '1.412', '+0.064', '53 / 68'],
            ['mezii', '1.103', '1.055', '+0.047', '48 / 64'],
            ['apEX', '1.038', '1.004', '+0.035', '53 / 68'],
          ],
          note: 'mezii has fewer maps because Vitality used a substitute at Porto. Means are equal-map averages and should not be compared with round-weighted event aggregates.',
        },
        callout: 'The team wins more on weekends. But among the same winning team, ropz is the player whose rating changes most.',
      },
      {
        number: '05',
        eyebrow: 'Adjustment ladder',
        title: 'The effect survives simple controls and weakens under the strictest model.',
        paragraphs: [
          'Fixed-effect adjustment asks a narrower question: after removing the average difficulty of each event or map, is the weekend residual still higher? Event adjustment leaves +0.149. Map adjustment leaves +0.188. Iteratively removing both leaves +0.152. Opponent adjustment alone leaves +0.109. These estimates remain large enough to describe a real pattern in the observed sample.',
          'Removing event, map and opponent effects together reduces the estimate to +0.030. That model is close to saturation: 121 maps are being divided among 12 events, eight maps and many opponents, with several combinations appearing on only one side of the weekend boundary. It may control away the playoff pathway that defines the phenomenon, or it may reveal that opponent scheduling explains most of it. The data cannot distinguish those interpretations cleanly.',
          'The right response is to publish the entire adjustment ladder. Reporting only +0.185 would ignore schedule composition. Reporting only +0.030 would pretend a sparse, highly collinear model created a randomised comparison. The stable empirical statement is that the raw pattern is broad. The causal statement—weekend itself makes ropz better—remains unsupported.',
        ],
        table: {
          caption: 'Estimated weekend lift under alternative adjustments',
          headers: ['Model', 'Estimated lift', 'What it removes', 'Limit'],
          rows: [
            ['Raw equal-map split', '+0.185', 'Nothing', 'Schedule and win selection'],
            ['Event fixed effects', '+0.149', 'Average tournament level', 'Stage remains confounded'],
            ['Map fixed effects', '+0.188', 'Average map preference', 'Opponent mix remains'],
            ['Opponent fixed effects', '+0.109', 'Average opponent difficulty', 'Sparse repeated matchups'],
            ['Event + map', '+0.152', 'Tournament and veto composition', 'Opponent mix remains'],
            ['Event + map + opponent', '+0.030', 'All three observed factors', 'Near-saturated and highly collinear'],
          ],
          note: 'Fixed effects were removed by iterative demeaning. No model controls unobserved stage pressure, match time, illness, practice, travel, role changes or opponent preparation.',
        },
      },
      {
        number: '06',
        eyebrow: 'What the pattern could mean',
        title: 'The plausible mechanism is competitive context, not the Gregorian calendar.',
        paragraphs: [
          'Top-level Counter-Strike schedules are structured. Weekdays contain opening groups, adaptation matches and the occasional early elimination. Weekends contain arenas, playoffs and finals. ropz’s role as a late-round rifler and closer may become more valuable when opponents are stronger, preparation is deeper and a higher share of rounds reach fragile mid-round states. Rating 3.0 explicitly includes economy adjustment and Round Swing, so decisive kills in uncertain rounds can move the number more than low-leverage cleanup.',
          'That explanation is plausible, but it is still a hypothesis. The dataset does not contain player sleep, match start time, crowd size, stage status in a common field, travel history or role-level event logs. “Big-game ropz” could also be reverse selection: Vitality reach the weekend precisely when ropz has already found form, and his form helps create both the playoff berth and the later rating. Weekend is then a label attached to a successful tournament state, not the cause of it.',
          'The weirdness is useful because it generates a better analytical question. Instead of asking whether players possess an abstract clutch gene, ask whether ropz’s round-swing, trading, survival and site-anchor value change between group and playoff environments after controlling the opponent and map. A calendar anomaly becomes a concrete request for round-level stage data.',
        ],
        callout: 'Do not conclude that Saturday causes performance. Conclude that “weekend” is currently the best visible label for a repeatable ropz state the available variables do not fully explain.',
      },
      {
        number: '07',
        eyebrow: 'The out-of-sample test',
        title: 'Freeze the finding now and make the rest of 2026 try to kill it.',
        paragraphs: [
          'The clean next step is prospective. Keep the 1 September cut-off untouched. For every remaining top-level 2026 Vitality map, record the date, event, stage, opponent, map, series result and ropz Rating 3.0. Do not redefine “weekend,” drop bad events or add a new context after seeing the outcomes.',
          'The anomaly passes a practical replication test if the new weekend-minus-weekday estimate remains at least +0.100, appears on both Saturday and Sunday, and stays positive after event and map adjustment. It fails if the sign reverses, if the interval includes effects of meaningful size in both directions, or if the result becomes entirely explainable by one opponent or one event. The teammate-relative difference should be reported again regardless of outcome.',
          'This is where an odd statistic becomes science-like rather than decorative. The 2026-to-date sample discovers the pattern; the remaining calendar tests it. If it survives, “weekend ropz” becomes evidence of a stage-linked player state worth round-level study. If it disappears, the honest conclusion is that an unusually consistent historical coincidence was still a coincidence.',
        ],
        stats: [
          { value: '+0.100', label: 'Replication threshold', detail: 'Prospective weekend-minus-weekday lift' },
          { value: '2', label: 'Days must agree', detail: 'Saturday and Sunday remain separately positive' },
          { value: '0', label: 'Post-hoc exclusions', detail: 'Every future eligible map stays in the test' },
        ],
        callout: 'Final answer: ropz is the 2026 weekend outlier. The pattern is real in this sample, its cause is unknown, and the test that could disprove it is now public.',
      },
    ],
    sources: [
      { label: 'HLTV — ropz 2026 match history', url: 'https://www.hltv.org/stats/players/matches/11816/ropz?startDate=2026-01-01&endDate=2026-09-01', use: 'Public map-by-map date, opponent, score and Rating 3.0 ledger used to audit the selected player split.' },
      { label: 'HLTV — ropz career history', url: 'https://www.hltv.org/stats/players/career/11816/ropz', use: 'Independent 2026 map-count cross-check for the 121-map player sample.' },
      { label: 'HLTV — ropz player profile', url: 'https://www.hltv.org/player/11816/ropz', use: 'Current team, recent match path and roster context.' },
      { label: 'CS API — interactive endpoint documentation', url: 'https://api.csapi.de/docs', use: 'Machine-readable match, map and per-map player-stat endpoints used for the full-calendar screen.' },
      { label: 'OldFella / hltv_api — source and data notes', url: 'https://github.com/OldFella/hltv_api', use: 'Open-source endpoint implementation, HLTV provenance, response schema and daily-refresh statement.' },
      { label: 'HLTV — Introducing Rating 3.0', url: 'https://www.hltv.org/news/42485/introducing-rating-30', use: 'Meaning of the rating, economy adjustment, Round Swing and why map ratings are not simple kill–death summaries.' },
      { label: 'HLTV — Rating 3.0 adjustments', url: 'https://www.hltv.org/news/43047/rating-30-adjustments-go-live', use: 'Current formula context and warning that single-map ratings can be affected by high-leverage round peaks.' },
      { label: 'Liquipedia — 2026 S-tier tournament calendar', url: 'https://liquipedia.net/counterstrike/S-Tier_Tournaments', use: 'Cross-check of the top-level 2026 event universe and calendar dates.' },
    ],
  },
];
