import type { CounterStrikeEditorial, EditorialMapLayout, EditorialMapZone } from './counter-strike-editorials.data';

const MIRAGE_ZONES: readonly EditorialMapZone[] = [
  { label: 'A site', x: 8, y: 9, width: 25, height: 28 },
  { label: 'Mid', x: 36, y: 18, width: 28, height: 62 },
  { label: 'B site', x: 69, y: 9, width: 23, height: 28 },
  { label: 'Connector', x: 31, y: 38, width: 20, height: 22 },
  { label: 'Short', x: 57, y: 38, width: 18, height: 22 },
];

const MIRAGE_LAYOUTS: readonly EditorialMapLayout[] = [
  {
    caption: 'Super Falcons — maximum pressure',
    map: 'Mirage',
    side: 'CT',
    zones: MIRAGE_ZONES,
    markers: [
      { player: 'b1t', role: 'A anchor', x: 20, y: 25, tone: 'anchor' },
      { player: 'donk', role: 'primary pressure', x: 43, y: 48, tone: 'entry' },
      { player: 'm0NESY', role: 'mobile AWP', x: 52, y: 25, tone: 'awp' },
      { player: 'kyousuke', role: 'second contact', x: 66, y: 48, tone: 'rifle' },
      { player: 'NiKo', role: 'B / command', x: 81, y: 25, tone: 'igl' },
    ],
    routes: [
      { x1: 20, y1: 25, x2: 43, y2: 48, tone: 'support' },
      { x1: 43, y1: 48, x2: 52, y2: 25, tone: 'primary' },
      { x1: 52, y1: 25, x2: 66, y2: 48, tone: 'secondary' },
      { x1: 66, y1: 48, x2: 81, y2: 25, tone: 'support' },
    ],
    note: 'Two central rifle contacts maximise the first and second fight; b1t and NiKo absorb the isolated sites.',
  },
  {
    caption: 'NAVI 2021 — superstar gravity',
    map: 'Mirage',
    side: 'CT',
    zones: MIRAGE_ZONES,
    markers: [
      { player: 'b1t', role: 'A rifle', x: 20, y: 25, tone: 'rifle' },
      { player: 'electronic', role: 'star pressure', x: 43, y: 48, tone: 'entry' },
      { player: 's1mple', role: 'free AWP', x: 52, y: 25, tone: 'awp' },
      { player: 'Boombl4', role: 'info / rotate', x: 66, y: 48, tone: 'igl' },
      { player: 'Perfecto', role: 'hard anchor', x: 81, y: 25, tone: 'anchor' },
    ],
    routes: [
      { x1: 20, y1: 25, x2: 43, y2: 48, tone: 'support' },
      { x1: 43, y1: 48, x2: 52, y2: 25, tone: 'primary' },
      { x1: 52, y1: 25, x2: 66, y2: 48, tone: 'primary' },
      { x1: 52, y1: 25, x2: 81, y2: 25, tone: 'support' },
    ],
    note: 'The entire structure feeds information and survival time into s1mple while electronic supplies rifle force.',
  },
  {
    caption: 'Astralis 2018 — protocol coverage',
    map: 'Mirage',
    side: 'CT',
    zones: MIRAGE_ZONES,
    markers: [
      { player: 'Magisk', role: 'A anchor', x: 20, y: 25, tone: 'anchor' },
      { player: 'dupreeh', role: 'first contact', x: 43, y: 48, tone: 'entry' },
      { player: 'device', role: 'system AWP', x: 52, y: 25, tone: 'awp' },
      { player: 'gla1ve', role: 'info / command', x: 66, y: 48, tone: 'igl' },
      { player: 'Xyp9x', role: 'B anchor', x: 81, y: 25, tone: 'anchor' },
    ],
    routes: [
      { x1: 20, y1: 25, x2: 43, y2: 48, tone: 'support' },
      { x1: 43, y1: 48, x2: 52, y2: 25, tone: 'primary' },
      { x1: 52, y1: 25, x2: 66, y2: 48, tone: 'support' },
      { x1: 66, y1: 48, x2: 81, y2: 25, tone: 'support' },
    ],
    note: 'Every lane has a fallback relationship; the map remains coherent after the opening position changes.',
  },
  {
    caption: 'FaZe 2022 — distributed autonomy',
    map: 'Mirage',
    side: 'CT',
    zones: MIRAGE_ZONES,
    markers: [
      { player: 'karrigan', role: 'A / command', x: 20, y: 25, tone: 'igl' },
      { player: 'rain', role: 'space and contact', x: 43, y: 48, tone: 'entry' },
      { player: 'broky', role: 'reactive AWP', x: 52, y: 25, tone: 'awp' },
      { player: 'Twistzz', role: 'flex rifle', x: 66, y: 48, tone: 'rifle' },
      { player: 'ropz', role: 'anchor / closer', x: 81, y: 25, tone: 'anchor' },
    ],
    routes: [
      { x1: 20, y1: 25, x2: 43, y2: 48, tone: 'primary' },
      { x1: 43, y1: 48, x2: 52, y2: 25, tone: 'primary' },
      { x1: 52, y1: 25, x2: 66, y2: 48, tone: 'secondary' },
      { x1: 66, y1: 48, x2: 81, y2: 25, tone: 'secondary' },
    ],
    note: 'karrigan spends his own life to create a late round for broky, Twistzz and ropz.',
  },
  {
    caption: 'Vitality 2025 — separated stars',
    map: 'Mirage',
    side: 'CT',
    zones: MIRAGE_ZONES,
    markers: [
      { player: 'ropz', role: 'A anchor', x: 20, y: 25, tone: 'anchor' },
      { player: 'flameZ', role: 'primary pressure', x: 43, y: 48, tone: 'entry' },
      { player: 'ZywOo', role: 'universal AWP', x: 52, y: 25, tone: 'awp' },
      { player: 'apEX', role: 'info / command', x: 66, y: 48, tone: 'igl' },
      { player: 'mezii', role: 'B connector', x: 81, y: 25, tone: 'rifle' },
    ],
    routes: [
      { x1: 20, y1: 25, x2: 52, y2: 25, tone: 'secondary' },
      { x1: 43, y1: 48, x2: 52, y2: 25, tone: 'primary' },
      { x1: 52, y1: 25, x2: 66, y2: 48, tone: 'support' },
      { x1: 66, y1: 48, x2: 81, y2: 25, tone: 'support' },
    ],
    note: 'The role network gives ZywOo, ropz and flameZ different phases of the round instead of competing lanes.',
  },
];

export const COUNTER_STRIKE_COMPARISON_EDITORIALS: readonly CounterStrikeEditorial[] = [
  {
    slug: 'super-falcons-vs-navi-astralis-faze-vitality-role-comparison',
    number: '037',
    title: 'Super Falcons Against Every Era-Defining Five',
    shortTitle: 'Super Falcons versus history',
    dek: 'NiKo, donk, m0NESY, kyousuke and b1t have more mechanical ceiling than any roster here. Prime Vitality still have the strongest role-for-role team, Astralis the best system, NAVI the greatest superstar structure and FaZe the best international network.',
    verdict: 'Super Falcons are the most talented five—and the least complete team in this comparison.',
    verdictDetail: 'donk wins the aggressive-rifle slot and b1t belongs with the elite anchors. m0NESY sits just below the s1mple–ZywOo AWP apex. kyousuke brings unmatched second-wave potential but no era-level proof. NiKo ranks last among these five IGLs. The roster leads mechanical ceiling and trails every historical five in demonstrated command, role certainty and tactical repetition.',
    readingMinutes: 23,
    publishedAt: '2026-09-02',
    dataCutoff: '2 September 2026',
    sample: 'Five fixed lineups: proposed Super Falcons; NAVI’s Boombl4–s1mple–electronic–Perfecto–b1t five in 2021; Astralis’ gla1ve–device–dupreeh–Magisk–Xyp9x five in 2018–2019; FaZe’s karrigan–broky–rain–ropz–Twistzz five in 2022–2023; and Vitality’s apEX–ZywOo–flameZ–ropz–mezii five in 2025–August 2026. Role scores are a declared 0–100 desk model combining peak individual level, fit, awards, championship conversion and tactical proof.',
    heroStats: [
      { value: '#1', label: 'Mechanical ceiling', detail: 'Super Falcons lead the four non-command roles' },
      { value: '#5', label: 'Proven command', detail: 'NiKo ranks last against four era-winning IGLs' },
      { value: '96.8', label: 'Firepower index', detail: 'Average of opening, AWP, second-rifle and anchor scores' },
      { value: '0', label: 'Maps together', detail: 'Every rival begins with an era; Falcons begin with a blueprint' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'The comparison set',
        title: 'Each opponent defined a different solution to elite Counter-Strike.',
        paragraphs: [
          'The comparison uses one lineup from each modern archetype. NAVI 2021 concentrated enormous freedom in s1mple and surrounded him with electronic’s force, b1t’s precision, Perfecto’s survival and Boombl4’s willingness to enter. Astralis distributed responsibility through rehearsed protocols. FaZe gave five international players autonomous jobs inside karrigan’s loose structure. Vitality separated four elite players by phase of the round around ZywOo.',
          'Super Falcons are different again. Their premise is surplus: the best aggressive rifler, an elite mobile AWPer, a second young spacetaker, a championship anchor and the greatest pure rifler of his generation acting as IGL. The roster does not solve scarcity. It tries to convert an unprecedented excess of duel-winning power into one sequence.',
          'The historical teams arrive with proof. NAVI won eight trophies in 2021, an Intel Grand Slam and the first flawless Major run. Astralis won 16 trophies across 2018–2019 and three consecutive Majors. FaZe won the 2022 Major, four elite events that year and an Intel Grand Slam before closing the Twistzz era with three straight CS2 trophies. Vitality won 14 titles by August 2026, including consecutive Majors and two Grand Slams. Super Falcons have zero maps together.',
        ],
        table: {
          caption: 'The five lineups and their defining competitive proof',
          headers: ['Team', 'Peak window', 'Five', 'Defining proof'],
          rows: [
            ['Super Falcons', 'Hypothetical, Sep 2026', 'NiKo · donk · m0NESY · kyousuke · b1t', 'Highest projected firepower; zero maps'],
            ['NAVI', '2021', 'Boombl4 · s1mple · electronic · Perfecto · b1t', 'Eight trophies; Grand Slam; flawless Major'],
            ['Astralis', '2018–2019', 'gla1ve · device · dupreeh · Magisk · Xyp9x', '16 trophies; three consecutive Majors; 58 weeks #1'],
            ['FaZe', '2022–2023', 'karrigan · broky · rain · ropz · Twistzz', 'Major; Grand Slam; first CS2 triple'],
            ['Vitality', '2025–Aug 2026', 'apEX · ZywOo · flameZ · ropz · mezii', '14 trophies; two Majors; two Grand Slams'],
          ],
        },
      },
      {
        number: '02',
        eyebrow: 'Functional alignment',
        title: 'Role-for-role comparison requires jobs, not roster order.',
        paragraphs: [
          'The five teams did not use identical labels. Boombl4 combined command with sacrificial entry work; gla1ve produced utility, information and above-average fragging; karrigan spent his life creating map control; apEX occupied active rotation positions. NiKo’s proposed role combines macro calling with an active lurk. They share final authority while reaching it through different spaces.',
          'The aggressive-rifle slot is equally varied. electronic was NAVI’s rifle engine while Boombl4 took cheaper first contacts. dupreeh opened alongside device. rain created early territory for FaZe. flameZ supplies Vitality’s pace. donk does all of that at greater volume and with a higher individual ceiling.',
          'The remaining mapping follows function: primary AWP; second rifle responsible for converting the space; and stabiliser responsible for anchors, extremities or closure. This places kyousuke beside b1t, Magisk, Twistzz and ropz, while the proposed b1t sits beside Perfecto, Xyp9x, FaZe ropz and mezii. Some names appear in different functional columns because elite players frequently carry more than one job.',
        ],
        table: {
          caption: 'Role-for-role alignment',
          headers: ['Function', 'Super Falcons', 'NAVI 2021', 'Astralis', 'FaZe', 'Vitality'],
          rows: [
            ['Command', 'NiKo', 'Boombl4', 'gla1ve', 'karrigan', 'apEX'],
            ['Aggressive rifle engine', 'donk', 'electronic', 'dupreeh', 'rain', 'flameZ'],
            ['Primary AWP', 'm0NESY', 's1mple', 'device', 'broky', 'ZywOo'],
            ['Second-wave rifle', 'kyousuke', 'b1t', 'Magisk', 'Twistzz', 'ropz'],
            ['Anchor / closer', 'b1t', 'Perfecto', 'Xyp9x', 'ropz', 'mezii'],
          ],
          note: 'The alignment compares competitive function; exact positions and resource levels still change by map.',
        },
      },
      {
        number: '03',
        eyebrow: 'The role graph',
        title: 'Super Falcons expand the mechanical axes and collapse at command.',
        paragraphs: [
          'The shape is more informative than one composite score. Super Falcons touch the outer edge in aggressive rifling, sit close to it in AWPing, second-wave power and anchoring, then contract sharply at command and role clarity. Every era-defining rival is rounder. Their weakest role remained connected to a proven operating system.',
          'Vitality produce the strongest total polygon because ZywOo matches s1mple’s AWP ceiling, ropz dominates the second-rifle and closing categories, flameZ supplies elite pace, mezii stabilises difficult positions and apEX has championship command proof. Astralis remain the only team at 100 for both command and clarity. NAVI own the highest AWP apex. FaZe have no maximum individual axis and almost no structural hole.',
          'The Falcons profile is therefore unprecedented but not mysterious. It is an extreme mechanical roster with one deliberately underqualified function. NiKo must convert a 65 command score into an era-level role without losing the rifle value that made the gamble attractive.',
        ],
        radar: {
          caption: 'Role ceiling and system-fit scorecard / 0–100',
          axes: ['Command', 'Aggressive rifle', 'Primary AWP', 'Second-wave rifle', 'Anchor / closer', 'Role clarity'],
          series: [
            { label: 'Super Falcons', color: '#d9ff43', values: [65, 100, 96, 96, 95, 80] },
            { label: 'NAVI 2021', color: '#70b7ff', values: [88, 94, 100, 92, 93, 96] },
            { label: 'Astralis 2018–19', color: '#ff5b35', values: [100, 90, 93, 96, 98, 100] },
            { label: 'FaZe 2022–23', color: '#d99cff', values: [98, 90, 90, 95, 96, 98] },
            { label: 'Vitality 2025–26', color: '#ffd84d', values: [95, 93, 100, 98, 94, 99] },
          ],
          note: 'Desk scores are ordinal comparisons inside this five-team set. Mechanical roles combine peak output and role fit; command and clarity add championship repetition and tactical proof.',
        },
        callout: 'The largest roster has the smallest command axis. That is the entire Super Falcons risk in one shape.',
      },
      {
        number: '04',
        eyebrow: 'Role one — command',
        title: 'NiKo loses the IGL comparison to all four era captains.',
        paragraphs: [
          'gla1ve is the benchmark. He combined elite calling, information-heavy CT play, 7.9 utility ADR in the dynasty’s early sample and enough firepower to rank eighth in the world in 2018. His system converted 81.2% of 5v4 advantages and recovered roughly one third of 4v5s. No captain here joined more tactical authority to more repeatable round-state control.',
          'karrigan ranks next because FaZe’s role network was an expression of his flexibility. He used himself and rain to gain early territory, then left broky, Twistzz and ropz to close. apEX follows with two Majors in 2025 and an architecture that kept four top-20 players in distinct phases. Boombl4 ranks fourth: B1ad3 supplied much of NAVI’s strategic framework, but Boombl4 carried the live authority and sacrificial pace of an eight-trophy year.',
          'NiKo is fifth by a wide margin. His earlier FaZe IGL period ended under unsustainable personal pressure, and the proposed roster asks him to replace a captain who just won the Cologne Major. His advantage is fragging; his deficit is every repeated late-round, veto and pressure decision the other four captains have already converted into an era.',
        ],
        bars: [
          { label: 'gla1ve', value: 100, display: '100', detail: 'Best protocol system and strongest command–fragging combination' },
          { label: 'karrigan', value: 98, display: '98', detail: 'Best international role builder and autonomy manager' },
          { label: 'apEX', value: 95, display: '95', detail: 'Two-Major peak with four differentiated stars' },
          { label: 'Boombl4', value: 88, display: '88', detail: 'Eight-title year inside B1ad3’s structure' },
          { label: 'NiKo', value: 65, display: '65', detail: 'Elite tactical voice without modern full-time IGL proof' },
        ],
        callout: 'NiKo is the best rifler in the IGL group and the least proven IGL in it.',
      },
      {
        number: '05',
        eyebrow: 'Role two — aggressive rifle',
        title: 'donk wins the only role comparison without qualification.',
        paragraphs: [
          'electronic gave NAVI a top-ten rifle beside the greatest player in the world. dupreeh shared Astralis’ opening burden with device and delivered elite entries inside exact utility timing. rain turned karrigan’s early map-control demands into a Major MVP. flameZ supplies the speed that prevents Vitality’s ZywOo–ropz core from becoming passive. All four were essential to an era.',
          'donk is still the clear winner. His 1.32 rating across 122 maps in 2026 follows 1.33 in 2024 and 1.34 in 2025. He combines entry volume, multi-kill rate and repeatability against elite opposition at a level none of the comparison players sustained. The role score reaches 100 because the field is defined relative to him.',
          'The tactical consequence is larger than the rating. Every historical team created premium conditions for its aggressive player. Super Falcons begin with a player who converts non-premium conditions anyway. That allows NiKo to spend less utility manufacturing a safe opening and more utility preserving the second wave.',
        ],
        bars: [
          { label: 'donk', value: 100, display: '100', detail: '1.32 in 2026 after consecutive 1.33+ years' },
          { label: 'electronic', value: 94, display: '94', detail: 'Top-tier rifle engine beside s1mple' },
          { label: 'flameZ', value: 93, display: '93', detail: 'Pace and first displacement in Vitality’s record season' },
          { label: 'dupreeh', value: 90, display: '90', detail: 'System entry with elite opening efficiency' },
          { label: 'rain', value: 90, display: '90', detail: 'Map-control entry and Major MVP peak' },
        ],
        callout: 'Every era had an elite opener. Super Falcons have the best one.',
      },
      {
        number: '06',
        eyebrow: 'Role three — primary AWP',
        title: 'm0NESY clears device and broky; s1mple and ZywOo retain the apex.',
        paragraphs: [
          's1mple’s 2021 remains the strongest single-player season in this comparison: a 1.35 annual rating, eight MVPs and a 1.47 flawless Major. ZywOo’s 2025 joined team dominance to the same universal role—opening, supporting, clutching and changing weapons without changing the system. Those two do more than operate the AWP; they become the team’s answer to every broken round.',
          'm0NESY ranks immediately below them. His 1.24 rating across 123 maps in 2026, Cologne Major MVP and 1.25 championship run place him above broky in direct output and above device in improvisational ceiling. He is the fastest mid-round processor of the three younger systems and already proved that freedom can coexist with a Major-winning structure.',
          'device remains the superior system AWPer. His movement, opening efficiency and low-error positioning made Astralis’ protocols executable without consuming the round. broky ranks fifth here but was the right AWPer for FaZe: reactive, low-maintenance and devastating after karrigan and rain created disorder. The role comparison measures apex; team fit explains why the lower raw score still won everything.',
        ],
        bars: [
          { label: 's1mple', value: 100, display: '100', detail: '1.35 in 2021; eight MVPs; 1.47 at the flawless Major' },
          { label: 'ZywOo', value: 100, display: '100', detail: 'Universal AWP engine of Vitality’s nine-title 2025' },
          { label: 'm0NESY', value: 96, display: '96', detail: '1.24 in 2026; Cologne Major MVP' },
          { label: 'device', value: 93, display: '93', detail: 'Best system AWP and opening partner in the set' },
          { label: 'broky', value: 90, display: '90', detail: 'Reactive closer perfectly matched to FaZe chaos' },
        ],
      },
      {
        number: '07',
        eyebrow: 'Role four — second rifle',
        title: 'kyousuke has the highest unspent ceiling and the weakest résumé.',
        paragraphs: [
          'This is the deepest comparison. NAVI’s b1t supplied 1.27 in the 2021 Cologne final and immediate championship precision. Magisk ranked seventh in 2018 while anchoring sites and adding 6.3 utility ADR. Twistzz became the flexible bridge between FaZe’s early map control and its clutch trio. ropz ranked third in 2025 and made Vitality’s entire CT role network cleaner.',
          'kyousuke matches their mechanical promise and none of their proof. He received primary T-side positions when he joined Falcons, while the Super Falcons design demotes him behind donk. The new job is favourable—trading a donk contact produces excellent fights—but it remains a transformation from protected spacetaker to repeatable second man.',
          'ropz wins the complete role because he combines star output, anchoring, lurking, secondary calling and closure. Magisk follows as the best protocol fit, Twistzz as the most flexible, and NAVI b1t as the cleanest young championship rifle. kyousuke’s score remains high because his aim and percentage play fit the job. His ranking remains last because the others built eras doing it.',
        ],
        table: {
          caption: 'Second-rifle comparison',
          headers: ['Player', 'Primary value', 'Era proof', 'Super Falcons comparison'],
          rows: [
            ['ropz', 'Lurk, anchor, close, second voice', '#3 player in nine-title 2025', 'More complete than kyousuke'],
            ['Magisk', 'Site strength and protocol utility', '#7 in 2018; three straight Majors', 'More system-proof than kyousuke'],
            ['Twistzz', 'Flexible contact and late round', 'Major and Grand Slam', 'More adaptable than kyousuke'],
            ['NAVI b1t', 'Precision and site conversion', 'Major and Grand Slam as a rookie', 'More proven than kyousuke'],
            ['kyousuke', 'Trade power and second penetration', 'One tier-one season', 'Highest remaining ceiling'],
          ],
        },
        callout: 'kyousuke is the luxury. The comparison players turned the same slot into infrastructure.',
      },
      {
        number: '08',
        eyebrow: 'Role five — anchor and closer',
        title: 'b1t supplies enough stability to belong; Xyp9x and ropz supply more late-round control.',
        paragraphs: [
          'b1t is already qualified for this table. He won Anchor of the Year in 2024, played difficult sites across multiple NAVI systems and carries two distinct forms of Major experience: the dominant Russian-speaking 2021 five and the international 2024 team. His headshot efficiency gives Super Falcons a low-resource player who still punishes the final execute.',
          'Xyp9x owns the historical closing edge. Astralis’ entire round structure preserved information, utility and his life for the late phase, turning “Clutch Minister” from a nickname into a system outcome. FaZe ropz adds more independent map control and a higher star ceiling. Perfecto is the closest direct analogue to the proposed b1t: quiet extremity work, low deaths and clutch conversion beside louder stars. mezii is the most connective, linking Vitality’s rotations without demanding the finish.',
          'b1t wins pure defensive mechanics and loses total role breadth to ropz and Xyp9x. That is sufficient for Super Falcons. The roster does not need another voice or another mobile star; it needs one site to remain intact while donk, kyousuke and m0NESY move elsewhere.',
        ],
        bars: [
          { label: 'Xyp9x', value: 98, display: '98', detail: 'Best system closer and late-round utility profile' },
          { label: 'FaZe ropz', value: 96, display: '96', detail: 'Highest independent anchor–lurk ceiling' },
          { label: 'b1t', value: 95, display: '95', detail: 'Best pure aim in the anchor group; two system languages' },
          { label: 'mezii', value: 94, display: '94', detail: 'Best connective rotation fit' },
          { label: 'Perfecto', value: 93, display: '93', detail: 'Low-resource survival and clutch fit beside s1mple' },
        ],
      },
      {
        number: '09',
        eyebrow: 'Mechanical ceiling versus proof',
        title: 'Super Falcons lead the role index and trail the trophy graph.',
        paragraphs: [
          'Removing command and averaging the four mechanical role scores produces the expected result. Super Falcons lead at 96.8, narrowly ahead of Vitality on 96.3. NAVI and Astralis follow because their power was distributed differently: NAVI concentrated the maximum in s1mple, while Astralis traded a singular 100 for strength at every slot. FaZe score lowest mechanically and remained devastating because their topology multiplied the pieces.',
          'The trophy graph reverses the order. Astralis lead the selected dynasty window with 16, Vitality have 14 by the cut-off, NAVI won eight in 2021 and the Twistzz FaZe five won eight significant LAN trophies across its life. Super Falcons remain at zero. Talent is the input; an era is repeated conversion after opponents understand the system.',
          'Capacity and organisation are different quantities. Super Falcons possess the largest capacity. Every rival has already organised less raw capacity into championships.',
        ],
        stats: [
          { value: '96.8', label: 'Super Falcons mechanical index', detail: 'Mean of opening, AWP, second rifle and anchor' },
          { value: '96.3', label: 'Vitality mechanical index', detail: 'The nearest complete roster' },
          { value: '16–0', label: 'Astralis–Falcons trophy proof', detail: 'Selected dynasty window versus hypothetical lineup' },
        ],
        bars: [
          { label: 'Astralis', value: 100, display: '16', detail: '2018–2019 dynasty window' },
          { label: 'Vitality', value: 88, display: '14', detail: 'January 2025 through August 2026' },
          { label: 'NAVI', value: 50, display: '8', detail: 'Complete 2021 season' },
          { label: 'FaZe', value: 50, display: '8', detail: 'Significant LAN trophies with Twistzz and ropz' },
          { label: 'Super Falcons', value: 0, display: '0', detail: 'A role design, not a played lineup' },
        ],
        callout: 'Super Falcons win the capacity graph. The era teams win the conversion graph.',
      },
      {
        number: '10',
        eyebrow: 'The map layouts',
        title: 'The same Mirage topology exposes five different team philosophies.',
        paragraphs: [
          'Standardising the five teams onto one functional Mirage board makes their internal geometry visible. The labels encode starting responsibility—anchor, central pressure, AWP lane, second contact and command connection. Spawns and opponent tendencies moved the pieces; the relationships remained.',
          'Super Falcons place the greatest force in the middle: donk, m0NESY and kyousuke can all produce the opening, while b1t and NiKo absorb the extremities. NAVI look similar but direct more of the map toward s1mple. Astralis distribute fallback relationships across all five positions. FaZe spend karrigan’s resources to preserve three closers. Vitality separate flameZ’s pressure, ZywOo’s universal response and ropz’s stability.',
          'The Falcons board has the highest immediate pressure and the weakest natural information chain. NiKo is physically separated from the central trio on many CT starts. Their protocol must therefore make donk’s first contact legible before it becomes a solo fight, and kyousuke must communicate the second lane rather than simply joining it.',
        ],
        mapLayouts: MIRAGE_LAYOUTS,
        callout: 'Astralis cover the map. NAVI bend it toward s1mple. FaZe stretch it into a clutch. Vitality divide it by phase. Super Falcons try to break it at first contact.',
      },
      {
        number: '11',
        eyebrow: 'Direct tactical collisions',
        title: 'Each era attacks a different Super Falcons weakness.',
        paragraphs: [
          'Astralis attack impatience. Their retained utility and advantage protocols force donk and kyousuke to win through a second layer after the first contact is denied. NAVI attack concentration: s1mple matches the server-winning ceiling while electronic and b1t punish any resource imbalance created by hunting him. FaZe attack closure, extending broken rounds until NiKo must out-call karrigan with fewer pieces.',
          'Vitality are the hardest theoretical opponent because they concede no obvious role edge beyond donk over flameZ and b1t over mezii as a pure anchor. ZywOo exceeds m0NESY’s universal output, ropz exceeds kyousuke’s total role value, and apEX owns vastly more current IGL proof than NiKo. Their roles are already separated in exactly the way Super Falcons are trying to learn.',
          'Super Falcons answer all four with pace. donk and m0NESY can make a protocol irrelevant before it completes, while kyousuke turns the displacement into a second elite duel. That advantage is real and narrow. Once a round reaches an equal-player late state, every historical team regains ground through clearer authority and more rehearsed spacing.',
        ],
        table: {
          caption: 'How the era teams attack the proposed five',
          headers: ['Opponent', 'Primary weapon', 'Falcons weakness attacked', 'Super Falcons answer'],
          rows: [
            ['NAVI 2021', 's1mple gravity plus electronic force', 'Resources collapse toward the star duel', 'donk creates a second simultaneous crisis'],
            ['Astralis', 'Utility and conditional protocols', 'Young entries repeat the first timing', 'm0NESY changes the lane before the execute'],
            ['FaZe', 'Autonomy and three-man closure', 'NiKo carries the final-call burden', 'Win the round before FaZe preserve the clutch trio'],
            ['Vitality', 'Role-separated four-star system', 'No soft role to target', 'Overwhelm flameZ’s pressure lane with donk–kyousuke'],
          ],
        },
      },
      {
        number: '12',
        eyebrow: 'The final order',
        title: 'Vitality remain the best five; Super Falcons become the most dangerous blueprint.',
        paragraphs: [
          'Role for role, prime Vitality win this comparison. ZywOo and ropz give them two category leaders, flameZ remains an elite aggressive engine, mezii completes the low-resource network and apEX supplies proven command. Astralis rank second because no team has ever joined comparable role clarity to superior tactical repetition. NAVI rank third through the greatest superstar season and an almost perfect support structure. FaZe rank fourth, owning the best international autonomy but the lowest raw mechanical index in this field.',
          'Super Falcons rank fifth as a complete team and first as a talent construction. That order follows directly from comparing a five that has never played with four teams that changed Counter-Strike. donk is the best aggressive player here, m0NESY is already an era-capable AWPer, b1t solves the anchor slot, and kyousuke can become an unprecedented second wave. None of those facts manufacture elite calling experience for NiKo.',
          'The ceiling still exceeds every rival. If NiKo’s narrow command model works, Super Falcons move past FaZe and NAVI immediately, then attack Astralis and Vitality through firepower those systems never had to contain in four separate players. Until then, the final answer is exact: the roster is history’s strongest collection of roles, not history’s strongest team.',
        ],
        table: {
          caption: 'Category winners and the complete verdict',
          headers: ['Category', 'Winner', 'Decisive reason'],
          rows: [
            ['Mechanical ceiling', 'Super Falcons', 'Best aggressive rifler plus elite AWP, second rifle and anchor'],
            ['Role completeness', 'Vitality', 'No collision across four stars and a proven IGL'],
            ['Tactical system', 'Astralis', 'Protocols, utility and role clarity survived every anti-strat'],
            ['Superstar architecture', 'NAVI', 'Greatest individual season inside a stable support hierarchy'],
            ['International flexibility', 'FaZe', 'Five autonomous roles joined by karrigan’s command'],
            ['Best complete five', 'Vitality', 'Highest combined role score with championship proof'],
          ],
        },
        callout: 'Final answer: Super Falcons are the most talented roster ever proposed. Prime Vitality remain the better team until NiKo turns that talent into a repeatable system.',
      },
    ],
    sources: [
      { label: 'The Server Room — Super Falcons role blueprint', url: 'https://me-mhq.pages.dev/editorials/falcons-final-form-niko-donk-monesy-kyousuke-b1t-superteam', use: 'Proposed role hierarchy, current-player inputs and map-by-map responsibilities used as the comparison baseline.' },
      { label: 'HLTV — NAVI named the top team of 2021', url: 'https://www.hltv.org/news/33041/top-10-teams-of-2021', use: 'Full-year team ranking context and the 2021 lineup’s place above the field.' },
      { label: 'HLTV — s1mple declares the NAVI era', url: 'https://www.hltv.org/news/32998/s1mple-right-now-id-say-yes-were-in-the-navi-era', use: 'Eight 2021 trophies, four consecutive LAN wins and eight s1mple MVPs.' },
      { label: 'HLTV — NAVI complete the flawless Major', url: 'https://www.hltv.org/news/32761/navi-win-pgl-major-stockholm-over-g2-make-history-by-going-undefeated', use: 'Undefeated Major run and s1mple’s 1.47 event rating.' },
      { label: 'HLTV — NAVI win Cologne 2021', url: 'https://www.hltv.org/news/32075/navi-beat-g2-3-0-to-win-iem-cologne', use: 'Five-player distribution in an elite final and the s1mple–b1t conversion peak.' },
      { label: 'HLTV — NAVI role disruption after 2021', url: 'https://www.hltv.org/news/36570/stat-check-how-will-the-new-navi-set-up', use: 'Evidence that electronic’s IGL move and b1t and Perfecto role changes damaged the championship balance.' },
      { label: 'HLTV — Astralis top team of 2018', url: 'https://www.hltv.org/news/25740/top-10-teams-of-2018', use: 'Ten-title year, uninterrupted number-one position and dynasty context.' },
      { label: 'HLTV — Astralis: A legend in the making', url: 'https://www.hltv.org/news/24545/astralis-a-legend-in-the-making', use: 'Opening rates, 81.2% 5v4 conversion, 4v5 recovery, flash assists and 29.0 utility ADR.' },
      { label: 'HLTV — Intel Grand Slams compared', url: 'https://www.hltv.org/news/35883/intel-grand-slams-compared', use: 'Astralis protocol model and FaZe’s four-star, international role architecture.' },
      { label: 'HLTV — FaZe named Team of the Year 2022', url: 'https://www.hltv.org/news/35382/hltv-award-show-2022-recap-who-were-the-winners', use: 'Katowice, EPL, Major and Cologne championship run.' },
      { label: 'HLTV — karrigan on the FaZe role network', url: 'https://www.hltv.org/news/33182/karrigan-on-ropz-twistzz-and-broky-the-sky-is-the-limit-for-them-to-stay-together-for-a-long-time', use: 'ropz structure, Twistzz flexibility, broky fit and the three-player late-round network.' },
      { label: 'HLTV — ropz’s 2022 role analysis', url: 'https://www.hltv.org/news/35350/top-20-players-of-2022-ropz-8', use: '31.8% 4v5 recovery and FaZe’s clutch-centred construction.' },
      { label: 'HLTV — Twistzz leaves the era-defining FaZe five', url: 'https://www.hltv.org/news/37655/faze-confirm-twistzz-departure', use: 'Major, Grand Slam, three-event CS2 streak and complete roster boundary.' },
      { label: 'HLTV — Vitality role redistribution after ropz', url: 'https://www.hltv.org/news/40932/vitality-neo-interview-free-transfers-how-zywoo-helped-sign-ropz-and-starting-fresh-in-2025', use: 'ropz anchoring and the CT freedom returned to flameZ and mezii.' },
      { label: 'HLTV — ZywOo named the best player of 2025', url: 'https://www.hltv.org/news/43610/top-20-players-of-2025-zywoo-1', use: 'ZywOo’s universal peak and Vitality’s opening championship sequence.' },
      { label: 'HLTV — Vitality complete back-to-back Majors', url: 'https://www.hltv.org/news/43449/vitality-beat-faze-3-1-to-become-back-to-back-major-champions-in-budapest', use: 'Nine-title year, two Majors and 37-series streak context.' },
      { label: 'HLTV — mezii ranked twelfth in 2025', url: 'https://www.hltv.org/news/43534/top-20-players-of-2025-mezii-12', use: 'Low-resource output and connective role inside the four-star distribution.' },
      { label: 'HLTV — donk 2026 career split', url: 'https://www.hltv.org/stats/players/career/21167/donk', use: '1.32 rating across 122 maps and three-year elite baseline.' },
      { label: 'HLTV — m0NESY 2026 career split', url: 'https://www.hltv.org/stats/players/career/19230/m0nesy', use: '1.24 rating across 123 maps and Major sample.' },
      { label: 'HLTV — b1t 2026 career split', url: 'https://www.hltv.org/stats/players/career/18987/b1t', use: 'Current anchor output and Major rating.' },
    ],
  },
];
