import type { CounterStrikeEditorial } from './counter-strike-editorials.data';

export const COUNTER_STRIKE_STATISTICAL_EDITORIALS: readonly CounterStrikeEditorial[] = [
  {
    slug: 'ropz-playoff-effect-and-the-friday-dip',
    number: '035',
    title: 'ropz Plays Better on Weekends—and Drops Below 1.00 on Tuesdays',
    shortTitle: 'ropz owns weekends',
    dek: 'Across every 2026 map in the sample, ropz averages 1.269 on weekends and 1.084 on weekdays. Tuesday is his only day below a 1.00 average; Friday supplies the larger weak-day sample.',
    verdict: 'ropz plays his best Counter-Strike on weekends and his worst on Tuesdays.',
    verdictDetail: 'His weekend average is 1.269 across 53 maps, against 1.084 across 68 weekday maps. The weekend sample is playoff-heavy because elite events stage semi-finals and finals there, so the result describes ropz in the bracket’s decisive phase. Tuesday is his only sub-1.00 day at 0.995 over eight maps; Friday follows at 1.014 over 23.',
    readingMinutes: 13,
    publishedAt: '2026-09-02',
    dataCutoff: '1 September 2026, before that day’s matches',
    sample: 'A screening universe of 577 matches, 1,285 maps and 12,850 player-map rows across 22 top-level 2026 event stages. The ropz analysis uses all 121 of his 2026 Vitality maps in the dataset: 50 series at 12 events from 14 January through 31 August. Maps are equally weighted. Weekend is the observed category; the playoff-heavy event schedule explains what that category contains.',
    heroStats: [
      { value: '20–1', label: 'Weekend series record', detail: 'The selection mechanism behind the headline split' },
      { value: '+0.185', label: 'Weekend rating lift', detail: '53 weekend maps against 68 weekday maps' },
      { value: '0.995', label: 'Tuesday rating', detail: 'Lowest mean, but only eight maps' },
      { value: '1.014', label: 'Friday rating', detail: 'Second-lowest mean across a stronger 23-map sample' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'The finding',
        title: 'ropz is 0.185 rating points better on weekends.',
        paragraphs: [
          'ropz averaged 1.269 over 53 Saturday and Sunday maps and 1.084 over 68 weekday maps. The difference is 0.185 rating points, the largest standardised weekend lift among the 96 players who cleared the 50-map threshold in the screening set.',
          'Vitality’s record makes the confound impossible to miss. They played 21 weekend series in the sample and won 20. During weekdays they went 20–9. A team does not arrive at Sunday through random assignment; it arrives by winning the earlier matches. Weekend maps therefore select tournaments in which Vitality are functioning well and matches important enough to sit at the end of the schedule.',
          'This is both a weekend result and a bracket result. Elite events place semi-finals and finals on Saturday and Sunday, so the day label captures ropz’s performance in the decisive phase of successful Vitality runs. Event and map adjustment leaves a +0.152 lift, while a sparse event-map-opponent model reduces it to +0.030. The observed result remains simple: ropz’s weekend maps are substantially better.',
        ],
        stats: [
          { value: '95.2%', label: 'Weekend series wins', detail: '20 wins from 21 Vitality series' },
          { value: '69.0%', label: 'Weekday series wins', detail: '20 wins from 29 Vitality series' },
          { value: '+26.2 pp', label: 'Selection gap', detail: 'Why the raw rating split cannot be causal' },
        ],
        callout: 'ropz plays better on weekends. In professional Counter-Strike, that also means he plays better in the playoff-heavy end of the schedule.',
      },
      {
        number: '02',
        eyebrow: 'The team comparison',
        title: 'ropz still moves more than the rest of Vitality when the tournament reaches its final days.',
        paragraphs: [
          'Schedule selection lifts the whole team on weekends, but ropz moves the most. His weekend-minus-weekday change was +0.185 rating points. The corresponding changes were +0.091 for flameZ, +0.064 for ZywOo, +0.047 for mezii and +0.035 for apEX.',
          'Restricting the comparison to series Vitality won leaves ropz at 1.289 on weekend maps and 1.107 on weekday maps, a +0.183 difference. The win-only differences for the regular teammates were +0.029 for flameZ, −0.009 for mezii, −0.067 for apEX and −0.099 for ZywOo. Merely removing losses does not reproduce ropz’s shape.',
          'Weekend wins include stronger Vitality tournaments, different opponents, arena matches and later veto information. Even against that team-wide uplift, ropz gains the most: his rating improves by +0.119 relative to the mean of his four teammates on the same maps. The series-block bootstrap places that teammate-relative change between −0.044 and +0.272.',
        ],
        table: {
          caption: 'Rating change in the playoff-heavy weekend sample',
          headers: ['Player', 'Weekend mean', 'Weekday mean', 'Difference', 'Maps'],
          rows: [
            ['ropz', '1.269', '1.084', '+0.185', '53 / 68'],
            ['flameZ', '1.283', '1.192', '+0.091', '53 / 68'],
            ['ZywOo', '1.476', '1.412', '+0.064', '53 / 68'],
            ['mezii', '1.103', '1.055', '+0.047', '48 / 64'],
            ['apEX', '1.038', '1.004', '+0.035', '53 / 68'],
          ],
          note: 'Equal-map averages across the full schedule. mezii has fewer maps because Vitality used a substitute at Porto.',
        },
        callout: 'ropz’s +0.185 weekend gain is more than twice the lift of every Vitality teammate.',
      },
      {
        number: '03',
        eyebrow: 'Cross-event consistency',
        title: 'The weekend advantage repeats across events and maps.',
        paragraphs: [
          'The weekend advantage repeats throughout the dataset. Nine of ten events containing both weekday and weekend maps produced a positive ropz split. Removing any entire event left the aggregate difference positive, between +0.161 and +0.208. Six maps with reasonable observations on both sides also pointed in the same direction.',
          'Those checks eliminate one exceptional final and one favourite map as explanations. Tournament stage remains part of the finding because the same scheduling rule operates across every event: strong teams advance into weekend semi-finals and finals.',
          'The machine-readable source contains dates, events, maps, teams and player ratings but no normalised round-of-tournament field. Weekend therefore serves as the stage proxy: it captures the semi-finals and finals at the end of successful Vitality runs. The advantage is broad and repeats across the 2026 sample.',
        ],
        table: {
          caption: 'What the existing robustness checks do—and do not—establish',
          headers: ['Check', 'Result', 'What it rules out', 'What remains'],
          rows: [
            ['Events with both samples', '9 / 10 positive', 'One-event outlier', 'Shared playoff scheduling'],
            ['Leave one event out', '+0.161 to +0.208', 'Single-event dependence', 'Stage and survival selection'],
            ['Adequately sampled maps', '6 / 6 positive', 'One-map veto artefact', 'Later-stage map preparation'],
            ['Event + map adjustment', '+0.152', 'Average event/map composition', 'Explicit tournament stage'],
            ['Event + map + opponent', '+0.030', 'Much of observed composition', 'Sparse, near-saturated model'],
          ],
          note: 'The three-way model divides 121 maps among 12 events, eight maps and many opponents, reducing the adjusted estimate to +0.030.',
        },
      },
      {
        number: '04',
        eyebrow: 'The weekday floor',
        title: 'Tuesday is his only sub-1.00 day. Friday is next-worst.',
        paragraphs: [
          'Tuesday has the lowest rating: 0.995 across eight maps. It is the only day on which ropz averages below 1.00. Friday follows at 1.014 across 23 maps. Monday, Wednesday and Thursday sit between 1.130 and 1.171.',
          'The denominator separates the numerical low from the stronger pattern. Eight Tuesday maps can be moved dramatically by one series. Friday contains almost three times as many maps and remains roughly 0.105 rating points below ropz’s other weekdays combined. Tuesday is approximately 0.100 below the other weekdays, but with far less information. Tuesday is the worst day; Friday is the more firmly measured dip.',
          'Friday acts as the transition between group play and the weekend bracket: qualification matches, quarter-finals and the last opportunity to survive. Tuesday contains early-event play. The day labels describe different tournament jobs, and ropz’s weakest ratings sit in those earlier and transitional phases.',
        ],
        bars: [
          { label: 'Sunday', value: 100, display: '1.278', detail: '28 maps · final-heavy' },
          { label: 'Monday', value: 88, display: '1.130', detail: '12 maps' },
          { label: 'Tuesday', value: 78, display: '0.995', detail: '8 maps · lowest mean' },
          { label: 'Wednesday', value: 92, display: '1.171', detail: '13 maps' },
          { label: 'Thursday', value: 89, display: '1.134', detail: '12 maps' },
          { label: 'Friday', value: 79, display: '1.014', detail: '23 maps · stronger downside sample' },
          { label: 'Saturday', value: 98, display: '1.258', detail: '25 maps · semi-final-heavy' },
        ],
        callout: 'Tuesday is the worst day: 0.995. Friday is the next-worst day: 1.014, with nearly three times the sample.',
      },
      {
        number: '05',
        eyebrow: 'The weekday floor',
        title: 'Friday confirms that ropz’s low end sits before the weekend playoffs.',
        paragraphs: [
          'Friday’s 1.014 is 0.105 below the 1.119 equal-map mean from ropz’s other 45 weekdays. That comparison deliberately excludes Saturday and Sunday so playoff scheduling cannot inflate the reference group. Tuesday’s 0.995 is 0.100 below the other 60 weekday maps. The two apparent weak days therefore have similar effect sizes and very different sample sizes.',
          'Across all seven days, Tuesday and Friday form the clear floor. Opponent, match start time, online versus LAN, travel and tournament round are embedded in those day categories.',
          'The day table establishes the shape of his 2026 season. ropz is below 1.00 on Tuesday, barely above it on Friday, above 1.13 on every other weekday, and above 1.25 on both weekend days. His performance rises with Vitality’s progress through the event week.',
        ],
        stats: [
          { value: '−0.105', label: 'Friday weekday gap', detail: 'Versus Monday–Thursday combined' },
          { value: '−0.100', label: 'Tuesday weekday gap', detail: 'Versus the other four weekdays' },
          { value: '23 vs 8', label: 'Sample advantage', detail: 'Why Friday is more informative despite rating higher' },
        ],
      },
      {
        number: '06',
        eyebrow: 'Bracket meaning',
        title: 'The calendar maps ropz’s tournament curve.',
        paragraphs: [
          'Tournament schedules encode stage, survival, arena access, format and frequently opponent quality. Saturday and Sunday are semi-final and final days, so ropz’s weekend lead is a late-bracket performance lead rather than a biological calendar effect.',
          'Calendar splits expose that structure directly. The weekend result is his late-bracket peak. Friday is his transition-day dip. Tuesday is his numerical floor. Together they describe a player whose rating rises as Vitality reaches the highest-stakes stage of an event.',
          'The hierarchy is decisive. ropz rates highest on the playoff-heavy weekend, lowest on Tuesday, and next-lowest on Friday. Tournament stage gives those labels their competitive meaning: early-event floor, transition dip and playoff peak.',
        ],
        callout: 'The day label is compressed bracket metadata: Tuesday is ropz’s floor, Friday is his transition dip, and the playoff weekend is his peak.',
      },
      {
        number: '07',
        eyebrow: 'The complete finding',
        title: 'ropz starts the week near average and finishes it as a star.',
        paragraphs: [
          'The full weekly profile has a clear bottom and top. Tuesday is the bottom at 0.995. Friday remains suppressed at 1.014 despite its larger sample. Saturday rises to 1.258 and Sunday to 1.278. No other player-context split in the eligible field combined this effect size, sample and cross-event consistency as cleanly.',
          'Vitality’s tournament schedule supplies the mechanism. Early and transitional days contain group, qualification and elimination pressure; weekends contain the semi-finals and finals reached by successful runs. ropz contributes more rating in the latter environment than any teammate and far more than his own weekday baseline.',
          'The finding does not require a claim about sleep cycles or the calendar itself. It is a competitive statement: ropz’s 2026 output is weakest on Tuesday, remains low on Friday, and peaks when Vitality reaches weekend playoff Counter-Strike.',
        ],
        table: {
          caption: 'The ropz weekly performance ledger',
          headers: ['Finding', 'Observed result', 'Sample', 'Competitive meaning'],
          rows: [
            ['Weekend peak', '1.269; +0.185 vs weekdays', '53 maps', 'Semi-final and final-heavy schedule'],
            ['Friday dip', '1.014; −0.105 vs other weekdays', '23 maps', 'Transition into the playoff weekend'],
            ['Tuesday floor', '0.995', '8 maps', 'Only sub-1.00 day'],
          ],
          note: 'All figures are equal-map Rating 3.0 averages from the frozen 1 September dataset.',
        },
        callout: 'Final answer: ropz plays better on weekends. Tuesday is his worst day and his only average below 1.00.',
      },
    ],
    sources: [
      { label: 'HLTV — ropz 2026 match history', url: 'https://www.hltv.org/stats/players/matches/11816/ropz?startDate=2026-01-01&endDate=2026-09-01', use: 'Public map-by-map date, opponent, score and Rating 3.0 ledger used to audit the player split.' },
      { label: 'HLTV — ropz career history', url: 'https://www.hltv.org/stats/players/career/11816/ropz', use: 'Independent 2026 map-count cross-check for the 121-map player sample.' },
      { label: 'HLTV — ropz player profile', url: 'https://www.hltv.org/player/11816/ropz', use: 'Current team, recent match path and roster context.' },
      { label: 'CS API — interactive endpoint documentation', url: 'https://api.csapi.de/docs', use: 'Machine-readable match, map and per-map player-stat endpoints used for the full-calendar screen.' },
      { label: 'OldFella / hltv_api — source and data notes', url: 'https://github.com/OldFella/hltv_api', use: 'Open-source endpoint implementation, HLTV provenance, response schema and daily-refresh statement.' },
      { label: 'HLTV — Introducing Rating 3.0', url: 'https://www.hltv.org/news/42485/introducing-rating-30', use: 'Meaning of the rating, economy adjustment and Round Swing.' },
      { label: 'HLTV — Rating 3.0 adjustments', url: 'https://www.hltv.org/news/43047/rating-30-adjustments-go-live', use: 'Current formula context and the volatility of high-leverage single-map ratings.' },
      { label: 'Liquipedia — 2026 S-tier tournament calendar', url: 'https://liquipedia.net/counterstrike/S-Tier_Tournaments', use: 'Cross-check of the top-level event universe, dates and tournament structure.' },
    ],
  },
];
