import type { CounterStrikeEditorial } from './counter-strike-editorials.data';

export const COUNTER_STRIKE_META_EDITORIALS: readonly CounterStrikeEditorial[] = [
  {
    slug: 'how-astralis-wrote-the-grammar-of-modern-counter-strike',
    number: '030',
    title: 'How Astralis Wrote the Grammar of Modern Counter-Strike',
    shortTitle: 'The tactical legacy of Astralis',
    dek: 'The grenades were memorable. The deeper revolution was a system for turning information, roles and small advantages into rounds with almost industrial reliability.',
    verdict: 'Astralis changed the unit of tactics from the play to the protocol.',
    verdictDetail: 'Their lasting innovation was not a single execute. It was the idea that utility, positioning, communication and fallback decisions could be rehearsed as one conditional system. Modern elite teams still play inside that grammar.',
    readingMinutes: 18,
    publishedAt: '2026-08-29',
    dataCutoff: '29 August 2026',
    sample: 'The Magisk roster’s 2018–2019 dynasty, with tactical statistics from HLTV’s August and December 2018 analyses, the completed 31-map Nuke LAN streak, historical map-pool reporting and contemporary player/coach interviews.',
    heroStats: [
      { value: '29.0', label: 'Utility ADR', detail: 'Team figure in HLTV’s August 2018 tactical sample' },
      { value: '81.2%', label: '5v4 round conversion', detail: 'Rounds won after Astralis secured the opening kill' },
      { value: '≈33%', label: '4v5 recovery', detail: 'Nearly one in three rounds won after conceding first death' },
      { value: '31–0', label: 'Nuke LAN streak', detail: 'Completed before ENCE ended it in Madrid in May 2019' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'The actual invention',
        title: 'Astralis did not invent grenades. They industrialised their relationship to information.',
        paragraphs: [
          'The simplified history says Astralis changed Counter-Strike by throwing better grenades. That is true in the way that saying a computer changed offices by typing faster is true: it identifies the visible instrument and misses the operating model. HE stacks, late molotovs and exact flashes mattered because they belonged to a shared decision system. Every grenade either damaged a likely position, denied a timing, preserved a teammate or made the next rotation more certain.',
          'Before the dynasty, elite tactical identity was often described through set pieces: a smoke execute, a boost, a pistol round or a caller’s read. Astralis moved the emphasis toward protocols—if this information appears, these players fall back, this crossfire forms, this utility is retained and this player becomes the next contact. The play could change while the logic remained stable.',
          'That is the durable innovation. A set piece depreciates as soon as opponents learn the lineup. A protocol survives because it defines a family of responses. Astralis could show the same opening shape, receive a different reaction and still reach a coherent late round. Modern analysts call this structure. In 2018, Astralis made its competitive value impossible to ignore.',
        ],
        callout: 'The copyable object was never “throw this grenade.” It was “make every grenade and every rotation answer the same shared model of the round.”',
      },
      {
        number: '02',
        eyebrow: 'Utility becomes offence',
        title: 'Twenty-nine points of utility damage per round changed what a gunfight began with.',
        paragraphs: [
          'HLTV’s August 2018 sample measured Astralis at 29.0 utility ADR. gla1ve supplied 7.9, Xyp9x 6.4 and Magisk 6.3; those three alone generated 20.6 points, or 71.0% of the team total. gla1ve also produced 0.07 of the team’s 0.20 flash assists per round. The caller was not standing outside the mechanical system. He was one of its highest-volume enablers.',
          'The famous double-HE stacks explain part of the number. zonic pushed the roster to catalogue low-risk locations where two grenades could kill a full-health opponent or leave one player functionally removed from the next duel. The mathematical exchange was attractive: $600 of replenishable utility could delete a $4,750 AWP before a rifle was exposed. Even without a kill, 80–90 damage changed the expected value of every later body shot, wallbang and molotov tick.',
          'The more consequential habit was timing. Astralis were unusually willing to retain smokes and incendiaries for the second decision of a round. A smoke at 1:35 buys map control; the same smoke at 0:32 can erase the only viable path to a site. Utility ceased to be merely the entrance fee for an execute. It became damage, clock control and a method of shrinking the opponent’s decision tree.',
        ],
        table: {
          caption: 'Astralis’ measured utility distribution, August 2018 sample',
          headers: ['Measure', 'Value', 'Share / implication'],
          rows: [
            ['Team utility ADR', '29.0', 'Baseline for the five-player system'],
            ['gla1ve utility ADR', '7.9', '27.2% of team total'],
            ['Xyp9x utility ADR', '6.4', '22.1% of team total'],
            ['Magisk utility ADR', '6.3', '21.7% of team total'],
            ['Three-player subtotal', '20.6', '71.0% of all utility damage'],
            ['gla1ve flash assists', '0.07 / round', '35% of the team’s 0.20 rate'],
          ],
          note: 'Shares are arithmetic from HLTV’s published team and player rates. They describe the named sample, not every map of the dynasty.',
        },
      },
      {
        number: '03',
        eyebrow: 'Advantage engineering',
        title: 'Their great statistic was not the opening kill. It was what happened next.',
        paragraphs: [
          'device and dupreeh combined for 0.28 of Astralis’ 0.56 opening kills per round in the published sample—exactly half. Yet the team’s defining number came after that contact: Astralis won 81.2% of rounds in which they found the opening kill. They were also recovering nearly 33% after losing the opener.',
          'Those two rates describe the same system from opposite sides. At 5v4, Astralis reduced unnecessary contact, preserved trade spacing and forced the opponent to spend time locating the new setup. At 4v5, they resisted the instinct to solve the deficit with five seconds of isolated aggression. They denied the pinch, sought information safely and concentrated the remaining players around a readable finish.',
          'A useful derived measure is the gap between conversion and recovery: roughly 48 percentage points. That gap is large because first kills matter, but a 33% disadvantage rate means the opening death was not a verdict. Astralis turned game state into a conditional problem. The modern expectation that a professional team should have explicit 5v4 and 4v5 procedures is one of the dynasty’s clearest descendants.',
        ],
        stats: [
          { value: '0.28 / 0.56', label: 'Openings from device + dupreeh', detail: '50% of the team’s opening kills per round' },
          { value: '81.2%', label: 'Conversion after first kill', detail: 'The advantage became a controlled round' },
          { value: '≈33%', label: 'Recovery after first death', detail: 'Disadvantage did not trigger automatic desperation' },
        ],
        callout: 'Astralis made “play the percentages” concrete: a five-versus-four was an asset to be protected, not permission to hunt.',
      },
      {
        number: '04',
        eyebrow: 'Nuke as a laboratory',
        title: 'The 31–0 streak was a communication architecture disguised as map dominance.',
        paragraphs: [
          'Nuke made Astralis’ model visible because the map punishes ambiguous information. A player heard above may be ending upper, dropping vent or creating a rotation toward lower. Astralis placed Xyp9x and gla1ve on the ramp and yard extremities, Magisk as the upper-site rock, dupreeh as the vent rotator and device as a mobile AWP connecting the calls. The roles described not only where each player began, but who supplied which kind of information.',
          'In HLTV’s analysis during the streak, Astralis’ Nuke CT side found the opening kill about 66% of the time and converted 86% of those 5v4s. Their T side won 64% of rounds on a map that remained structurally CT-favoured. They did not need dozens of unrelated executes: two- and three-player moves gained yard, secret or vent control, induced rotations, and allowed the opposite extremity to attack the gap.',
          'Economy reinforced the loop. They won roughly 60% of pistols, converted about 80% of the following rounds, and still won half of second-round force-buys after losing a pistol in the analysed window. Early money enabled full utility; full utility protected survival; survival carried equipment forward. The eventual 31-map LAN streak was not a mystical comfort map. It was a compounding system.',
        ],
        table: {
          caption: 'The Nuke operating model during the streak',
          headers: ['Layer', 'Observed indicator', 'Tactical effect'],
          rows: [
            ['CT information', '≈66% opening-kill rate', 'More rounds begin with known advantage'],
            ['CT conversion', '86% after the opener', 'Extremities stall; rotations arrive coherently'],
            ['T-side pressure', '64% round win rate', 'Small control groups dislocate a CT-sided map'],
            ['Pistols', '≈60% won', 'Early economy control'],
            ['Anti-eco', '≈80% conversion', 'Fewer resets after the pistol'],
            ['LAN result', '31 consecutive wins', 'The protocol survived repeated anti-stratting'],
          ],
          note: 'Round-level figures come from HLTV’s analysis at 26–0; 31–0 is the completed streak reported when ENCE ended it.',
        },
      },
      {
        number: '05',
        eyebrow: 'Role design',
        title: 'Five specialists became one mechanism because support stopped meaning sacrifice without agency.',
        paragraphs: [
          'Astralis’ roles were clear without being low-agency. device’s AWP created openings but remained mobile. dupreeh accepted the first collision and the vent rotation. Magisk anchored the highest-contact site. Xyp9x survived, supported and closed. gla1ve called while generating elite flash and utility value. The system assigned responsibility, not a hierarchy of people permitted and forbidden to decide.',
          'Xyp9x illustrates the difference. He recorded fewer openings and multikills, but only 0.57 deaths per round, 0.17 assists and a 25.3% support-round rate in the published sample. Survival was productive because it preserved an extremity, utility and a late-round decision-maker. His role was not “lose so device can trade.” It was “keep the map logically connected until the round reaches the state we prepared.”',
          'The whole five appearing in HLTV’s 2018 Top 20 was partly an outcome of winning, but it also captures the absence of a targetable weak link. Modern roster construction increasingly evaluates anchors, supportive riflers and IGLs through the round states they stabilize, not raw kill totals alone. Astralis did not invent specialization; they demonstrated how much individual ceiling good specialization could release.',
        ],
        bars: [
          { label: 'device', value: 100, display: '#2', detail: 'HLTV Top 20 of 2018' },
          { label: 'dupreeh', value: 84, display: '#5', detail: 'Aggressive opening rifle' },
          { label: 'Magisk', value: 72, display: '#7', detail: 'High-contact anchor' },
          { label: 'gla1ve', value: 64, display: '#8', detail: 'IGL, flash and utility engine' },
          { label: 'Xyp9x', value: 46, display: '#13', detail: 'Anchor, support and closer' },
        ],
      },
      {
        number: '06',
        eyebrow: 'Veto as strategy',
        title: 'They turned an unpopular map into a ban that improved every other map.',
        paragraphs: [
          'Nuke had appeared only twice at the Boston Major and was still the least-played Big Event map of 2018. Astralis treated that neglect as available territory. Once Nuke became effectively unpickable against them, opponents spent an early veto removing it and entered the rest of the series with less control.',
          'The April 2018 removal of Cobblestone also erased Astralis’ long-term permaban. That external change mattered and should not be rewritten as tactical genius. What Astralis did with the opportunity was decisive: by August they were undefeated on Nuke and Dust2, 11–3 on Overpass, strong on Inferno and Mirage, and winning between 64% and 71% of CT rounds across six non-Cache maps in HLTV’s sample.',
          'The lasting lesson is not “learn every map.” It is to develop one opponent-distorting map while ensuring the remainder has no free punishment pick. A signature map changes the entire best-of-three before round one. Teams now hire analysts and allocate practice blocks around exactly this portfolio problem: not seven independent win rates, but the sequence of choices the pool forces on a rival.',
        ],
        callout: 'Map mastery compounds: one near-forced ban protects two comfort picks and makes the decider more predictable.',
      },
      {
        number: '07',
        eyebrow: 'What survived',
        title: 'The Astralis meta disappeared because it became normal.',
        paragraphs: [
          'By late 2019, opponents had copied the obvious surface: HE stacks, deeper utility books, delayed executes and more systematic anti-stratting. Astralis’ tactical advantage narrowed. That is evidence of influence, not a rebuttal to it. A genuine meta innovation becomes harder to see after the field absorbs it.',
          'The enduring pieces are now baseline expectations at elite level: nade damage is reviewed as a team output; anchors are judged by survival and delay; analysts catalogue opponent reactions; 5v4s trigger risk reduction; CT rotations follow explicit information ownership; practice produces contingency trees rather than only five-man executes. None belongs exclusively to Astralis today. That is what successful diffusion looks like.',
          'Astralis did not originate every component, and their legacy does not depend on claiming they did. They combined the components, validated them through unprecedented results and forced the elite field to adopt the combination as the standard. They changed how a good round was built and explained.',
        ],
        table: {
          caption: 'Legacy ledger: documented contribution versus interpretation',
          headers: ['Practice', 'Astralis evidence', 'Durable reading'],
          rows: [
            ['HE stacks', 'zonic-led systematic search; 29.0 utility ADR', 'Utility can create the duel, not only support it'],
            ['Advantage protocols', '81.2% 5v4 conversion; ≈33% 4v5 recovery', 'Round state should change team-wide risk'],
            ['Information rotations', 'Nuke role network; 86% CT 5v4 conversion', 'The caller is distributed across information owners'],
            ['Role value', 'All five Top 20; Xyp9x 25.3% support rounds', 'Low-contact roles can retain high agency'],
            ['Veto pressure', '31–0 Nuke; broad six-map strength', 'Map pools are strategic portfolios'],
            ['Professional process', 'Analysts, psychology and structured preparation', 'Infrastructure is a competitive mechanic'],
          ],
          note: 'The first column is observable practice. The final column is the article’s interpretation of why it remained important.',
        },
        callout: 'Astralis’ greatest trick was making their innovation vanish into the definition of “fundamental Counter-Strike.”',
      },
    ],
    sources: [
      { label: 'HLTV — Astralis: A legend in the making', url: 'https://www.hltv.org/news/24545/astralis-a-legend-in-the-making', use: 'Utility ADR, opening allocation, 5v4 conversion, 4v5 recovery, support rates and map-pool statistics.' },
      { label: 'HLTV — Astralis’ Nuke: analysing the 26–0 streak', url: 'https://www.hltv.org/news/25528/astraliss-nuke-analyzing-the-26-0-streak', use: 'Role structure, rotations, CT/T round rates, pistols, force-buys and advantage conversion.' },
      { label: 'HLTV — Xyp9x on systematic double-HE practice', url: 'https://www.hltv.org/news/23626/xyp9x-thanks-to-zonic-its-become-a-thing-that-we-have-to-find-spots-we-can-double-nade', use: 'Contemporary account of zonic’s utility-development process.' },
      { label: 'HLTV — ENCE end the 31–0 Nuke streak', url: 'https://www.hltv.org/news/27539/the-headlines-of-2019-a-mid-season-recap', use: 'Completed Nuke LAN streak and its endpoint.' },
      { label: 'HLTV — A year at the summit', url: 'https://www.hltv.org/news/26664/a-year-at-the-summit-how-astralis-wrote-history', use: 'Map streaks, preparation infrastructure and evidence that rivals adopted comparable support systems.' },
      { label: 'HLTV — History of the competitive map pool', url: 'https://www.hltv.org/news/36574/the-history-of-csgos-competitive-map-pool', use: 'Nuke’s prior unpopularity and the Cobblestone-to-Dust2 change that removed Astralis’ permaban.' },
      { label: 'HLTV — gla1ve ranked eighth in 2018', url: 'https://www.hltv.org/news/25815/top-20-players-of-2018-gla1ve-8', use: 'gla1ve’s utility and flash-assist standing and the team-first role description.' },
      { label: 'HLTV — Astralis top team of 2018', url: 'https://www.hltv.org/news/25740/top-10-teams-of-2018', use: 'Season results and historical competitive context.' },
    ],
  },
  {
    slug: 'how-ropz-era-vitality-rebuilt-the-superteam',
    number: '031',
    title: 'How Vitality’s ropz Era Rebuilt the Superteam',
    shortTitle: 'Vitality’s modern superteam',
    dek: 'The roster did not dominate because it collected the five largest names. It dominated because one signing redistributed space, information and agency across every role.',
    verdict: 'Vitality’s innovation is architectural: stars without role collision.',
    verdictDetail: 'Vitality established the MR12 superteam blueprint: explicit roles, distributed mid-round authority and interchangeable closing power. Their stars amplify one another because the roster eliminates role collision.',
    readingMinutes: 18,
    publishedAt: '2026-08-29',
    dataCutoff: '29 August 2026',
    sample: 'The apEX–ZywOo–flameZ–mezii–ropz roster from January 2025 through August 2026, emphasizing the integration period, the seven-title/37-series 2025 peak, role interviews, 2025 player rankings and the subsequent adaptation cycle.',
    heroStats: [
      { value: '40.9→60.4%', label: 'Early T-side climb', detail: 'Bounty LAN to tournament-best at IEM Katowice 2025' },
      { value: '37', label: 'BO3/BO5 win streak', detail: 'The defining proof of repeatable mid-series adaptation' },
      { value: '4', label: 'Top-20 players', detail: '#1 ZywOo, #3 ropz, #7 flameZ, #12 mezii in 2025' },
      { value: '9 / 16', label: '2025 Big Events won', detail: 'With playoff appearances at all sixteen' },
    ],
    sections: [
      {
        number: '01',
        eyebrow: 'A different kind of influence',
        title: 'Vitality did not invent a new grenade. They solved the superteam coordination tax.',
        paragraphs: [
          'Counter-Strike history is full of rosters that won the announcement and lost the server. Adding another star creates more theoretical firepower, but also more players expecting the same safe spawn, the same rotation, the same late-round freedom and the same stream of resources. The coordination tax rises faster than the names on the poster.',
          'ropz replaced Spinx in January 2025. On paper, it was a premium one-for-one lurker upgrade. In practice, the move changed the geometry of the whole five. ropz could absorb difficult CT anchors while actively taking information from them; mezii moved toward more comfortable and active positions; flameZ retained aggressive space-taking; ZywOo remained the universal tactical release valve; apEX gained a second veteran voice whose preferred lurks could be integrated into the call rather than merely permitted after it.',
          'Vitality’s contribution is roster and tactical architecture rather than a wholly new style of Counter-Strike. Entry–support–lurk structure, active anchoring and shared mid-round calling already existed. Vitality combined them at record-setting scale and prevented a modern multi-star lineup from collapsing into role duplication.',
        ],
        callout: 'The lesson of Vitality’s ropz era is not “sign more stars.” It is “make every star increase someone else’s playable map.”',
      },
      {
        number: '02',
        eyebrow: 'The role cascade',
        title: 'One replacement altered four jobs because positions are a network, not a list.',
        paragraphs: [
          'On CT sides, ropz’s anchor strength allowed mezii to leave several low-agency holds and occupy more active positions. mezii described the value directly: an anchor willing to take space and make plays gives the rest of the defence options. That phrase matters. Traditional anchor is often treated as a synonym for passivity. ropz’s version secures the site while creating information early enough for the rotation to remain a choice.',
          'On T sides, apEX wanted ropz closer to the centre of the game than Spinx had been. The lurker was not instructed to wait for the four-player move to either succeed or fail. apEX adapted calls to ropz’s intended lurks and gave him a larger voice. A successful extremity could become the round’s main body; a contact seen by the defence could become deliberately false identity information.',
          'The cascade preserved distinct jobs. flameZ supplied pace and first contact. ZywOo could AWP, rifle, open or close without also having to manufacture every mid-round read. apEX remained the final caller but did not monopolise sensing. mezii became a flexible connector rather than a displaced anchor. ropz provided site stability, lurk initiative and late-round conversion. Five roles became clearer even as the team gained options.',
        ],
        table: {
          caption: 'Vitality’s ropz-era role network',
          headers: ['Player', 'Primary tactical responsibility', 'What the structure releases'],
          rows: [
            ['apEX', 'Tempo, first plan, final call', 'Can call around high-quality live information'],
            ['ropz', 'Active anchor, aggressive lurk, second voice', 'Frees mezii; gives T defaults an autonomous edge'],
            ['ZywOo', 'Universal star and AWP pressure', 'Can solve the highest-value state rather than every state'],
            ['flameZ', 'Space, entry pressure, defensive aggression', 'Creates rotation and trade opportunities'],
            ['mezii', 'Connector, rotation and adaptable site work', 'Moves toward active positions with less role friction'],
          ],
          note: 'Roles are analytical summaries, not fixed coordinates. Their value is in the dependencies between them.',
        },
      },
      {
        number: '03',
        eyebrow: 'From friction to fluency',
        title: 'A nineteen-point T-side jump shows how quickly structure can become executable.',
        paragraphs: [
          'The first weeks exposed the cost of integration. Vitality’s T-side round win rate was 46.5% in the online BLAST Bounty stage and 40.9% at the LAN Finals. At IEM Katowice it rose to a tournament-best 60.4%. The change from Bounty LAN to Katowice was 19.5 percentage points; from the online stage it was 13.9.',
          'The increase tracks the tactical installation of ropz’s role. CT positions transferred immediately; the T side required new timings between the extremity and the group. The early failure and rapid recovery show apEX learning when ropz’s extremity remained the threat, when the group paused for his information and when the lurk converted into the hit.',
          'Katowice supplied the first proof that this was more than a honeymoon. Vitality swept Spirit 3–0 in the final, ropz posted a 1.23 event rating, and the offence led the field. A superteam’s first meaningful innovation is often not a new play but a reduction in synchronization time. Vitality went from obvious T-side friction to the tournament’s best attacking rate within one major preparation cycle.',
        ],
        table: {
          caption: 'Early offensive integration, 2025',
          headers: ['Event phase', 'T-round win rate', 'Change from prior sample'],
          rows: [
            ['BLAST Bounty online', '46.5%', 'Starting point'],
            ['BLAST Bounty LAN Finals', '40.9%', '–5.6 pp'],
            ['IEM Katowice', '60.4%', '+19.5 pp'],
          ],
          note: 'Event fields and map distributions differ across the three periods; the table reports the team’s observed side-level change.',
        },
      },
      {
        number: '04',
        eyebrow: 'Distributed authority',
        title: 'apEX kept command by giving up the monopoly on ideas.',
        paragraphs: [
          'The usual caricature places structured teams and loose teams at opposite ends. Vitality show a more useful axis: who is authorised to change the plan, and on what evidence? apEX described retaining his identity and gut feeling while listening to how ropz wanted to play a lurk. That is not five players improvising independently. It is bounded autonomy inside a known decision hierarchy.',
          'ropz later praised apEX’s opponent reads and said the caller helped him reach peak form. The exchange works in both directions. The IGL supplies the global model—economy, opponent tendencies, intended finish. The lurker supplies high-resolution local information. ZywOo and flameZ supply contact-state information through the main group. The final call belongs to apEX, but the sensing layer is distributed.',
          'This arrangement matters in MR12 because there are fewer low-cost rounds in which a caller can test a hypothesis. A bad read represents a larger fraction of the half. The durable Vitality lesson is to separate command from observation: one person may own the decision without pretending to own all five views of the map.',
        ],
        stats: [
          { value: '1', label: 'Final caller', detail: 'apEX retains tactical identity and decision ownership' },
          { value: '5', label: 'Information sources', detail: 'Roles are expected to create and report actionable states' },
          { value: '12', label: 'Regulation rounds per half', detail: 'MR12 raises the cost of a slow or false read' },
        ],
        callout: 'Shared calling does not require ambiguous authority. Vitality distribute observation and preserve a decision owner.',
      },
      {
        number: '05',
        eyebrow: 'Identity as misinformation',
        title: 'Clear roles made their deviations more—not less—deceptive.',
        paragraphs: [
          'Traditional role structure appears anti-strattable because opponents know where the lurker, entry and anchor usually operate. ropz identified the countermeasure: teams can deliberately expose a player’s nickname in an unusual place, causing the defence to infer the familiar structure and rotate against a false picture.',
          'The tactic only works because identities have meaning. Seeing ropz on one extremity carries a stronger implied distribution than seeing an interchangeable rifler. Vitality can use that expectation as a resource—show the lurker with the group, leave an unexpected player behind, or let the familiar extremity contact occur earlier than its actual commitment.',
          'This is a subtle answer to a modern analytical environment. As demo preparation improves, complete randomness is not the only escape from predictability. A team can build a legible baseline and then price deviations from it. Role clarity becomes the prior that misinformation attacks.',
        ],
        table: {
          caption: 'Structured deception as a conditional system',
          headers: ['Observed cue', 'Defender’s likely prior', 'Vitality’s available deviation'],
          rows: [
            ['ropz seen alone', 'Classic late lurk / opposite-side pressure', 'Accelerate his side into the real finish'],
            ['ropz seen with group', 'Commitment is concentrated', 'Leave flameZ or mezii as the delayed edge'],
            ['flameZ early contact', 'Fast space-taking sequence', 'Pause and let extremity information mature'],
            ['ZywOo AWP shown', 'Respect the sightline and reroute', 'Use star gravity without demanding a kill'],
          ],
          note: 'These rows describe the decision logic implied by the role system, not a claim that every listed variation is a named Vitality set play.',
        },
      },
      {
        number: '06',
        eyebrow: 'Interchangeable win conditions',
        title: 'The second superstar did not reduce ZywOo. He reduced the number of rounds ZywOo had to rescue.',
        paragraphs: [
          'ZywOo remained the best player of 2025, but the statistical distribution around him changed the failure modes. ropz ranked third, flameZ seventh and mezii twelfth. Four top-20 players do not automatically constitute a system; here they occupied different phases of the round. flameZ could create the first displacement, ZywOo punish the highest-value duel, ropz close the broken geometry and mezii connect the defence.',
          'The 37-series best-of-three/best-of-five streak is the strongest evidence that the arrangement was robust rather than decorative. A long series repeatedly exposes the quiet player, the weak map and the single star having an ordinary day. Vitality survived because the identity of the decisive player could change while the roles stayed recognizable.',
          'At their eight-event peak, Vitality went 76–18 on maps, won seven events and beat MOUZ, Falcons and Spirit 14–0 in series. Against those challengers they were 34–10 on maps, a 77.3% rate. The roster architecture produced repeatable closure across opponents and formats, including the ordinary days when individual firepower did not erase every mistake.',
        ],
        table: {
          caption: 'Output depth and peak team conversion',
          headers: ['Measure', 'Observed result', 'Structural reading'],
          rows: [
            ['2025 Top 20', '#1 / #3 / #7 / #12', 'Four elite outputs in differentiated roles'],
            ['Peak event record', '7 titles in 8 LANs', '87.5% event conversion'],
            ['Peak map record', '76–18', '80.8% observed map win rate'],
            ['BO3/BO5 streak', '37 series', 'Repeated recovery across multi-map tests'],
            ['Series vs three challengers', '14–0', 'No nearest rival converted a series in the window'],
            ['Maps vs challengers', '34–10', '77.3% per-map control'],
          ],
          note: 'Peak records follow HLTV’s comparison window. The Top 20 positions cover the complete 2025 season.',
        },
      },
      {
        number: '07',
        eyebrow: 'The anti-meta cycle',
        title: 'Their decline and recovery are part of the tactical legacy, not an exception to it.',
        paragraphs: [
          'Vitality’s seven-title streak ended, MOUZ broke the 37-series run in Cologne, and four events passed without another trophy. Opponents gained a large shared demo set; repeated matchups exposed preferences; the same clear roles that accelerated integration supplied better anti-strat priors. Dominance creates its own data exhaust.',
          'That period prevents an inflated innovation claim. Vitality’s ropz-era roster did not discover an uncounterable formation. Their structure could become readable, and ropz himself acknowledged that fixed roles can make a team easier to prepare for. The answer was not to abandon the architecture. After meaningful practice time, Vitality won EPL Season 22 and then the Budapest Major, restoring confidence while keeping the same five.',
          'Vitality’s later recovery establishes the architecture’s durability. The stable baseline hosted new variations without requiring a roster change. Structure and adaptation reinforced one another because fixed responsibilities made the readable parts easier to diagnose and change.',
        ],
        callout: 'A tactical identity becomes historically serious when it can be countered, revised and made dangerous again without changing its five players.',
      },
      {
        number: '08',
        eyebrow: 'The permanent contribution',
        title: 'Vitality rewrote the construction rule for superteams.',
        paragraphs: [
          'Astralis left teams new round protocols. Vitality’s clearest legacy is a construction rule: evaluate a signing by the space it returns to the other four. ropz added his own rating, but his deeper value was multiplicative—more active CT positions for mezii, a more assertive T-side extremity for apEX, another closer beside ZywOo and a stable anchor behind flameZ’s aggression.',
          'Vitality established the standard for future superteams: stars occupy different temporal jobs. flameZ creates first displacement, ropz owns the extremity and low-contact site, mezii connects rotations, apEX converts distributed information into the final call, and ZywOo supplies universal finishing power. A roster that assigns three of those jobs to the same player has purchased names rather than a system.',
          'The blueprint proved itself through nine wins from 16 Big Events in 2025, playoffs at all 16, back-to-back Majors and four top-20 players without role collapse. Astralis changed round protocols; Vitality changed how elite organisations assemble multiple stars.',
        ],
        table: {
          caption: 'The modern superteam architecture established by Vitality',
          headers: ['Roster function', 'Vitality’s owner', 'Failure mode eliminated'],
          rows: [
            ['First contact', 'flameZ / situational ZywOo', 'Every star waiting for favourable information'],
            ['Extremity control', 'ropz with active autonomy', 'Passive lurk detached from the call'],
            ['Low-contact sites', 'ropz within a flexible CT network', 'A star demanding only rotation positions'],
            ['Rotation connection', 'mezii in more active roles', 'Role sacrifice suppressing the fourth player'],
            ['Final call', 'apEX, informed by distributed voices', 'Five competing mid-round plans'],
            ['Round closure', 'ZywOo or ropz, with wider support', 'Single-point superstar dependence'],
          ],
          note: 'The framework is derived from Vitality’s documented role changes and competitive results.',
        },
        callout: 'Vitality’s ropz-era superteam is not five players who can carry. It is five jobs arranged so that carrying one never prevents another from working.',
      },
    ],
    sources: [
      { label: 'HLTV — apEX on reshaping the team around ropz', url: 'https://www.hltv.org/news/40751/apex-ropz-will-have-a-bigger-voice-and-more-plays-than-what-spinx-had', use: 'Primary account of ropz’s larger voice, aggressive lurks and apEX adapting calls around them.' },
      { label: 'HLTV — mezii on the role changes created by ropz', url: 'https://www.hltv.org/news/40814/mezii-on-ropz-when-you-have-anchors-that-are-willing-to-take-space-and-make-plays-it-definitely-helps-a-team', use: 'Primary account of CT-position redistribution and active anchoring.' },
      { label: 'HLTV — Vitality win IEM Katowice 2025', url: 'https://www.hltv.org/news/40960/vitality-sweep-spirit-to-win-iem-katowice-2025', use: 'Early T-side progression, tournament-best 60.4% attacking rate and ropz event rating.' },
      { label: 'HLTV — ropz credits apEX’s reads', url: 'https://www.hltv.org/news/41213/ropz-apexs-calling-is-great-hes-reading-the-enemies-well', use: 'Primary account of the calling relationship and early map-pool confidence.' },
      { label: 'HLTV — ropz ranked third in 2025', url: 'https://www.hltv.org/news/43608/top-20-players-of-2025-ropz-3', use: 'Role architecture, structured deception, season arc and ropz’s individual impact.' },
      { label: 'HLTV — Vitality’s 2025 compared with prime Astralis', url: 'https://www.hltv.org/news/42253/how-does-vitalitys-season-compare-to-prime-astralis', use: 'Peak event, map and challenger records and MR12 context.' },
      { label: 'HLTV — MOUZ end the 37-series streak', url: 'https://www.hltv.org/news/42377/eighth-time-is-the-charm-as-mouz-beat-vitality-to-reach-cologne-final', use: 'Streak endpoint and evidence of recurring mid-series recovery before the loss.' },
      { label: 'HLTV — Top teams of 2025', url: 'https://www.hltv.org/news/43615/the-top-10-teams-of-2025', use: 'Nine titles, sixteen Big Events, complete playoff record and season-level context.' },
      { label: 'HLTV — 2025 player ranking', url: 'https://www.hltv.org/players/top20/2025', use: 'ZywOo, ropz, flameZ and mezii’s final individual rankings.' },
      { label: 'HLTV — Keep calm and carry on', url: 'https://www.hltv.org/news/42607/keep-calm-and-carry-on-vitality-do-not-need-to-panic', use: 'Post-streak adaptation context and limits of the initial dominance.' },
    ],
  },
];
