import { Thought } from './thought';

// These opening pieces establish the publication's voice and structure. They
// are intentionally marked as evolving notes and can be replaced as the real
// body of writing grows.
export const THOUGHTS: readonly Thought[] = [
  {
    number: '001',
    slug: 'observability-is-an-editorial-act',
    title: 'Observability is an editorial act',
    dek: 'Every dashboard is an argument about what matters, what can be ignored, and what deserves an alarm.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Systems', 'Operations', 'Legibility'],
    thesis: 'A monitoring system does not simply reveal reality. It edits reality into a form an organization is prepared to see.',
    body: [
      'Observability is usually described as a property of software: the ability to infer internal state from external outputs. That definition is useful, but incomplete. Before a signal reaches a person it has already passed through instrumentation choices, sampling rules, storage limits, aggregation windows, dashboard layouts, thresholds, and naming conventions.',
      'Each choice removes information. This is not a failure; useful interfaces must compress. The problem begins when compression is mistaken for neutrality. A green dashboard does not mean a system is healthy. It means the conditions represented by that dashboard have not crossed the boundaries someone chose.',
      'The most consequential observability work therefore happens before a chart is drawn. Teams decide whose experience counts as failure, which delays are acceptable, which dependencies deserve independent visibility, and how uncertainty should appear. Those are editorial decisions expressed through technical machinery.',
      'A better review of an operational dashboard would ask the same questions asked of a piece of writing: Who is the audience? What has been left out? What claim is this arrangement making? What would contradict it? The goal is not a complete picture. The goal is an honest one.',
    ],
    related: ['automation-should-reduce-ambiguity', 'interfaces-are-part-of-the-architecture'],
    featured: true,
  },
  {
    number: '002',
    slug: 'interfaces-are-part-of-the-architecture',
    title: 'The interface is part of the architecture',
    dek: 'Defaults, error messages, and naming schemes shape a system as surely as queues, databases, and network boundaries.',
    kind: 'Note',
    state: 'Working',
    publishedAt: '2026-08-24',
    updatedAt: '2026-08-27',
    readingMinutes: 4,
    themes: ['Architecture', 'Interfaces', 'Systems'],
    thesis: 'Architecture is not only the arrangement of components. It is also the set of ideas a system makes easy or difficult to express.',
    body: [
      'Architecture diagrams tend to stop at the service boundary. They show calls, stores, streams, and zones of responsibility. The experience of using those components is treated as a later concern, even though that experience determines whether the architecture is followed or quietly bypassed.',
      'A difficult API produces local wrappers. An ambiguous deployment model produces undocumented conventions. A poor failure message creates a parallel support system made from chat history and institutional memory. These adaptations become part of the real architecture whether or not the diagram acknowledges them.',
      'This suggests a useful test: if the intended path through a system is not also the clearest path, the architecture is unfinished. Interfaces are where structural decisions become behavioral defaults.',
    ],
    related: ['configuration-is-a-debt-instrument', 'observability-is-an-editorial-act'],
  },
  {
    number: '003',
    slug: 'automation-should-reduce-ambiguity',
    title: 'Automation should reduce ambiguity, not only effort',
    dek: 'The best automation leaves the state of the world clearer than it found it.',
    kind: 'Model',
    state: 'Revisited',
    publishedAt: '2026-08-18',
    updatedAt: '2026-08-26',
    readingMinutes: 5,
    themes: ['Automation', 'Operations', 'Legibility'],
    thesis: 'Time saved is a weak measure of automation. A stronger measure is how much uncertainty remains when the automation stops.',
    body: [
      'Many automated workflows are evaluated by the manual steps they remove. This catches obvious value but misses a more durable effect: whether the workflow produces a state that people can inspect, explain, and recover.',
      'An opaque script may save ten minutes and create an hour of uncertainty when it fails. A slower process that emits a plan, records its decisions, identifies ownership, and exposes a safe recovery path often creates more organizational capacity.',
      'The model is simple: useful automation should reduce effort, reduce ambiguity, or preferably both. If it reduces effort while increasing ambiguity, the saved time is being borrowed from the next incident.',
      'This reframes logs, previews, idempotency, and dry runs. They are not secondary conveniences. They are the means by which automated action remains legible to the humans responsible for its consequences.',
    ],
    related: ['observability-is-an-editorial-act', 'the-queue-is-the-product'],
  },
  {
    number: '004',
    slug: 'configuration-is-a-debt-instrument',
    title: 'Configuration is a debt instrument',
    dek: 'Every option postpones a decision and transfers its cost to every future operator.',
    kind: 'Note',
    state: 'Working',
    publishedAt: '2026-08-11',
    updatedAt: '2026-08-21',
    readingMinutes: 4,
    themes: ['Architecture', 'Complexity', 'Design'],
    thesis: 'Configurability is valuable when variation is real. Everywhere else it is deferred design work accruing interest.',
    body: [
      'Configuration feels safe because it avoids closing a door. A value can be tuned later, a policy can vary between environments, and an uncertain decision can be moved into a file. The immediate implementation becomes more flexible and the design conversation can end.',
      'But the decision has not disappeared. It has been distributed to every deployment, test suite, operator, upgrade path, and support conversation. Each option creates combinations; each combination asks whether it is valid, documented, observable, and still supported.',
      'The question is not whether software should be configurable. It is whether the variation represents a genuine difference in context or an unwillingness to choose. Good defaults pay down uncertainty. Unbounded options capitalize it.',
    ],
    related: ['interfaces-are-part-of-the-architecture', 'what-deserves-to-become-a-platform'],
  },
  {
    number: '005',
    slug: 'small-tools-have-long-half-lives',
    title: 'Small tools have long half-lives',
    dek: 'A narrow tool can survive because it asks very little from the future.',
    kind: 'Note',
    state: 'Spark',
    publishedAt: '2026-08-03',
    updatedAt: '2026-08-03',
    readingMinutes: 2,
    themes: ['Tools', 'Maintenance', 'Design'],
    thesis: 'Longevity often comes from having fewer reasons to change, not from having more capacity to change.',
    body: [
      'The tools that remain useful for years are often unimpressive on first inspection. They accept a clear input, perform one transformation, and leave behind an artifact that another tool can understand.',
      'Large platforms survive through continuous investment. Small tools sometimes survive through indifference: protocols remain stable, dependencies are few, and the problem retains its shape. Their restraint is a maintenance strategy.',
      'There is a design lesson here. Extensibility is not the only route to a long life. A small and explicit boundary may be the more generous gift to whoever encounters the software next.',
    ],
    related: ['configuration-is-a-debt-instrument'],
  },
  {
    number: '006',
    slug: 'ai-systems-need-visible-seams',
    title: 'AI systems need visible seams',
    dek: 'Uncertainty becomes dangerous when an interface edits it out before a person can respond.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-07-27',
    updatedAt: '2026-08-20',
    readingMinutes: 7,
    themes: ['AI', 'Interfaces', 'Trust'],
    thesis: 'A trustworthy AI interface should expose the boundary between retrieved fact, generated interpretation, and unresolved uncertainty.',
    body: [
      'Seamless software has long been treated as a mark of quality. Transitions disappear, complexity recedes, and the user is allowed to focus on a goal. Applied to probabilistic systems, that instinct can become misleading. A polished answer may conceal several qualitatively different operations behind one confident surface.',
      'Retrieved evidence, deterministic calculation, model inference, and invented connective language do not deserve identical visual treatment. When an interface flattens them into a single voice, it also removes the cues a person needs to calibrate trust.',
      'Visible seams do not require flooding the screen with implementation detail. They can be expressed through provenance, confidence ranges, explicit assumptions, reversible actions, and clear boundaries around what the system did not establish.',
      'The goal is not to make AI feel unreliable. It is to make reliability inspectable. A system earns trust when it gives people enough structure to disagree with it well.',
    ],
    related: ['interfaces-are-part-of-the-architecture', 'observability-is-an-editorial-act'],
  },
  {
    number: '007',
    slug: 'what-deserves-to-become-a-platform',
    title: 'What deserves to become a platform?',
    dek: 'When does repeated work indicate a shared foundation—and when is a platform merely premature centralization?',
    kind: 'Question',
    state: 'Spark',
    publishedAt: '2026-07-19',
    updatedAt: '2026-07-19',
    readingMinutes: 3,
    themes: ['Platforms', 'Organizations', 'Architecture'],
    thesis: 'A platform should emerge from stable, repeated needs—not from the visual similarity of several unfinished solutions.',
    body: [
      'Repeated work creates a strong temptation to centralize. Three teams have pipelines, templates, authentication layers, or deployment scripts; therefore one platform should own the shared problem. Sometimes this is exactly right. Sometimes the repetition is only superficial.',
      'A platform freezes a theory of what its users have in common. If that theory is premature, variation does not disappear—it returns as exceptions, escape hatches, wrappers, and political negotiation.',
      'What evidence should exist before platformization? Stable language may matter more than repeated code. Voluntary convergence may matter more than executive sponsorship. The best early signal might be that teams have independently started solving the same boundary, not merely using similar tools.',
    ],
    related: ['configuration-is-a-debt-instrument', 'interfaces-are-part-of-the-architecture'],
  },
  {
    number: '008',
    slug: 'the-queue-is-the-product',
    title: 'The queue is the product',
    dek: 'A system that accepts more work than it can complete is defined by how it explains waiting.',
    kind: 'Model',
    state: 'Working',
    publishedAt: '2026-07-08',
    updatedAt: '2026-08-09',
    readingMinutes: 5,
    themes: ['Systems', 'Operations', 'Organizations'],
    thesis: 'When demand exceeds capacity, the ordering, visibility, and ownership of waiting become the system’s real interface.',
    body: [
      'Queues are often introduced as implementation details: buffers that absorb uneven work and allow components to proceed independently. At human scale the same structure appears as a backlog, approval list, support inbox, project pipeline, or hiring process.',
      'In each case, the visible service is only half the product. The rest is the experience of waiting: whether position is knowable, priorities are explainable, abandonment is possible, and responsibility remains attached to an item while nothing appears to happen.',
      'An invisible queue converts capacity limits into personal uncertainty. A legible queue turns them into a shared constraint that can be discussed and changed. Throughput still matters, but so do admission, ordering, expiry, and explanation.',
      'This is why adding intake without designing the queue is not an expansion of service. It is an expansion of ambiguity.',
    ],
    related: ['automation-should-reduce-ambiguity', 'observability-is-an-editorial-act'],
  },
];

