import { Thought } from './thought';

// This file is the publication desk. Pieces remain editable after publication;
// dates and maturity states make that continuing work visible.
export const THOUGHTS: readonly Thought[] = [
  {
    number: '001',
    slug: 'observability-is-an-editorial-act',
    title: 'Observability is an editorial act',
    dek: 'Every dashboard is an argument about what matters, what can be ignored, and what deserves an alarm.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Systems', 'Operations', 'Legibility'],
    thesis: 'A monitoring system does not simply reveal reality. It edits reality into a form an organization is prepared to see.',
    body: [
      'Observability is usually described as a property of software: the ability to infer internal state from external outputs. That definition is useful, but incomplete. Before a signal reaches a person it has already passed through instrumentation choices, sampling rules, storage limits, aggregation windows, dashboard layouts, thresholds, and naming conventions.',
      'Each choice removes information. This is not a failure; useful interfaces must compress. The problem begins when compression is mistaken for neutrality. A green dashboard does not mean a system is healthy. It means the conditions represented by that dashboard have not crossed the boundaries someone chose.',
      'The most consequential observability work therefore happens before a chart is drawn. Teams decide whose experience counts as failure, which delays are acceptable, which dependencies deserve independent visibility, and how uncertainty should appear. Those are editorial decisions expressed through technical machinery.',
      'A better review of an operational dashboard would ask the same questions asked of a piece of writing: Who is the audience? What has been left out? What claim is this arrangement making? What would contradict it? The goal is not a complete picture. The goal is an honest one.',
    ],
    related: ['automation-should-reduce-ambiguity', 'interfaces-are-part-of-the-architecture'],
  },
  {
    number: '002',
    slug: 'interfaces-are-part-of-the-architecture',
    title: 'The interface is part of the architecture',
    dek: 'Defaults, error messages, and naming schemes shape a system as surely as queues, databases, and network boundaries.',
    kind: 'Note',
    state: 'Working',
    publishedAt: '2026-08-24',
    updatedAt: '2026-08-27',
    readingMinutes: 4,
    themes: ['Architecture', 'Interfaces', 'Systems'],
    thesis: 'Architecture is not only the arrangement of components. It is also the set of ideas a system makes easy or difficult to express.',
    body: [
      'Architecture diagrams tend to stop at the service boundary. They show calls, stores, streams, and zones of responsibility. The experience of using those components is treated as a later concern, even though that experience determines whether the architecture is followed or quietly bypassed.',
      'A difficult API produces local wrappers. An ambiguous deployment model produces undocumented conventions. A poor failure message creates a parallel support system made from chat history and institutional memory. These adaptations become part of the real architecture whether or not the diagram acknowledges them.',
      'This suggests a useful test: if the intended path through a system is not also the clearest path, the architecture is unfinished. Interfaces are where structural decisions become behavioral defaults.',
    ],
    related: ['configuration-is-a-debt-instrument', 'observability-is-an-editorial-act'],
  },
  {
    number: '003',
    slug: 'automation-should-reduce-ambiguity',
    title: 'Automation should reduce ambiguity, not only effort',
    dek: 'The best automation leaves the state of the world clearer than it found it.',
    kind: 'Model',
    state: 'Revisited',
    publishedAt: '2026-08-18',
    updatedAt: '2026-08-26',
    readingMinutes: 5,
    themes: ['Automation', 'Operations', 'Legibility'],
    thesis: 'Time saved is a weak measure of automation. A stronger measure is how much uncertainty remains when the automation stops.',
    body: [
      'Many automated workflows are evaluated by the manual steps they remove. This catches obvious value but misses a more durable effect: whether the workflow produces a state that people can inspect, explain, and recover.',
      'An opaque script may save ten minutes and create an hour of uncertainty when it fails. A slower process that emits a plan, records its decisions, identifies ownership, and exposes a safe recovery path often creates more organizational capacity.',
      'The model is simple: useful automation should reduce effort, reduce ambiguity, or preferably both. If it reduces effort while increasing ambiguity, the saved time is being borrowed from the next incident.',
      'This reframes logs, previews, idempotency, and dry runs. They are not secondary conveniences. They are the means by which automated action remains legible to the humans responsible for its consequences.',
    ],
    related: ['observability-is-an-editorial-act', 'the-queue-is-the-product'],
  },
  {
    number: '004',
    slug: 'configuration-is-a-debt-instrument',
    title: 'Configuration is a debt instrument',
    dek: 'Every option postpones a decision and transfers its cost to every future operator.',
    kind: 'Note',
    state: 'Working',
    publishedAt: '2026-08-11',
    updatedAt: '2026-08-21',
    readingMinutes: 4,
    themes: ['Architecture', 'Complexity', 'Design'],
    thesis: 'Configurability is valuable when variation is real. Everywhere else it is deferred design work accruing interest.',
    body: [
      'Configuration feels safe because it avoids closing a door. A value can be tuned later, a policy can vary between environments, and an uncertain decision can be moved into a file. The immediate implementation becomes more flexible and the design conversation can end.',
      'But the decision has not disappeared. It has been distributed to every deployment, test suite, operator, upgrade path, and support conversation. Each option creates combinations; each combination asks whether it is valid, documented, observable, and still supported.',
      'The question is not whether software should be configurable. It is whether the variation represents a genuine difference in context or an unwillingness to choose. Good defaults pay down uncertainty. Unbounded options capitalize it.',
    ],
    related: ['interfaces-are-part-of-the-architecture', 'what-deserves-to-become-a-platform'],
  },
  {
    number: '005',
    slug: 'small-tools-have-long-half-lives',
    title: 'Small tools have long half-lives',
    dek: 'A narrow tool can survive because it asks very little from the future.',
    kind: 'Note',
    state: 'Spark',
    publishedAt: '2026-08-03',
    updatedAt: '2026-08-03',
    readingMinutes: 2,
    themes: ['Tools', 'Maintenance', 'Design'],
    thesis: 'Longevity often comes from having fewer reasons to change, not from having more capacity to change.',
    body: [
      'The tools that remain useful for years are often unimpressive on first inspection. They accept a clear input, perform one transformation, and leave behind an artifact that another tool can understand.',
      'Large platforms survive through continuous investment. Small tools sometimes survive through indifference: protocols remain stable, dependencies are few, and the problem retains its shape. Their restraint is a maintenance strategy.',
      'There is a design lesson here. Extensibility is not the only route to a long life. A small and explicit boundary may be the more generous gift to whoever encounters the software next.',
    ],
    related: ['configuration-is-a-debt-instrument'],
  },
  {
    number: '006',
    slug: 'ai-systems-need-visible-seams',
    title: 'AI systems need visible seams',
    dek: 'Uncertainty becomes dangerous when an interface edits it out before a person can respond.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-07-27',
    updatedAt: '2026-08-20',
    readingMinutes: 7,
    themes: ['AI', 'Interfaces', 'Trust'],
    thesis: 'A trustworthy AI interface should expose the boundary between retrieved fact, generated interpretation, and unresolved uncertainty.',
    body: [
      'Seamless software has long been treated as a mark of quality. Transitions disappear, complexity recedes, and the user is allowed to focus on a goal. Applied to probabilistic systems, that instinct can become misleading. A polished answer may conceal several qualitatively different operations behind one confident surface.',
      'Retrieved evidence, deterministic calculation, model inference, and invented connective language do not deserve identical visual treatment. When an interface flattens them into a single voice, it also removes the cues a person needs to calibrate trust.',
      'Visible seams do not require flooding the screen with implementation detail. They can be expressed through provenance, confidence ranges, explicit assumptions, reversible actions, and clear boundaries around what the system did not establish.',
      'The goal is not to make AI feel unreliable. It is to make reliability inspectable. A system earns trust when it gives people enough structure to disagree with it well.',
    ],
    related: ['interfaces-are-part-of-the-architecture', 'observability-is-an-editorial-act'],
  },
  {
    number: '007',
    slug: 'what-deserves-to-become-a-platform',
    title: 'What deserves to become a platform?',
    dek: 'When does repeated work indicate a shared foundation—and when is a platform merely premature centralization?',
    kind: 'Question',
    state: 'Spark',
    publishedAt: '2026-07-19',
    updatedAt: '2026-07-19',
    readingMinutes: 3,
    themes: ['Platforms', 'Organizations', 'Architecture'],
    thesis: 'A platform should emerge from stable, repeated needs—not from the visual similarity of several unfinished solutions.',
    body: [
      'Repeated work creates a strong temptation to centralize. Three teams have pipelines, templates, authentication layers, or deployment scripts; therefore one platform should own the shared problem. Sometimes this is exactly right. Sometimes the repetition is only superficial.',
      'A platform freezes a theory of what its users have in common. If that theory is premature, variation does not disappear—it returns as exceptions, escape hatches, wrappers, and political negotiation.',
      'What evidence should exist before platformization? Stable language may matter more than repeated code. Voluntary convergence may matter more than executive sponsorship. The best early signal might be that teams have independently started solving the same boundary, not merely using similar tools.',
    ],
    related: ['configuration-is-a-debt-instrument', 'interfaces-are-part-of-the-architecture'],
  },
  {
    number: '008',
    slug: 'the-queue-is-the-product',
    title: 'The queue is the product',
    dek: 'A system that accepts more work than it can complete is defined by how it explains waiting.',
    kind: 'Model',
    state: 'Working',
    publishedAt: '2026-07-08',
    updatedAt: '2026-08-09',
    readingMinutes: 5,
    themes: ['Systems', 'Operations', 'Organizations'],
    thesis: 'When demand exceeds capacity, the ordering, visibility, and ownership of waiting become the system’s real interface.',
    body: [
      'Queues are often introduced as implementation details: buffers that absorb uneven work and allow components to proceed independently. At human scale the same structure appears as a backlog, approval list, support inbox, project pipeline, or hiring process.',
      'In each case, the visible service is only half the product. The rest is the experience of waiting: whether position is knowable, priorities are explainable, abandonment is possible, and responsibility remains attached to an item while nothing appears to happen.',
      'An invisible queue converts capacity limits into personal uncertainty. A legible queue turns them into a shared constraint that can be discussed and changed. Throughput still matters, but so do admission, ordering, expiry, and explanation.',
      'This is why adding intake without designing the queue is not an expansion of service. It is an expansion of ambiguity.',
    ],
    related: ['automation-should-reduce-ambiguity', 'observability-is-an-editorial-act'],
  },
  {
    number: '009',
    slug: 'software-simplified-technical-english',
    title: 'Software Simplified Technical English',
    dek: 'A controlled-English standard for making software work easier to read, execute, review, and maintain.',
    kind: 'Standard',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 5,
    themes: ['Language', 'Standards', 'Legibility', 'Writing'],
    thesis: 'Software documentation improves when important instructions use a deliberately limited language instead of relying on individual style and interpretation.',
    body: [
      'Software work is carried by language long before it is carried by code. Requirements define what should exist. Architecture decisions explain why one path was chosen. Runbooks tell a tired person what to do while something is broken. Tickets, comments, reviews, and incident updates all attempt to move an idea from one mind into another without losing its meaning.',
      'Software Simplified Technical English, or SSTE, treats that transfer as an engineering problem. It is a controlled-English standard for software development, delivery, operations, and work tracking. Its rules restrict avoidable ambiguity and encourage instructions whose actor, action, object, conditions, and expected result can be identified without guesswork.',
      'The intention is not to make every sentence sound mechanical. Controlled language is most valuable where interpretation has a cost: procedures, requirements, safety boundaries, operational changes, and records that must outlive their original author. A small loss of stylistic freedom can purchase a large increase in repeatability.',
      'SSTE also makes conformance explicit. A document can name an edition, profile, and level rather than claiming to be generically clear. That turns clarity from a preference into something a team can inspect, discuss, and improve. The standard is published openly so that its own language and assumptions can receive the same scrutiny it asks of software documentation.',
    ],
    references: [
      { label: 'SSTE repository and publication source', url: 'https://github.com/Reason0x6/SSTE' },
      { label: 'SSTE 1.0 normative specification', url: 'https://github.com/Reason0x6/SSTE/blob/main/SSTE-1.0.md' },
    ],
    related: ['observability-is-an-editorial-act', 'interfaces-are-part-of-the-architecture'],
  },
  {
    number: '010',
    slug: 'why-chess-feels-honest',
    title: 'Why chess feels honest',
    dek: 'The board remembers every decision, including the ones we have already explained away to ourselves.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Chess', 'Games', 'Judgment'],
    thesis: 'Chess feels honest because intention carries no special weight: the position records what a decision actually made possible.',
    body: [
      'Most decisions arrive wrapped in context. A poor result can be blamed on timing, incomplete information, competing priorities, or another person who failed to understand the plan. Sometimes those explanations are true. They are also comfortable places to hide. Chess offers fewer of them. The pieces remain where we put them, and the board does not remember what we meant.',
      'That does not make chess perfectly fair. Players differ in experience, energy, preparation, temperament, and time. Luck enters through the opponent we meet and the position we happen to know. But once a game begins, consequence is unusually visible. A neglected square becomes a route of entry. A casual pawn move remains unavailable in reverse. The position is an accumulating record of judgment.',
      'The honesty is not that every mistake is immediately punished. Many are not. It is that a mistake changes what can happen next. We may survive it, disguise it, or receive a second chance, but we do not get the original position back. This is a more useful model of consequence than simple reward and punishment. Decisions reshape the future before they produce a result.',
      'Chess is therefore at its most revealing after the game, when certainty becomes cheap. With the answer visible, every missed tactic looks obvious. Honest analysis requires recovering the uncertainty of the moment: what was seen, what was ignored, and which story made the wrong move feel right. The lesson is not that mistakes should be embarrassing. It is that explanations should remain accountable to the board.',
    ],
    related: ['small-engines-strange-intelligence', 'the-aesthetics-of-constraint', 'against-having-a-take-on-everything'],
    featured: true,
  },
  {
    number: '011',
    slug: 'small-engines-strange-intelligence',
    title: 'Small engines, strange intelligence',
    dek: 'A tiny chess bot reveals how much apparent intelligence can emerge from an argument about what deserves a score.',
    kind: 'Essay',
    state: 'Revisited',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 7,
    themes: ['Chess', 'Games', 'Intelligence', 'Constraints'],
    thesis: 'Building a small chess engine makes intelligence look less like a hidden substance and more like search directed by carefully chosen values.',
    body: [
      'A chess engine can appear to understand a position it has never encountered. It gives up material for activity, refuses an attractive attack, or finds a defensive move that changes the character of the game. The temptation is to imagine a compact strategist somewhere inside the program. Building even a small engine replaces that image with something stranger.',
      'The engine searches possible continuations, but search alone is not enough. The game expands too quickly. It must abandon most futures before seeing where they end, which means it needs an evaluation: a rough claim about which positions are worth pursuing. Material, mobility, king safety, pawn structure, and initiative become numbers that can be compared even though their value changes with context.',
      'That evaluation is a compressed theory of chess. Every weight says that one feature is worth some fraction of another. Every pruning decision says that a branch is unlikely to contain a surprise important enough to justify attention. The engine looks intelligent where those approximations align with the position and becomes alien where the compression loses something essential.',
      'Working within a tiny implementation budget makes the trade visible. There is never enough room for every refinement, so representation becomes strategy. A better search may matter less than a better question; another tactical layer may matter less than recognizing when the king is exposed. Intelligence begins to resemble the allocation of scarce attention under an imperfect value system—which is not an entirely foreign description of human thought.',
    ],
    references: [
      { label: 'Tiny Chess Bot — source repository', url: 'https://github.com/Reason0x6/Chess-Challenge' },
    ],
    related: ['why-chess-feels-honest', 'ai-systems-need-visible-seams', 'the-aesthetics-of-constraint'],
  },
  {
    number: '012',
    slug: 'the-aesthetics-of-constraint',
    title: 'The aesthetics of constraint',
    dek: 'A closed door can give a piece of work the shape that unlimited possibility never would.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Constraints', 'Design', 'Art', 'Making'],
    thesis: 'Constraints become aesthetically productive when they force a work to develop a coherent answer instead of postponing every decision.',
    body: [
      'Freedom is pleasant at the beginning and exhausting shortly after. An empty page permits every form, voice, color, length, and subject. Nothing resists, which means nothing helps. The work must generate both the question and the conditions under which an answer will count.',
      'A constraint changes the relationship. A fixed size, restricted vocabulary, limited palette, short runtime, or unforgiving material removes possibilities before taste has to evaluate them. The remaining decisions gain weight. Repetition becomes visible. Variations become meaningful because they occur against a boundary the audience can feel.',
      'The useful constraint is not merely an inconvenience. It enters the character of the work. A sonnet is not prose damaged by a line count. Pixel art is not painting awaiting more resolution. A small chess engine is not only a large engine missing features. In each case, limitation creates a different field of expression and rewards a different kind of intelligence.',
      'Constraints fail when they are arbitrary theatre or when they protect a weak decision from criticism. Their value is not difficulty for its own sake. It is the pressure to choose. A good limit closes enough doors that the work can stop negotiating with every possible version of itself and finally become one thing.',
    ],
    related: ['small-engines-strange-intelligence', 'mechanical-keyboards-as-folk-engineering', 'a-hobby-should-be-allowed-to-be-useless'],
  },
  {
    number: '013',
    slug: 'a-hobby-should-be-allowed-to-be-useless',
    title: 'A hobby should be allowed to be useless',
    dek: 'Not every sustained interest needs to become income, expertise, identity, or material for an audience.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Hobbies', 'Attention', 'Culture'],
    thesis: 'A hobby protects a kind of freedom that disappears when enjoyment must justify itself through output, improvement, or recognition.',
    body: [
      'A new interest now arrives with a ready-made career path. Enjoy cooking and there is a channel to start. Learn an instrument and there are progress clips to publish. Collect, paint, play, repair, or read for long enough and someone will suggest a store, a brand, a course, or a more disciplined practice. The compliment carries a demand: this pleasure could become productive.',
      'Productivity is not the enemy of enjoyment. Skill is satisfying, sharing can deepen an interest, and some livelihoods begin as play. The problem is the disappearance of an outside. When every activity is evaluated as a possible asset, leisure inherits the anxieties of work: consistency, differentiation, growth, and the suspicion that an unrecorded hour has been wasted.',
      'A useless hobby is useful precisely because its value remains local. It can be abandoned for months, pursued badly, repeated without improvement, and changed without explanation. There is no audience whose expectations must be managed. Curiosity can move at the speed of appetite instead of a publishing schedule.',
      'Protecting uselessness is not a rejection of ambition. It is a refusal to make ambition the price of attention. Some practices should be allowed to end with the person doing them: one game played, one object repaired, one afternoon pleasantly spent, and no evidence required.',
    ],
    related: ['the-quiet-value-of-abandoned-projects', 'the-internet-needs-more-small-rooms', 'the-soundtrack-changes-the-work'],
  },
  {
    number: '014',
    slug: 'taste-is-a-compression-algorithm',
    title: 'Taste is a compression algorithm',
    dek: 'Preference lets us move through more possibility than explicit reasoning could ever evaluate.',
    kind: 'Model',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Taste', 'Judgment', 'Culture'],
    thesis: 'Taste compresses accumulated experience into fast judgments, preserving useful patterns while hiding much of the reasoning that produced them.',
    body: [
      'There are too many possible books, songs, typefaces, moves, tools, and ways to arrange a room for each choice to begin from first principles. Explicit comparison is expensive. Taste makes abundance navigable by turning a history of encounters into a feeling: this belongs, this does not, this is worth another look.',
      'Calling taste subjective is true but incomplete. It is subjective in the way a trained model is shaped by its data. Exposure, imitation, social class, subculture, memory, and repeated attention all influence the result. The judgment feels immediate because the intermediate steps have been compressed, not because they never existed.',
      'Compression preserves patterns by discarding detail. That is why taste can be both perceptive and unfair. It notices a familiar false note before conscious analysis catches up, but it can also reject work that uses a language it has not learned. Confidence may indicate a deep pattern or merely a well-rehearsed preference.',
      'Good taste therefore needs two opposing practices: cultivation and interruption. Cultivation builds a richer internal library through close attention. Interruption asks when the shortcut has become a fence. The purpose is not to eliminate preference. It is to know when a fast judgment deserves trust and when the unfamiliar deserves more time.',
    ],
    related: ['against-having-a-take-on-everything', 'everything-eventually-gets-called-content', 'the-soundtrack-changes-the-work'],
  },
  {
    number: '015',
    slug: 'the-internet-needs-more-small-rooms',
    title: 'The internet needs more small rooms',
    dek: 'Not every conversation improves when it becomes searchable, scalable, permanent, and available to everyone at once.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 7,
    themes: ['Internet', 'Communities', 'Culture'],
    thesis: 'Healthy online culture depends on spaces small enough to develop context, memory, and norms that are not optimized for universal reach.',
    body: [
      'The dominant architecture of the internet is the room with no walls. A remark can leave its original audience instantly, appear beside strangers who share none of its context, and be judged as though it were addressed to everyone. Visibility is treated as opportunity, so the machinery keeps opening doors.',
      'Small rooms behave differently. A forum with regular names, a private group, a personal site with a modest readership, or a niche community can accumulate memory. People learn which disagreements are recurring, who is joking, what has already been tried, and which forms of behavior make the room worse. Context becomes part of the infrastructure.',
      'Smallness does not guarantee kindness. Closed spaces can become insular, coercive, or confidently wrong. But scale has pathologies too: performance replaces conversation, moderation becomes industrial, and every statement must survive contact with the least charitable possible audience. The absence of boundaries is not neutrality.',
      'The goal is not to retreat from public life. It is to restore a varied ecology of publics: some permanent, some temporary, some searchable, some deliberately obscure. A good internet should contain plazas, libraries, workshops, clubs, kitchens, and quiet tables. We have built enough stadiums.',
    ],
    related: ['everything-eventually-gets-called-content', 'a-hobby-should-be-allowed-to-be-useless', 'what-an-archive-chooses-to-forget'],
  },
  {
    number: '016',
    slug: 'everything-eventually-gets-called-content',
    title: 'Everything eventually gets called content',
    dek: 'The word makes essays, reporting, jokes, art, instruction, and confession look like interchangeable units of supply.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Media', 'Language', 'Culture'],
    thesis: 'Calling every cultural object content describes its usefulness to a distribution system while concealing the distinct purposes for which it was made.',
    body: [
      'Content is an admirably efficient word. It can refer to a film, a product review, a photograph, a political argument, a live stream, a tutorial, or a stranger describing the worst day of their life. The category asks only whether something can occupy a container and hold attention long enough to be distributed.',
      'From the platform’s perspective this flattening is practical. Different forms become comparable through impressions, completion, retention, and conversion. But the language escapes the dashboard. Makers begin to describe their own work as a supply to be maintained. Audiences learn to approach every encounter as another item in an infinite queue.',
      'The loss is not prestige. A joke does not need to be elevated into Art, and an ordinary explanation can matter more than a novel. What disappears is purpose. Reporting asks to be trusted in a different way from fiction. A diary entry has a different relationship to its audience than an advertisement. Treating them as one substance makes those obligations harder to see.',
      'Better nouns restore useful distinctions. Essay, conversation, documentation, criticism, performance, record, and story tell us something about the object and how to meet it. Content tells us that the slot has been filled. A culture becomes thinner when its most common word for expression belongs to the container rather than the thing expressed.',
    ],
    related: ['the-internet-needs-more-small-rooms', 'taste-is-a-compression-algorithm', 'against-having-a-take-on-everything'],
  },
  {
    number: '017',
    slug: 'owning-books-you-have-not-read',
    title: 'Owning books you have not read',
    dek: 'An unread shelf can be a map of possible attention rather than an accusation made from paper.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Books', 'Knowledge', 'Attention'],
    thesis: 'A personal library is valuable not only as a record of completed reading but as a visible arrangement of questions one may someday choose to follow.',
    body: [
      'Unread books have a talent for becoming moral objects. They sit in view as evidence of ambition outrunning discipline: money spent, intentions deferred, spines still unbroken. A sufficiently large shelf can feel less like a library than a queue whose service rate is obviously inadequate.',
      'That interpretation borrows the logic of completion. If possession creates an obligation, then reading is the task that clears the inventory. But books are not tickets, and a library need not be a record of finished work. It can also be an environment designed to make certain encounters more likely.',
      'An unread book keeps a question physically available. Years after it was acquired, a conversation or experience can suddenly reveal why it belongs nearby. The distance between interest and attention collapses: the book can be opened immediately, followed through its references, or placed beside another work that changes its meaning.',
      'This does not justify indiscriminate accumulation. A useful library still requires curation, space, memory, and occasional release. The better measure is not the percentage completed but the quality of possibility the collection creates. The unread shelf should invite curiosity, not administer guilt.',
    ],
    related: ['what-an-archive-chooses-to-forget', 'the-quiet-value-of-abandoned-projects', 'taste-is-a-compression-algorithm'],
  },
  {
    number: '018',
    slug: 'the-quiet-value-of-abandoned-projects',
    title: 'The quiet value of abandoned projects',
    dek: 'Unfinished work can change its maker even when it never becomes useful, polished, public, or complete.',
    kind: 'Essay',
    state: 'Revisited',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Making', 'Hobbies', 'Memory'],
    thesis: 'A project does not need a finished artifact to have produced knowledge, taste, capability, or a more precise understanding of what its maker wants.',
    body: [
      'Abandoned projects are usually described by the object they failed to become. The game was not released, the cabinet was not finished, the essay stopped halfway, and the instrument remains disassembled. Completion is visible; the changes that occurred before completion are harder to inventory.',
      'A project teaches through resistance. Materials behave differently than expected. An apparently small decision opens into a field of dependencies. A borrowed style reveals what feels natural and what does not. By the time the work is abandoned, the maker may understand the problem well enough to know that the original destination is no longer worth reaching.',
      'Stopping can therefore be evidence of judgment rather than its absence. Some projects should be finished through boredom because endurance is part of the lesson. Others survive only because sunk cost has learned to speak in the voice of discipline. The difficult skill is distinguishing a temporary plateau from a purpose that has genuinely expired.',
      'The remains still matter. A fragment can become a reference, a tool can migrate elsewhere, and an old attempt can make a later decision feel obvious. Even when nothing is reused directly, the project has altered the person who will begin the next one. Not every valuable process leaves behind a product.',
    ],
    related: ['a-hobby-should-be-allowed-to-be-useless', 'small-tools-have-long-half-lives', 'owning-books-you-have-not-read'],
  },
  {
    number: '019',
    slug: 'mechanical-keyboards-as-folk-engineering',
    title: 'Mechanical keyboards as folk engineering',
    dek: 'A community took an ordinary tool apart and discovered an unusually social way to decide how an object should feel.',
    kind: 'Essay',
    state: 'Revisited',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 7,
    themes: ['Keyboards', 'Making', 'Communities', 'Design'],
    thesis: 'Custom mechanical keyboards are folk engineering: technical objects developed through shared experiments, local craft, copied patterns, and intensely personal standards of use.',
    body: [
      'A keyboard is a solved object until someone asks a slightly unreasonable question. What if the hands did not need to bend this way? What if the keys sounded lower, the case flexed less, the layout lost a column, or the firmware treated layers as a normal part of typing? One question is enough to reopen the whole device.',
      'The custom keyboard community answers through artifacts. Plates, cases, circuit boards, firmware, mounting systems, and layout files circulate between builders. A design may begin as a personal correction, become a shared reference, be modified by strangers, and return in a form its first maker would not have predicted. Knowledge travels inside objects as much as documentation.',
      'This resembles folk practice more than conventional product development. There is no single roadmap. Terms and conventions emerge through repeated use. Designs are copied with admiration, argued over, refined, and occasionally rediscovered. The boundary between engineer, designer, collector, and craftsperson remains usefully unclear.',
      'The result is not necessarily a better universal keyboard. It is a richer vocabulary for preference. Weight, sound, angle, resistance, layout, and visual proportion become qualities a person can notice and choose. The engineering succeeds when the object becomes more particular—not when everyone agrees on the same answer.',
    ],
    references: [
      { label: 'JP01 custom keyboard case', url: 'https://github.com/Reason0x6/JP01' },
      { label: 'Poverty Alice keyboard project', url: 'https://github.com/Reason0x6/poverty-alice' },
      { label: 'Arisu PCB design files', url: 'https://github.com/Reason0x6/arisu-pcb' },
    ],
    related: ['the-aesthetics-of-constraint', 'a-hobby-should-be-allowed-to-be-useless', 'small-tools-have-long-half-lives'],
  },
  {
    number: '020',
    slug: 'the-soundtrack-changes-the-work',
    title: 'The soundtrack changes the work',
    dek: 'Music does more than fill silence; it changes the pace, emotional temperature, and edges of attention.',
    kind: 'Note',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 5,
    themes: ['Music', 'Attention', 'Ritual'],
    thesis: 'The sound around a task becomes part of its cognitive environment, shaping not only concentration but the kinds of decisions that feel available.',
    body: [
      'Music is often treated as a productivity setting: lyrics for repetitive work, ambience for focus, silence for difficult thought. This makes sound an input to be optimized, as though every task already had a fixed shape and needed only the correct acoustic fuel.',
      'In practice, the soundtrack changes the shape. Fast music can make hesitation feel expensive. Repetition can sustain a long mechanical rhythm. A familiar record creates a room whose emotional weather is already known, while an unfamiliar one keeps asking for small withdrawals of attention. Silence makes certain thoughts louder and others harder to begin.',
      'The effect is not only intensity. Sound influences texture. The same paragraph written against restless percussion may acquire shorter edges; the same design considered with slow music may tolerate more space. These changes are difficult to measure and easy to romanticize, but they are familiar enough to become ritual.',
      'A useful soundtrack is therefore not simply the one that produces the most output. It is the one that supports the kind of attention the work deserves. Sometimes that means momentum. Sometimes it means patience. Sometimes the honest choice is to hear the room.',
    ],
    related: ['a-hobby-should-be-allowed-to-be-useless', 'taste-is-a-compression-algorithm', 'the-aesthetics-of-constraint'],
  },
  {
    number: '021',
    slug: 'what-an-archive-chooses-to-forget',
    title: 'What an archive chooses to forget',
    dek: 'Every collection creates absence through its definitions, acquisition habits, metadata, and limits.',
    kind: 'Essay',
    state: 'Working',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 7,
    themes: ['Archives', 'Memory', 'Curation', 'Legibility'],
    thesis: 'An archive is not memory made neutral; it is a continuing set of decisions about what can be found, what counts as related, and what is permitted to disappear.',
    body: [
      'An archive appears to face backward. Its task is to preserve what already exists against decay, neglect, broken links, obsolete formats, and the ordinary disappearance of attention. Yet every archival decision also acts on the future by determining which traces will remain available to become evidence.',
      'Selection is unavoidable. Storage may be cheap, but description, verification, rights review, migration, and retrieval are not. A collection needs boundaries: white papers but not blog posts, finished editions but not drafts, public links but not restricted copies. Each boundary makes the archive usable and leaves something outside it.',
      'Metadata creates another kind of memory. A document with a poor title, missing author, or vague category may technically survive while becoming practically invisible. Classification makes relationships discoverable, but it can also force unusual work into familiar boxes. What cannot be named is often preserved least effectively.',
      'A responsible archive should therefore document its absences as carefully as its holdings. Why was this object excluded? What could not be verified? Which links disappeared? Where do rights prevent hosting while still permitting a record? Forgetting cannot be eliminated, but it can be made legible. The honest archive preserves both material and the limits of its own memory.',
    ],
    related: ['owning-books-you-have-not-read', 'the-internet-needs-more-small-rooms', 'observability-is-an-editorial-act'],
  },
  {
    number: '022',
    slug: 'against-having-a-take-on-everything',
    title: 'Against having a take on everything',
    dek: 'A considered silence can preserve more intellectual freedom than an opinion assembled to meet the speed of the feed.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 6,
    themes: ['Judgment', 'Attention', 'Culture'],
    thesis: 'Refusing an immediate opinion is not disengagement; it is a way to protect judgment from becoming a performance of consistency and speed.',
    body: [
      'Public conversation rewards the person who already knows. An event occurs, a fragment circulates, and the empty space around it fills with explanation. Speed signals awareness. Certainty travels cleanly. By the time the situation becomes complicated, the first interpretation has accumulated an audience and begun to feel like a possession.',
      'A take is useful when it clarifies stakes or brings relevant experience to bear. The problem is the expectation of universal readiness: that an informed person should be able to convert every new subject into a position on demand. This replaces curiosity with sorting. New information is accepted, rejected, or recruited before it has time to disturb anything.',
      'Immediate opinions also create maintenance work. Once stated publicly, a provisional reaction begins to defend itself. Contradictory evidence threatens not only the claim but the identity that formed around it. Silence preserves an option that performance closes: the ability to encounter a subject without first negotiating with a previous version of oneself.',
      'There are moments when delay is cowardice and neutrality protects the comfortable. Not every question deserves endless contemplation. But urgency should come from the stakes, not the rhythm of distribution. “I do not know yet” is a complete position when it names a genuine condition and leaves the door open for the work of finding out.',
    ],
    related: ['taste-is-a-compression-algorithm', 'everything-eventually-gets-called-content', 'why-chess-feels-honest'],
  },
  {
    number: '023',
    slug: 'what-shape-is-the-internet',
    title: 'What shape is the Internet?',
    dek: 'A measurement programme for reconstructing the Internet across geographic, topological, latency, hyperbolic, and temporal dimensions.',
    kind: 'White paper',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 24,
    themes: ['Internet', 'Networks', 'Geometry', 'Research'],
    thesis: 'The Internet has no single faithful map: its shape is a family of partially compatible geometries revealed by measuring where packets can go, how long they take, and how those relationships change.',
    body: [
      'This white paper treats the Internet as an unknown geometric object reconstructed from observations rather than a physical map decorated with ping times.',
      'It defines a reproducible measurement programme built from pairwise latency, traceroute, routing, geography, peering metadata, multidimensional scaling, graph and hyperbolic embeddings, network tomography, persistent topology, anomaly detection, and temporal statistics.',
      'The paper is a research design, not a report of measurements already performed. Its outputs, uncertainty tests, falsification criteria, and visual grammar are specified in advance so that an eventual map can reveal where the evidence fails to support an attractive shape.',
    ],
    references: [
      { label: 'Read the complete white paper', url: '/papers/what-shape-is-the-internet' },
      { label: 'RIPE Atlas measurement platform', url: 'https://atlas.ripe.net/' },
      { label: 'CAIDA Archipelago measurement infrastructure', url: 'https://www.caida.org/projects/ark/' },
    ],
    related: ['what-an-archive-chooses-to-forget', 'the-internet-needs-more-small-rooms', 'observability-is-an-editorial-act'],
    path: '/papers/what-shape-is-the-internet',
  },
  {
    number: '024',
    slug: 'how-many-facts-does-reality-contain',
    title: 'How many facts does reality actually contain?',
    dek: 'World Rank, factual bases, and a rigorous geometry of how laws convert independent facts into consequences.',
    kind: 'White paper',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 28,
    themes: ['Information', 'Mathematics', 'Explanation', 'Complexity'],
    thesis: 'Relative to a fixed primitive schema and law, the independent factual content of a world is the minimum coordinate evidence that distinguishes it from every other world allowed by that law.',
    body: [
      'This paper formalises World Rank for finite deterministic world models, states the representation rules required to make it well-defined, and separates factual determination from descriptive compression.',
      'It proves universal bounds, monotonicity under stronger laws, an exact minimum-hitting-set characterisation, NP-hardness, additivity for independent products, reduction to nullity for linear systems, a counting bound, and a corrected cellular-automaton inevitability theorem.',
      'It then defines the Law–Fact Frontier and Explanatory Leverage, explains their relationship to Kolmogorov structure functions, teaching dimension, database keys, observability, and recent work, and gives a solver-based research programme without claiming a mathematically false priority.',
    ],
    references: [
      { label: 'Read the complete white paper', url: '/papers/how-many-facts-does-reality-contain' },
      { label: 'Teaching dimension', url: 'https://doi.org/10.1006/jcss.1995.1003' },
      { label: 'Kolmogorov structure functions and model selection', url: 'https://arxiv.org/abs/cs/0204037' },
    ],
    related: ['the-aesthetics-of-constraint', 'configuration-is-a-debt-instrument', 'what-shape-is-the-internet'],
    path: '/papers/how-many-facts-does-reality-contain',
  },
  {
    number: '025',
    slug: 'zero-trust-voice-verification',
    title: 'Zero Trust Voice Verification',
    dek: 'A mutual-authentication architecture for government calls that moves trust out of the phone line and into independently authenticated surfaces.',
    kind: 'White paper',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 24,
    themes: ['Security', 'Identity', 'Government', 'Systems'],
    thesis: 'A government call should be trusted only when the citizen and officer have independently authenticated, explicitly accepted the same short-lived session, and confirmed sensitive actions outside the voice channel.',
    body: [
      'Voice calls create a symmetric identity failure: citizens cannot authenticate an apparent government officer, while officers often rely on personal facts that an impostor may already possess.',
      'This discussion paper specifies a mutual protocol built around an authenticated citizen app, an authorised officer console, a signed short-lived session, explicit acceptance, and a human-readable verifier. It defines the threat model, protocol states, trust anchors, required claims, privacy rules, accessibility fallback and pilot measures.',
      'The design does not claim that a spoken code defeats a live relay. High-risk actions remain independently confirmed in-app, and a secure app-initiated callback is the stronger escalation path. The result is a practical extension of Australia’s emerging in-app call-verification pattern rather than a claim of novel cryptography.',
    ],
    references: [
      { label: 'Read the complete discussion paper', url: '/papers/zero-trust-voice-verification' },
      { label: 'NIST SP 800-207 — Zero Trust Architecture', url: 'https://doi.org/10.6028/NIST.SP.800-207' },
      { label: 'ACMA — SMS Sender ID Register', url: 'https://www.acma.gov.au/articles/2026-06/sms-sender-id-register-goes-live-help-protect-australians-scams' },
    ],
    related: ['observability-is-an-editorial-act', 'interfaces-are-part-of-the-architecture', 'automation-should-reduce-ambiguity'],
    path: '/papers/zero-trust-voice-verification',
  },
  {
    number: '026',
    slug: 'is-team-spirit-the-best-team-in-the-world',
    title: 'Is Team Spirit actually the best team in the world?',
    dek: 'The rankings say yes. The form says yes. The trophy cabinet says “not quite an era.”',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 13,
    themes: ['Counter-Strike', 'Statistics', 'Competition', 'Teams'],
    thesis: 'Spirit have the strongest current claim to number one, but a predictive crown should not be confused with season-long dominance or an era.',
    body: [
      'A ranking, a trophy count and a head-to-head record answer different questions. This editorial uses all three, labels their time windows, and treats “best” as a current estimate rather than a lifetime achievement award.',
      'Spirit entered the data cut-off ranked first, with an 85.7% three-month match win rate and a 13–4 map record at Esports World Cup 2026. Their run included the end of a six-series losing streak to Vitality and a 3–1 final win over FUT.',
      'The resulting verdict is affirmative but deliberately temporary: Spirit are the best team now. Two 2026 titles, a Major semi-final and recent final losses do not yet establish an era.',
    ],
    references: [
      { label: 'Read the complete editorial', url: '/editorials/is-team-spirit-the-best-team-in-the-world' },
      { label: 'HLTV — Spirit team overview', url: 'https://www.hltv.org/team/7020/spirit' },
    ],
    related: ['how-spirit-finally-solved-vitality', 'fut-esports-cinderella-run-or-tier-one-arrival', 'why-chess-feels-honest'],
    path: '/editorials/is-team-spirit-the-best-team-in-the-world',
  },
  {
    number: '027',
    slug: 'how-spirit-finally-solved-vitality',
    title: 'How Spirit finally solved Vitality',
    dek: 'Two maps at parity, one decider blown apart, and a superstar performance that needs an out-of-sample test.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 14,
    themes: ['Counter-Strike', 'Statistics', 'Tactics', 'Teams'],
    thesis: 'Spirit solved the EWC match by reaching Mirage at aggregate parity and then maximising donk’s individual advantage; only a rematch can show whether they solved Vitality itself.',
    body: [
      'Spirit had lost six consecutive series to Vitality. At EWC they won Anubis 13–11, lost Nuke 14–16 and reached the Mirage decider with the aggregate round score tied 27–27.',
      'Mirage finished 13–3. donk went 70–43 across the series with 101.0 ADR and a 1.46 Rating 3.0, while tN1R added a +18 K–D. Together they generated +45 raw K–D; the other three Spirit players combined for –3.',
      'The win is convincing evidence of progress but only one three-map sample. The proposed solution becomes durable only if it survives Vitality’s preparation in the next meeting.',
    ],
    references: [
      { label: 'Read the complete editorial', url: '/editorials/how-spirit-finally-solved-vitality' },
      { label: 'HLTV — Spirit snap six-match losing streak', url: 'https://www.hltv.org/news/45360/spirit-snap-six-match-losing-streak-vs-vitality-to-reach-ewc-semis' },
    ],
    related: ['is-team-spirit-the-best-team-in-the-world', 'fut-esports-cinderella-run-or-tier-one-arrival', 'why-chess-feels-honest'],
    path: '/editorials/how-spirit-finally-solved-vitality',
  },
  {
    number: '028',
    slug: 'fut-esports-cinderella-run-or-tier-one-arrival',
    title: 'FUT Esports: Cinderella run or tier-one arrival?',
    dek: 'A first Big Event final can be variance. Three straight wins over MOUZ look like a team changing tiers.',
    kind: 'Essay',
    state: 'Developed',
    publishedAt: '2026-08-28',
    updatedAt: '2026-08-28',
    readingMinutes: 15,
    themes: ['Counter-Strike', 'Statistics', 'Competition', 'Teams'],
    thesis: 'FUT have already arrived as a legitimate tier-one participant; repeat playoff runs and veto durability will decide whether they become a permanent title contender.',
    body: [
      'FUT entered EWC ranked fourteenth, reached the final undefeated and finished 5–1 in series and 10–6 on maps. Before Paris they had already won PGL Bucharest and placed fourth at EPL Season 23 Finals.',
      'Their strongest signal is repeatability against MOUZ. FUT won a group meeting 2–1 and the prepared quarter-final rematch 2–0, improving the round margin from +5 to +11. HLTV described it as their third consecutive series win over MOUZ.',
      'The full elite subset remained close—FUT were only +4 rounds over 12 fully scored maps against MOUZ, FURIA and Spirit—so the evidence supports arrival rather than dominance.',
    ],
    references: [
      { label: 'Read the complete editorial', url: '/editorials/fut-esports-cinderella-run-or-tier-one-arrival' },
      { label: 'HLTV — FUT sweep MOUZ', url: 'https://www.hltv.org/news/45355/fut-sweep-mouz-to-make-ewc-semis' },
    ],
    related: ['is-team-spirit-the-best-team-in-the-world', 'how-spirit-finally-solved-vitality', 'why-chess-feels-honest'],
    path: '/editorials/fut-esports-cinderella-run-or-tier-one-arrival',
  },
];
